### ISSUE TITLE
when the connected etcd node is down or in error, jectd watch cluster would not work.

### ISSUE THREAD

**Issue by Cifer0325** [etcd-io/jetcd#1012]
In java program, I used the v0.5.10 jetcd to watch a ETCD cluster.
Basically, the jectd builds the connection with the dns domain, which is resolved into three ETCD IPs. Then, while I stop the ETCD sever on one node that the program connected, the ETCD watch was useless and could not watch any changes for keys. It was not until I restart the ETCD server, stop before, that this watch worked again. I retried many times and this problem alway happends.
thus, using DNS domain to connect ETCD cluster with java SDK, the ETCD watch does not watch after the connected etcd node breaks down or not work. it is likely that the DNS domain would not be resolved into other worked server ips when some node does not work.
I remember that the client will connect to health node when some ETCD node is unhealthy in ETCD Go package .

**Comment by lburgazzoli** [comment]
Can you provide an example ? 
Can you also try with etcdctl ?

The dns resolver refreshes the IPs automatically buit that's not under the control of jetcd (https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/main/java/io/etcd/jetcd/resolver/DnsSrvNameResolver.java#L125-L161) but I guess the dns resolves the 3 IPs regardless of the fact that one instance is up or down.

As a note, the default [load balance policy](https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/main/java/io/etcd/jetcd/ClientConnectionManager.java#L216-L220) is `pick_frisr` so you may want to change it to something else like `round_robin` or provide your own

**Comment by Cifer0325** [comment]
hi~ @lburgazzoli,
I think I expressed sth wrong. I agree that the dns resolver refreshes the IPs automatically. Based on my situation, the watch have been stablished. and then , I stop one of ETCD server, which the watch real connect to. On next, I continued to update value successfully for ETCD cluster. I found the watcher did not get any response from cluster. But, while I restarted the nod stop before, the  watcher was recovered and accept the response again.

for example: 
the etcd cluster domian is the newinit.etcd.jddb.com. it could resolve into 3 ip, it just likes the following.
$ nslookup newinit.etcd.jddb.com
Server:		192.168.31.1
Address:	192.168.31.1#53

Non-authoritative answer:
Name:	newinit.etcd.jddb.com
Address: 11.80.13.116
Name:	newinit.etcd.jddb.com
Address: 11.80.11.207
Name:	newinit.etcd.jddb.com
Address: 11.80.35.166
I use jetcd to create etcd connnect with the domain and do watch. while I found the watch connnection connect to ip(11.80.13.116) in fact and I stop etcd server on ip (11.80.13.116), the watcher stop getting any response from ETCD cluster but run.

I tried to do same thing with etcdctl(3.5.0) . the watcher always get the response, no mater of which node broke down.

**Comment by lburgazzoli** [comment]
Please, can you provide an example/reproducer ?
Did you try to change the load balancing policy ?

**Comment by Cifer0325** [comment]
String urls = "http://newinit.etcd.jddb.com:2379";
        Client etcdClient = Client.builder().endpoints(urls).build();
        String key = "/cy";
        Integer maxEvents = Integer.MAX_VALUE;
        CountDownLatch latch = new CountDownLatch(maxEvents);
        Watch.Watcher watcher = null;
        try
        {
            ByteSequence watchKey = ByteSequence.from(key, UTF_8);
            WatchOption watchOpts = WatchOption.newBuilder().build();

            watcher = etcdClient.getWatchClient().watch(watchKey, watchOpts, response -> {
                for (WatchEvent event : response.getEvents())
                {

                    SimpleDateFormat sdf = new SimpleDateFormat();// 格式化时间
                    sdf.applyPattern("yyyy-MM-dd HH:mm:ss a");// a为am/pm的标记
                    Date date = new Date();// 获取当前时间
                    System.out.println("now:" + sdf.format(date));

                    System.out.println("watch type= \"" + event.getEventType().toString() + "\",  key= \""
                            + Optional.ofNullable(event.getKeyValue().getKey()).map(bs -> bs.toString(UTF_8)).orElse("")
                            + "\",  value= \"" + Optional.ofNullable(event.getKeyValue().getValue())
                            .map(bs -> bs.toString(UTF_8)).orElse("")
                            + "\"");
                }

                latch.countDown();
            });

            latch.await();
        }
        catch (Exception e)
        {
            System.out.println(e);
            if (watcher != null)
            {
                watcher.close();
                etcdClient.close();
            }
            throw e;
        }

above code is my work code.
I am fuzzy about the load balancing policy. would your mind provide some load balancing policy for me, except "pick_first".  I wan to change it and try again.

**Comment by lburgazzoli** [comment]
So here you are not using the DNS+SRV resolver provided by jetcd and in such case, the resolution returns a single address. 

At the moment this functionality is not implemented  but I guess it can be: do you have any time to implement it ? I don't have too much time to do it myself.

As workaround, you can list the 3 addresses or use DNS+SRV

**Comment by Cifer0325** [comment]
thank for your explain, I got it~

**Comment by Cifer0325** [comment]
hi~ @lburgazzoli 
while I run with master env, I found this issue have been solved. Compared with 0.5.10 jetcd, the master branch have a AbstractNameResolver class to create doResolve function which can resolve the domain.
would you mind to tell me where the master branch to release a new version?
or Could your provide a new released version which could run on JAVA 8 env ?  ^.^

**Comment by lburgazzoli** [comment]
> hi~ @lburgazzoli while I run program complied by master branch and do the watch with above the situation, I found this issue have been solved. Compared with 0.5.10 jetcd, the master branch have a AbstractNameResolver class to create doResolve function which can resolve the domain. would you mind to tell me where the master branch to release a new version? or 

I think it solve it by chance as the logic has not changed so maybe when a node goes down, then its IP is removed from the dns resolution ?  I think I will re-work the resolver impl we have so you can also use the [dns resolver from etcd-java](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/DnsNameResolver.java).

> Could your provide a new released version which could run on JAVA 8 env ? ^.^

Is Java 8 really needed ? 
My plan is to support LTS - 1 so now that Java 17 is out, Java 11 should be the minumum

**Comment by Cifer0325** [comment]
In my country, over thousands of companies  program is deployed based on free JAVA 8. Even Java 17 is out, it will take much time and programmer to change JAVA 8  to Java 17.  Those companies will not update old and stable program into a new java env.
maybe a special version ^.^~

**Comment by lburgazzoli** [comment]
I can certainly do a release with Java 8 but be aware that support will be removed soon.
I really don't have enough time to keep support for Java 8

**Comment by lburgazzoli** [comment]
I have release version 0.6.0 but unfortunately some plugins do not support anymore Java 8 so I can only use Java 11
