### ISSUE TITLE
Page not found in README.md

### ISSUE THREAD

**Issue by hypocrite30** [etcd-io/jetcd#1018]
The [instruction ](https://github.com/etcd-io/etcd/blob/main/Documentation/dl_build.md) in [jetcd-ctl/README.md](https://github.com/etcd-io/jetcd/blob/master/jetcd-ctl/README.MD) is missing.
Plz update doc. Thanks a lot.

**Comment by lburgazzoli** [comment]
A PR to fix the issue would be very welcome
