### ISSUE TITLE
Could not work well when network partitions.

### ISSUE THREAD

**Issue by weibubli** [etcd-io/jetcd#1022]
I found that the client's retry mechanism does not handle etcd exceptions. 
For example, if the node requested by the client is partitioned in the cluster, the client does not retry the request on other nodes. Although the cluster is available at this time, the client fails to request the request.

How to handle this exception so that the client can successfully request in this case？

The following is the code for determining the exception type.
https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/main/java/io/etcd/jetcd/Util.java#L81

The following is its judgment implementation code, in io.grpc.Status

```
    public static Status fromThrowable(Throwable t) {
        for(Throwable cause = (Throwable)Preconditions.checkNotNull(t, "t"); cause != null; cause = cause.getCause()) {
            if (cause instanceof StatusException) {
                return ((StatusException)cause).getStatus();
            }

            if (cause instanceof StatusRuntimeException) {
                return ((StatusRuntimeException)cause).getStatus();
            }
        }

        return UNKNOWN.withCause(t);
    }

```

When this function is entered, the exception type is UNAVAILABLE, but it is changed to unknown after it is determined that it does not belong to the StatusException or StatusRuntimeException class.

**Comment by vongosling** [comment]
This is a verified problem by OpenChaos(https://github.com/openmessaging/openchaos). I found the [doc](https://etcd.io/docs/v3.5/learning/design-client/) said "Client-side keepalive ping still does not reason about network partitions...  (see etcd#8673 for more detail)."

It seems no answer to this problem, right? ping @xiang90
