### ISSUE TITLE
In kubernetes environment, use headless mode to connect etcd. After etcd restarts, it cannot be connected

### ISSUE THREAD

**Issue by 20190101wkl** [etcd-io/jetcd#1025]
**Describe the bug**
In kubernetes environment, use headless mode to connect etcd. After etcd restarts, it cannot be connected

**To Reproduce**
1.create client using endpoints
`Client client = Client.builder().endpoints(
"http://common-etcd-etcd-0.common-etcd-etcd-headless.common.svc.cluster.local:2379", 
"http://common-etcd-etcd-1.common-etcd-etcd-headless.common.svc.cluster.local:2379", 
"http://common-etcd-etcd-2.common-etcd-etcd-headless.common.svc.cluster.local:2379").build();`
2.etcd service information before restart
![image](https://user-images.githubusercontent.com/46295149/144957390-aac83886-06f9-4eb0-94e4-7f0b449f2b6f.png)
3.unable to connect after etcd is restarted，Jetcd buffers the address of etcd service before restart
![image](https://user-images.githubusercontent.com/46295149/144957278-9ec95692-5e29-4d55-b0d5-f9065c7a79cf.png)
4.after restarting etcd, etcd service information
![image](https://user-images.githubusercontent.com/46295149/144957502-b0d0932e-91a1-450e-96cd-462d640c2eb5.png)

**Comment by lburgazzoli** [comment]
this has bern fixed in the latest release, can you try it out

**Comment by 20190101wkl** [comment]
> this has bern fixed in the latest release, can you try it out
The latest releases version is v0.5.0, which is the version we use.
![image](https://user-images.githubusercontent.com/46295149/144996622-8ff6ddb5-42ad-4fbf-ad54-61d96477f3e9.png)

**Comment by 20190101wkl** [comment]
> this has bern fixed in the latest release, can you try it out

The latest releases version is v0.5.0, which is the version we use.

**Comment by lburgazzoli** [comment]
No, the latest version is 0.6.1 (see https://search.maven.org/search?q=jetcd-core)
That is the latest version on github but it is not up to date

**Comment by 20190101wkl** [comment]
> No, the latest version is 0.6.1 (see https://search.maven.org/search?q=jetcd-core) That is the latest version on github but it is not up to date

OK, thanks. I'll try the latest version

**Comment by 20190101wkl** [comment]
> No, the latest version is 0.6.1 (see https://search.maven.org/search?q=jetcd-core) That is the latest version on github but it is not up to date

Jdk11 is required for release version 0.6.1. Our project uses JDK1.8. Has this problem been solved in the release version compatible with JDK1.8

**Comment by lburgazzoli** [comment]
Well, it is not a problem per se as the goal is to maintain support for LTS - 1 so Java 11 at the moment.

I'm the only maintainer so it is hard for me to maintain everything, if you want to help re-introducing support for Java 8, then  feel free to provide a PR

**Comment by 20190101wkl** [comment]
> this has bern fixed in the latest release, can you try it out

OK, I mean, in JDK1.8 compatible distributions (such as 0.5.11 and 0.5.10), has the problem that etcd will lose connection after restarting been solved

**Comment by lburgazzoli** [comment]
Not sure about what I can do, will have a look in the coming days
