### ISSUE TITLE
confused by the lock api

### ISSUE THREAD

**Issue by lpcy** [etcd-io/jetcd#1036]
I simply tested the lock api, but the code execution was beyond my expectation. First, I use etcdctl tool to occupy a lock, then execute the code, hoping to wait for the lock to be released, and then close the etcdctl tool. I thought the code would get lock and continue to execute, but it didn't (no "lock ok!" print). Did I write something wrong?
command: `etcdctl  --endpoints=myip:port lock lockName notepad`
java code:
```java
public static void main(String[] args) throws ExecutionException, InterruptedException {
        Client client = Client.builder()
                .endpoints("http://myip:port").build();
        Lock lockClient = client.getLockClient();
        Lease leaseClient = client.getLeaseClient();
        LeaseGrantResponse leaseGrantResponse = leaseClient.grant(5).get();
        long leaseId = leaseGrantResponse.getID();
        leaseClient.keepAlive(leaseId, new StreamObserver<LeaseKeepAliveResponse>() {
            @Override
            public void onNext(LeaseKeepAliveResponse leaseKeepAliveResponse) {
                logger.info("[keepAlive]onNext");
            }
            @Override
            public void onError(Throwable throwable) {
                logger.info("[keepAlive]onError");
            }

            @Override
            public void onCompleted() {
                logger.info("[keepAlive]onCompleted");
            }
        });
        ByteSequence lockName = ByteSequence.from("lockName", Charset.forName("utf8"));
        logger.info("try lock...");
        lockClient.lock(lockName,leaseId).get();
        logger.info("lock ok!");
    }

**Comment by sudoHackIn** [comment]
Hi, @lpcy what versions(jetcd, etcd ,etcdclt) do you use? I tried your example and it did work as you expect.
May be there is issue with lock acquiring with etcdctl?
Try 
`etcdctl --endpoints=--endpoints=myip:port lock lockName ` (without notepad)

**Comment by lpcy** [comment]
@sudoHackIn Thank you for your test. I found it was because of one bug in 3.x version etcd server. When one program that own and requiring a lot of lock on same lock name is suddenly killed, the memory data of the server is leaked. And this causes all clients to be unable to acquire new lock until the etcd server restart.

**Comment by sudoHackIn** [comment]
> @sudoHackIn Thank you for your test. I found it was because of one bug in 3.x version etcd server. When one program that own and requiring a lot of lock on same lock name is suddenly killed, the memory data of the server is leaked. And this causes all clients to be unable to acquire new lock until the etcd server restart.

 So, there is no issue in jecd? Can you close it?

**Comment by lpcy** [comment]
@sudoHackIn Yes, of course.
