### ISSUE TITLE
Make future.get() throw exception when streamIds exhausted.

### ISSUE THREAD

**Issue by horizonzy** [etcd-io/jetcd#1038]
**Versions**
- jetcd: 0.4.1
- java: jdk8

**Describe the bug**
```
Future future = etcdClient.getKVClient().get(ByteSequence.from(someKey));
Object result = future.get(); // without timeout
```
If user code as above, when grpc htttp2 stream id exhausted, it will block forever.

Is it can throw exception when stream id exhausted.

**Comment by lburgazzoli** [comment]
can you please provide a reproducer ?

**Comment by horizonzy** [comment]
Fine, I will reproduce it

**Comment by horizonzy** [comment]
Hi, I reproduce it, it work now, close it
