### ISSUE TITLE
how to debug a ssl certificate bug

### ISSUE THREAD

**Issue by leland17** [etcd-io/jetcd#1040]
**Versions**
- etcd: _add the etcd version here_  3.4.13.2
- jetcd: _add the jetcd version here_ 0.5.9
- java: _add the java version here_ 11

**Describe the bug**
the jetcd do not show the log when the client connection failed due to the ssl shakehands. the only log is the client deadline. 

**To Reproduce**
Steps or reproducer to reproduce the behavior. 
This section *must* be provided, if not, the issue may not get attention.

**Expected behavior**

**Additional context**

**Comment by sudoHackIn** [comment]
Hi, jetcd internally use netty as a transport, so you can enable netty logs to debug ssl issue.
also try enabling java ssl logs 
https://docs.oracle.com › ReadDebug
Debugging SSL/TLS connections - Oracle Help Center
