### ISSUE TITLE
Jetcd watch stream not receiving updates after restarting etcd cluster nodes

### ISSUE THREAD

**Issue by yashugrankar** [etcd-io/jetcd#1046]
**Versions**
- etcd: 3.3
- jetcd: 0.5.11
- java: openjdk 8

**Describe the bug**
I am planning to use jetcd in an application, which sets up a watcher to check for updates to a key range in a 3 node etcd-cluster. This watcher is expected to run till the application terminates.

I want to determine the client behaviour when the etcd cluster is down. To do this, I'm starting a watch on the cluster through jetcd, then bringing down majority of the cluster nodes. Once that is done, I'm restarting the nodes. 

What I have observed is that once the cluster nodes are brought up again, any subsequent PUT / DELETE operations are not received by the jetcd watch event handler. This is problematic, as it implies that the client app will not be able to recover from a temporary etcd cluster outage unless it is restarted.

**To Reproduce**

1. To initiate the watch, I'm running this code snippet:

```
public void startConfigWatch() {
        Client client = Client.builder()
                .endpoints("http://10.120.12.209:2379", "http://10.120.12.211:2379", "http://10.120.12.241:2379")
                .loadBalancerPolicy("round_robin").connectTimeout(Duration.ofSeconds(2)).waitForReady(false)
                .build();

        client.getWatchClient().watch(ByteSequence.from(String.join("/", "root-key"), StandardCharsets.UTF_8),
                WatchOption.newBuilder().isPrefix(true).withRequireLeader(true).build(), watchResponse -> {
                    watchResponse.getEvents().forEach(watchEvent -> {
                        System.out.println(watchEvent.getKeyValue().getKey() + " -> " + watchEvent.getKeyValue().getValue());
                    });
                }, Throwable::printStackTrace);

        while(true);
}
```

2. I am executing a PUT operation through etcdctl:

```
etcdctl --endpoints=10.120.12.209:2379,10.120.12.211:2379,10.120.12.241:2379 put "root-key/dummy-config-1/value1" 20
```
The following message is being printed to the console, which indicates the watch event handler is working fine.

```
root-key/dummy-config-1/value1 -> 20
```

3. I'm now taking down 2 of the 3 nodes in the cluster using `systemctl stop`. Once they are all down, I'm starting the etcd process on those nodes again using `systemctl start`

4. Once this is done, I'm executing another put operation using etcdctl:

```
etcdctl --endpoints=10.120.12.209:2379,10.120.12.211:2379,10.120.12.241:2379 put "root-key/dummy-config-1/value2" 30
```

The new key / value is not being printed this time. All I see is a couple of PING entries in the debug logs

```
201391 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler  - [id: 0x46d72275, L:/10.80.19.86:61180 - R:/10.120.12.241:2379] OUTBOUND PING: ack=false bytes=1111
201523 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler  - [id: 0x46d72275, L:/10.80.19.86:61180 - R:/10.120.12.241:2379] INBOUND PING: ack=true bytes=1111
208045 [grpc-nio-worker-ELG-1-9] DEBUG io.grpc.netty.NettyClientHandler  - [id: 0x93e77103, L:/10.80.19.86:61209 - R:/10.120.12.211:2379] OUTBOUND PING: ack=false bytes=1111
208177 [grpc-nio-worker-ELG-1-9] DEBUG io.grpc.netty.NettyClientHandler  - [id: 0x93e77103, L:/10.80.19.86:61209 - R:/10.120.12.211:2379] INBOUND PING: ack=true bytes=1111
211352 [grpc-nio-worker-ELG-1-10] DEBUG io.grpc.netty.NettyClientHandler  - [id: 0x0e71ee44, L:/10.80.19.86:61212 - R:/10.120.12.209:2379] OUTBOUND PING: ack=false bytes=1111
211486 [grpc-nio-worker-ELG-1-10] DEBUG io.grpc.netty.NettyClientHandler  - [id: 0x0e71ee44, L:/10.80.19.86:61212 - R:/10.120.12.209:2379] INBOUND PING: ack=true bytes=1111
```

I am able to read the new key through etcdctl though, which means the put operation was successful.

```
> etcdctl --endpoints=10.120.12.209:2379,10.120.12.211:2379,10.120.12.241:2379 get "root-key/dummy-config-1/value2" --prefix=true
root-key/dummy-config-1/value2
30
```

**Expected behavior**
The running watch channel should be receiving PUT / DELETE updates from the etcd cluster after the cluster nodes have been restarted.

**Comment by lburgazzoli** [comment]
can you test with a version built from the main branch ?

**Comment by yashugrankar** [comment]
@lburgazzoli I tried running the test again after using a new build from the main branch. I'm still getting the same result (i.e updates are not being received after nodes are restarted).

**Comment by lburgazzoli** [comment]
ok, I have very limited time so it would be very beneficial if you have time to create a test for this so that I can take a look.
