### ISSUE TITLE
version 0.6.x not support Java8

### ISSUE THREAD

**Issue by wuyueandrew** [etcd-io/jetcd#1053]
**Versions**
- etcd: _add the etcd version here_
- jetcd: 0.6.0,0.6.1
- java: 8

**Describe the bug**
version 0.6.x not support Java8

io/etcd/jetcd/resolver/DnsSrvResolverProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by lburgazzoli** [comment]
Version 0.7.0 with Java 8 support has been released
