### ISSUE TITLE
TryLock Support

### ISSUE THREAD

**Issue by Cesarla** [etcd-io/jetcd#1056]
**Describe the solution you'd like**
[etcd 3.5](https://github.com/etcd-io/etcd/blob/4504daa6b03f361a44a760e4bd5caf0e4ae9fc7e/CHANGELOG/CHANGELOG-3.5.md#v350-2021-06) added support for try-lock, but so far jetcd doesn't support it:
> Add https://github.com/etcd-io/etcd/pull/11104 method to clientv3/concurrency/Mutex. A non-blocking method on Mutex which does not wait to get lock on the Mutex, returns immediately if Mutex is locked by another session.

Are there any plans to add support for it?

**Comment by sudoHackIn** [comment]
@Cesarla, etcd grpc api is not exposing method wit same semantics. [I created issue in etcd](https://github.com/etcd-io/etcd/issues/14062), so will wait, what they say
