### ISSUE TITLE
Set daemon to true when creating background thread pool, and also set a proper name for the thread

### ISSUE THREAD

**Issue by Apache9** [etcd-io/jetcd#1057]
**Is your feature request related to a problem? Please describe.**
In our company, some users do not close etcd client properly and non daemon thread will make their process hang there forever.
We can pass in an executorService when constructing etcd client through ClientBuilder, but in WatchImpl we will always create a non daemon thread pool. And what's more, the thread just uses the default name pattern so it is hard to identify what it is used for when checking the jstack output.

**Describe the solution you'd like**
Creating daemon thread by default, and give the thread a proper name which is easy to identify

**Describe alternatives you've considered**
Add a method in ClientBuilder to pass in a ExecutorService to be used by WatchImpl, so we can control it by our own.

**Additional context**
No.

**Comment by yijianli** [comment]
We face the same issue, +1

**Comment by lburgazzoli** [comment]
@Apache9 any chance you contribute a fix ?

**Comment by Apache9** [comment]
Sure, let me provide a PR.

**Comment by Apache9** [comment]
Opened #1062 

Do I need to sign something like an ICLA before contributing code?

Thanks.

**Comment by lburgazzoli** [comment]
no, everything is fine
