### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by yijianli** [etcd-io/jetcd#1066]
Can i have a new release for the jetcd-all?

**Comment by lburgazzoli** [comment]
I will release a new version of jetcd this week but jetcd-all is not more published/supported

**Comment by yijianli** [comment]
Curious. Why the jetcd-all is no longer supported? In our case, the Grpc lib in jetcd is not compatible with our grpc version

**Comment by lburgazzoli** [comment]
I have very limited time to support the library so I had to remove some bits to ease the maintenance.

I'm happy to get it back if someone steps up and help maintaining it

**Comment by yijianli** [comment]
Ok, got it. I will help to handle the jetcd-all for this version. Thanks again

**Comment by vinsia** [comment]
@lburgazzoli there is a PR to shadow the jetcd-core, https://github.com/etcd-io/jetcd/pull/1068.
As the description, I did not test the release process. Can you help to do that? or how can I verify that?

**Comment by lburgazzoli** [comment]
you should be bale to dry-run a release

**Comment by yijianli** [comment]
let me try

**Comment by vinsia** [comment]
@lburgazzoli it is ok to run `./gradlew jetcd-core:publishToMavenLocal`

**Comment by vinsia** [comment]
can you help to merge this PR and publish a new release, thanks

**Comment by yijianli** [comment]
@lburgazzoli ping

**Comment by lburgazzoli** [comment]
v0.7.1 has been released
