### ISSUE TITLE
Watches not working after upgrading jetcd to 0.6.1 or newer

### ISSUE THREAD

**Issue by gunnarmorling** [etcd-io/jetcd#1075]
**Versions**
- etcd: 3.4.7
- jetcd: 0.6.1 and newer
- java: 11

**Describe the bug**
Watches aren't notified. After a while, this error is shown:

```
Jul 27, 2022 4:15:14 PM io.grpc.netty.NettyClientHandler$2 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: too_many_pings
Jul 27, 2022 4:15:14 PM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 60.000.000.000
```

**To Reproduce**
Steps or reproducer to reproduce the behavior. 
This section *must* be provided, if not, the issue may not get attention.

Build [this PR](https://github.com/gunnarmorling/kcetcd/pull/4) (which updates the kcetcd project to the latest jetcd) and observe how is stuck. It is stuck because it doesn't receive any of the expected change events from that connector, which in turn doesn't fire these events as it doesn't receive any watch notifications.

**Expected behavior**

Watches are firing, the test passes.

**Additional context**
n/a

**Comment by lburgazzoli** [comment]
This is cause by the client keep sending ping but the server is not configure to handle them, you can disable it using keepaliveWithoutCalls, i.e.:

```java
    Client client = Client.builder()
                .endpoints("...")
                .keepaliveWithoutCalls(false)
                .build();
```

**Comment by gunnarmorling** [comment]
Thanks a lot, @lburgazzoli! All is working as expected now with 0.7.3. Appreciate the quick help!
