### ISSUE TITLE
Could not initialize class io.grpc.netty.NettyChannelBuilder

### ISSUE THREAD

**Issue by luomengY** [etcd-io/jetcd#1085]
**Versions**
- etcd: v3.5.4
- jetcd: 0.7.1,0.7.3
- java:java11
**Describe the bug**

**To Reproduce**
Steps or reproducer to reproduce the behavior. 
This section *must* be provided, if not, the issue may not get attention.

**Expected behavior**

**Additional context**
code:
 Client    client = Client.builder().endpoints(
                "http://121.4.115.5:4379"
        ).build();
 Lock  lock = client.getLockClient();
question:
When the program runs to "lock = client.getLockClient()", an error is reported: "Could not initialize class io.grpc.netty.NettyChannelBuilder".It can run normally on the windows system, but the centos system reports this error.
maven:
        <dependency>
            <groupId>io.etcd</groupId>
            <artifactId>jetcd-core</artifactId>
            <version>0.7.3</version>
        </dependency>

**Comment by lburgazzoli** [comment]
The library is regularly tested on linux (ubuntu, fedora) and I'm not aware of such issue.

I recommend to check the setup (libs, java version, etc)

**Comment by luomengY** [comment]
The java version is 11, there is no conflicting library with jetcd in the platform, grpc-netty is also successfully introduced, but the error NoDefoundClass:Could not initialize class io.grpc.netty.NettyChannelBuilder is reported.


---Original---
From: "Luca ***@***.***&gt;
Date: Sun, Jul 31, 2022 23:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [etcd-io/jetcd] Could not initialize classio.grpc.netty.NettyChannelBuilder (Issue #1085)




 
The library is regularly tested on linux (ubuntu, fedora) and I'm not aware of such issue.
 
I recommend to check the setup (libs, java version, etc)

**Comment by lburgazzoli** [comment]
NoClassDefFound is when the definition of such class does not exists anymore so there must be something different

**Comment by luomengY** [comment]
However, after unzipping the "grpc-netty-1.42.1.jar" package, the "NettyChannelBuilder.class" file can be found. NettyChannelBuilder should be defined, but not recognized at runtime.




---Original---
From: "Luca ***@***.***&gt;
Date: Mon, Aug 1, 2022 00:14 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [etcd-io/jetcd] Could not initialize classio.grpc.netty.NettyChannelBuilder (Issue #1085)




 
NoClassDefFound is when the definition of such class does not exists anymore so there must be something different

**Comment by lburgazzoli** [comment]
I'd need a reproducer for that but I strongly recommend to review your classpath

**Comment by luomengY** [comment]
import io.etcd.jetcd.*;
import io.etcd.jetcd.kv.GetResponse;
import io.etcd.jetcd.lease.LeaseGrantResponse;
import io.etcd.jetcd.lock.LockResponse;
import io.etcd.jetcd.options.WatchOption;
import io.grpc.stub.StreamObserver;


import java.nio.charset.StandardCharsets;

import java.util.concurrent.*;

import io.etcd.jetcd.lease.LeaseKeepAliveResponse;
import org.junit.Test;


public class JEtcdTest {
    private Client client;
    private Lock lock;
    private Lease lease;
    //单位：秒
    private long lockTTl = 1;
    private ByteSequence lockKey = ByteSequence.from("/root/lock", StandardCharsets.UTF_8);
    private ScheduledExecutorService scheduledThreadPool = Executors.newScheduledThreadPool(2);
    private Watch watch;


    public void setUp() {
        client = Client.builder().endpoints(
                "http://10.3.75.143:6379"
        ).build();
        lock = client.getLockClient();
        lease = client.getLeaseClient();
        this.watch = client.getWatchClient();
        monitor();
    }

    private void monitor() {
        ByteSequence key = ByteSequence.from("masterIp", StandardCharsets.UTF_8);
        watch.watch(key, WatchOption.newBuilder().withPrevKV(true).build(), listener -> {
            listener.getEvents().forEach(event -> {
                switch (event.getEventType()) {
                    case DELETE: {
                        break;
                    }
                    case PUT: {
                        try {
                            String preMaster = event.getPrevKV().getValue().toString(StandardCharsets.UTF_8);
                            String currentMaster = event.getKeyValue().getValue().toString(StandardCharsets.UTF_8);
                            System.out.println("preMaster=====" + preMaster + "------" + event.getPrevKV().getKey().toString(StandardCharsets.UTF_8));
                            System.out.println("currentMaster=====" + currentMaster + "------" + event.getKeyValue().getKey().toString(StandardCharsets.UTF_8));
                            //当key推送触发
                            break;
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        } finally {

                        }
                    }
                    default:
                        break;
                }
            });
            ;
        });
    }


    @Test
    public void lockTest1toMaster() throws InterruptedException, ExecutionException {
        setUp();
        CompletableFuture<LeaseGrantResponse> completableFuture = lease.grant(lockTTl);
        LeaseGrantResponse leaseGrantResponse = completableFuture.get();
        long leaseId = leaseGrantResponse.getID();
        lease.keepAlive(leaseId, new StreamObserver<LeaseKeepAliveResponse>() {
            @Override
            public void onNext(LeaseKeepAliveResponse value) {
                System.err.println("LeaseKeepAliveResponse value:" + value.getTTL());
            }

            @Override
            public void onError(Throwable t) {
                scheduledThreadPool.shutdownNow();
                t.printStackTrace();
            }

            @Override
            public void onCompleted() {
                scheduledThreadPool.shutdownNow();
            }
        });

        CompletableFuture<LockResponse> lockResponseCompletableFuture = lock.lock(lockKey, leaseId);
        LockResponse lockResponse = lockResponseCompletableFuture.get();
        ByteSequence byteSequence = lockResponse.getKey();
        String lockstr = byteSequence.toString(StandardCharsets.UTF_8);
        scheduledThreadPool.submit(() -> {
            while (true) {
                System.err.println("我是主服务开始工作了");
                KV kv = client.getKVClient();
                ByteSequence key = ByteSequence.from("masterIp", StandardCharsets.UTF_8);
                ByteSequence value = ByteSequence.from("10.3.71.117", StandardCharsets.UTF_8);
                kv.put(key, value);
                TimeUnit.SECONDS.sleep(1);
            }
        });
        TimeUnit.DAYS.sleep(1);
    }

    @Test
    public void lockTest2toStandby() throws InterruptedException, ExecutionException {
        setUp();
        CompletableFuture<LeaseGrantResponse> completableFuture = lease.grant(lockTTl);
        boolean done = completableFuture.isDone();
        LeaseGrantResponse leaseGrantResponse = completableFuture.get();
        long leaseId = leaseGrantResponse.getID();
        lease.keepAlive(leaseId, new StreamObserver<LeaseKeepAliveResponse>() {
            @Override
            public void onNext(LeaseKeepAliveResponse value) {
                System.err.println("LeaseKeepAliveResponse value:" + value.getTTL());
            }

            @Override
            public void onError(Throwable t) {
                scheduledThreadPool.shutdownNow();
                t.printStackTrace();
            }

            @Override
            public void onCompleted() {

                scheduledThreadPool.shutdownNow();
            }
        });
        CompletableFuture<LockResponse> lockResponseCompletableFuture = lock.lock(lockKey, leaseId);
        LockResponse lockResponse = lockResponseCompletableFuture.get();
        ByteSequence byteSequence = lockResponse.getKey();
        String lockstr = byteSequence.toString(StandardCharsets.UTF_8);
        scheduledThreadPool.submit(() -> {
            while (true) {
                System.err.println("我是备用服务，我开始工作了，估计主服务已经挂了");
                TimeUnit.SECONDS.sleep(1);
            }
        });
        TimeUnit.DAYS.sleep(1);
    }

    @Test
    public void lockTest3toStandby() throws InterruptedException, ExecutionException {
        setUp();
        long leaseId = lease.grant(lockTTl).get().getID();
        lease.keepAlive(leaseId, new StreamObserver<LeaseKeepAliveResponse>() {
            @Override
            public void onNext(LeaseKeepAliveResponse value) {
                System.err.println("LeaseKeepAliveResponse value:" + value.getTTL());
            }

            @Override
            public void onError(Throwable t) {
                scheduledThreadPool.shutdownNow();
                t.printStackTrace();
            }

            @Override
            public void onCompleted() {
                scheduledThreadPool.shutdownNow();
            }
        });
        lock.lock(lockKey, leaseId).get().getKey();
        scheduledThreadPool.submit(() -> {
            while (true) {
                System.out.println("test3");
                TimeUnit.SECONDS.sleep(1);
            }
        });
        TimeUnit.DAYS.sleep(1);
    }
}

**Comment by luomengY** [comment]
this is my code.

**Comment by lburgazzoli** [comment]
I don't think that the code make much difference as you mention it works on windows, what it may be needed is a zip containing the applicaiton and the script you use to run it

**Comment by luomengY** [comment]
ectionManager at io.etcd.jetcd.ClientImpl.<init>(ClientImpl.java:49) at io.etcd.jetcd.ClientBuilder.build(ClientBuilder.java:317)

**Comment by luomengY** [comment]
After I changed the version of jetcd to 0.3.0, an error was reported at client = Client.builder().endpoints("http://10.3.75.143:6379").build(): Caused by: java.lang. NoClassDefFoundError: Could not initialize class io.etcd.jetcd.ClientConnectionManager at io.etcd.jetcd.ClientImpl.<init>(ClientImpl.java:49) at io.etcd.jetcd.ClientBuilder.build(ClientBuilder.java:317), And there are no conflicts with jetcd-related dependencies in the code.

**Comment by lburgazzoli** [comment]
Again, I don't think the code matter, such error are usually because of a misconfiguration of the classpath and or env issues. I strongly recommend you revisit your set-up or provide a zip file with the exact same set-up you are using in windows and centos.

**Comment by luomengY** [comment]
Thanks, I have solved this problem!


---Original---
From: "Luca ***@***.***&gt;
Date: Tue, Aug 2, 2022 15:26 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [etcd-io/jetcd] Could not initialize classio.grpc.netty.NettyChannelBuilder (Issue #1085)




 
Again, I don't think the code matter, such error are usually because of a misconfiguration of the classpath and or env issues. I strongly recommend you revisit your set-up or provide a zip file with the exact same set-up you are using in windows and centos.
