### ISSUE TITLE
How can I judge that the current client is connected to the server, I have not found a judgment method related to boolean etcdclient.isconnetcted().

### ISSUE THREAD

**Issue by luomengY** [etcd-io/jetcd#1086]
How can I judge that the current client is connected to the server, I have not found a judgment method related to boolean etcdclient.isconnetcted().

**Comment by lburgazzoli** [comment]
there's no such feature at the moment, what is the reasoning for the ask ? 
the client may lazy connect when it is needed and the channel backing the client may be closed at some point

**Comment by luomengY** [comment]
nt has been connected, and can only judge whether it is connected by running through or throwing an exception.

**Comment by luomengY** [comment]
Because after the client adds endpoints, it cannot judge whether the clent has been connected, and can only judge whether it is connected by running through or throwing an exception.

**Comment by lburgazzoli** [comment]
The client does not immediately connect after you add endpoint, but the connection is lazy and happen when you are invoking specific methods. 

How would you use such method ?
Would you be able to contribute a PR ?

**Comment by luomengY** [comment]
The following is the connection method I use. If the client is disconnected due to an exception or the server is abnormal in the middle, after the server returns to normal, the client needs to re-pass Client client = Client.builder().endpoints(ip).build() To establish a connection, whether the original client can still take effect.
Client client = Client.builder().endpoints(ipArr).build();
this.etcdLock = client.getLockClient();
 this.lease = client.getLeaseClient();
this.watch = client.getWatchClient();

**Comment by luomengY** [comment]
The following is the connection method I use. If the client is disconnected due to an exception or the server is abnormal in the middle, after the server returns to normal, does the client need to re-pass Client client = Client.builder().endpoints(ip).build( ) to establish a connection, and whether the original client can still take effect.
Client client = Client.builder().endpoints(ipArr).build();
 this.etcdLock = client.getLockClient();
 this.lease = client.getLeaseClient();
 this.watch = client.getWatchClient();

**Comment by lburgazzoli** [comment]
The client reconnects automatically

**Comment by luomengY** [comment]
ok, how to let the client open the connection after executing client.close()?

**Comment by lburgazzoli** [comment]
> ok, how to let the client open the connection after executing client.close()?

i.e. client.getLeaseClient() should create a brand new client

**Comment by luomengY** [comment]
reate Client once client = Client.builder().endpoints(ip).build(), it will reconnect even with exception.

**Comment by luomengY** [comment]
ok, I only need to create Client once client = Client.builder().endpoints(ip).build(), it will reconnect even with exception.
