### ISSUE TITLE
Hope to update CHANGELOG

### ISSUE THREAD

**Issue by linghengqian** [etcd-io/jetcd#1091]
**Is your feature request related to a problem? Please describe.**

- No.

**Describe the solution you'd like**

- https://github.com/etcd-io/jetcd/blob/jetcd-0.7.3/CHANGELOG.md does not have the latest version of the changelog, which brings some confusion to users. Hope some friends can update the file.

**Describe alternatives you've considered**

- I'm not quite sure if there is a changelog recorded somewhere else.

**Additional context**

- Null.

**Comment by lburgazzoli** [comment]
@linghengqian would you like to help ? I have very limited time

**Comment by linghengqian** [comment]
@lburgazzoli I don't need any help, I just don't understand the changes that happened after 0.0.3. If CHANGELOG doesn't have time to maintain for the committer, is it possible to open Milestones for PRs and issues of later versions to facilitate users Understand what changed behind the version change? I'm just assuming there are some API differences between 0.5.0, 0.6.0 and 0.7.0.

**Comment by lburgazzoli** [comment]
What I mean is that it is probably needed to set up some github actions or do something in the release plugin to keep the changelog up-to-date so I'm looking for volunteers

**Comment by linghengqian** [comment]
- I'm assuming you're talking about plugins like `se.bjurr.gitchangelog:git-changelog-maven-plugin` instead of `org.apache.maven.plugins:maven-changelog-plugin`?

**Comment by lburgazzoli** [comment]
@linghengqian note that we are using gradle insted of maven but yeah, the idea is to either have a plugin or a github action to collect and automatically create release notes and changelogs

**Comment by cotej** [comment]
Having some up to date release notes/changelog would be very helpful. 👍 

For example I just upgraded from jetcd `0.6.1` -> `0.7.3` and ran into a small issue since my application runs in a containerized environment where it could not write to the `/tmp/vertx-cache-<uuid>` directories by default.  Not a particularly tough problem to solve, but it would have been less of a surprise with some release notes detailing the change to Vert.x along with the new storage requirement.

**Comment by linghengqian** [comment]
- I do want to work on this issue, but my experience with gradle is terrible, I almost started using gradle when start.spring.io switched the default package manager a while ago. 🤔  I'm guessing I'll have a PR for this someday in the future.

**Comment by linghengqian** [comment]
- The main reason I'm not pushing this issue is that I'm pushing https://github.com/oracle/graalvm-reachability-metadata/pull/170, which is jetcd-core's nativeTest under GraalVM Native Image.
