### ISSUE TITLE
When the etcd is killed, the exception of get() cannot be caught

### ISSUE THREAD

**Issue by epiao55** [etcd-io/jetcd#1096]
**Versions**
- etcd: _etcd-v3.3.10-windows-amd64
- jetcd: jetcd-core 0.7.0
- java: 1.8

**Describe the bug**
I want to feel whether the data of etcd can be pulled normally, so I am ready to capture the exception of get(), but the test finds that the etcd  is killed directly or an incorrect endpoint is used, and then getFuture.get() , but no exception will be thrown. And the subsequent code of exception capture will not be executed. Is there a way to identify whether the application is connected to the etcd normally. thanks

**To Reproduce**
Steps or reproducer to reproduce the behavior. 
this is demo:
```java
public static void main(String[] args)  {
        ClientBuilder builder=Client.builder();
        Client client = builder.endpoints("http://127.0.0.1:2379")
                .build();
        KV kvClient = client.getKVClient();
        ByteSequence key = ByteSequence.from("test_key".getBytes());
        ByteSequence value = ByteSequence.from("test_value".getBytes());

        CompletableFuture<GetResponse> getFuture = kvClient.get(key);
        try {
            GetResponse response = getFuture.get();

        }catch (Exception e){
            // kill etcd but no exception be thrown
            e.printStackTrace();
        }
        System.out.println("ok");  //not be executed
    }
```
This code does not have any exceptions and subsequent code execution when the etcd is killed

**Expected behavior**
I hope there is an exception thrown or another method to identify that the connection between the application and the etcd has been disconnected.
At least I want to see the word 'ok' be Printed

**Additional context**
Even if I specify an incorrect endpoint at the beginning, there will be no exception, which is unreasonable
```java
//wrong endpoint
Client client = builder.endpoints("http://127.0.0.1:237")
                .build();
```

Hope to get help，thanks a lot!

**Comment by lburgazzoli** [comment]
@epiao55 sorry I missed this issue, by default the client tries to reconnect automatically, there are options to configure the retry logic in the Client.Builder
