### ISSUE TITLE
Whether jetcd supports that after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endponts?

### ISSUE THREAD

**Issue by luomengY** [etcd-io/jetcd#1099]
Whether jetcd supports that after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endponts?
(https://github.com/etcd-io/jetcd/issues/464#issuecomment-1298905607)
https://github.com/etcd-io/jetcd/issues/464#issuecomment-476443244
is this way support after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endpoints? has jetcd good eay now?

**Comment by luomengY** [comment]
final String[] etcdEndpoints = {"srv://_etcd-client._tcp.example.com"};
Client.builder().endpoints(etcdEndpoints)
  .uriResolverLoader(() -> {
    final Collection<URIResolver> resolvers = new ArrayList<>();
    resolvers.add(new DnsSrvUriResolver());
    return resolvers;
  })
  .loadBalancerFactory(Objects.requireNonNull(LoadBalancerRegistry.getDefaultRegistry()
  .getProvider("round_robin")))
  .build()
is this way support after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endpoints?

**Comment by luomengY** [comment]
Excuse me, has this function been implemented? Can this function be realized through dns dynamic discovery?

**Comment by lburgazzoli** [comment]
Yes, you can use the `dns+srv` protocol or any protocol provided by grpc-java
The list of provided shipped with jetcd is available here: https://github.com/etcd-io/jetcd/tree/61ad70b0fc3ff3b5455d2ce8075544680270d1e5/jetcd-core/src/main/java/io/etcd/jetcd/resolver
