### ISSUE TITLE
Whether jetcd supports that after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endponts?

### ISSUE THREAD

**Issue by luomengY** [etcd-io/jetcd#1100]
Whether jetcd supports that after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endponts?
(https://github.com/etcd-io/jetcd/issues/464#issuecomment-1298905607)
https://github.com/etcd-io/jetcd/issues/464#issuecomment-476443244
is this way support after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endpoints? has jetcd good eay now?

final String[] etcdEndpoints = {"srv://_etcd-client._tcp.example.com"};
Client.builder().endpoints(etcdEndpoints)
.uriResolverLoader(() -> {
final Collection resolvers = new ArrayList<>();
resolvers.add(new DnsSrvUriResolver());
return resolvers;
})
.loadBalancerFactory(Objects.requireNonNull(LoadBalancerRegistry.getDefaultRegistry()
.getProvider("round_robin")))
.build()
is this way support after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endpoints?

**Comment by lburgazzoli** [comment]
duplicates #1099
