### ISSUE TITLE
For example, at the beginning, there are only node1, node2, and node3 in the etcd cluster. How do I create client connection endpoints that only write node1? Without closing and re establishing, add node4 to the cluster, and remove node1. At this time, whether the original client can perceive the changes of the cluster node and whether the client can still use it normally. Can we only dynamically discover the etcd connections added to the client through dns svr? Can HttpNameResolver, HttpsNameResolver, and IPNameResolver also implement this function? Can you help me write a connection demo that supports this dynamic auto sensing client? I can't find the relevant test cases in the source code.

### ISSUE THREAD

**Issue by luomengY** [etcd-io/jetcd#1102]
For example, at the beginning, there are only node1, node2, and node3 in the etcd cluster. How do I create client connection endpoints that only write node1? Without closing and re establishing, add node4 to the cluster, and remove node1. At this time, whether the original client can perceive the changes of the cluster node and whether the client can still use it normally.
Can we only dynamically discover the etcd connections added to the client through dns svr? Can HttpNameResolver, HttpsNameResolver, and IPNameResolver also implement this function? Can you help me write a connection demo that supports this dynamic auto sensing client? I can't find the relevant test cases in the source code.

**Comment by lburgazzoli** [comment]
use discussion for this and pick a better  title. 

I suggest you look at the groc-java to implement your custom resolver. jetcd just delegate to it
