### ISSUE TITLE
Cluster Auth Enabled, fails to resume watch on cluster restart.

### ISSUE THREAD

**Issue by vivekpatani** [etcd-io/jetcd#1104]
**Versions**
- etcd: 3.5
- jetcd: main
- java: openjdk 11.0.17 2022-10-18 LTS

**Describe the bug**
When cluster authentication is enabled, and the cluster restarts, the watch fails to re-establish connection.

**To Reproduce**
1. Create a cluster
2. Create a client with auth and enable auth (can follow this test from jetcd code itself: https://github.com/etcd-io/jetcd/blob/70c9f45d34729c294904720097479b6705ddfa18/jetcd-core/src/test/java/io/etcd/jetcd/impl/AuthClientTest.java#L108) - follow until line 108
3. Establish a watch and then retry connection, continue the code from this test, and should be able to reproduce issue.

**Expected behavior**
Expectation is to have cluster auth enabled, and on cluster restarts, client should seamlessly reconnect.

**Comment by lburgazzoli** [comment]
@vivekpatani can you contribute an integration test ?

**Comment by lburgazzoli** [comment]
@vivekpatani this should have been fixed in the latest code, can you check out the latest code and try it ?

**Comment by vivekpatani** [comment]
@lburgazzoli sure, let me re run that test. Sorry didn't have the bandwidth to muster a fix.

**Comment by lburgazzoli** [comment]
@vivekpatani any update ?

**Comment by lburgazzoli** [comment]
@vivekpatani any update ?

**Comment by vivekpatani** [comment]
https://github.com/etcd-io/jetcd/pull/1103 - I think this PR has the fix, will close, sorry for the delay.
