### ISSUE TITLE
Can jetcd be ready for Jakarta EE 10?

### ISSUE THREAD

**Issue by speter555** [etcd-io/jetcd#1105]
**Is your feature request related to a problem? Please describe.**
I would like to use jetcd in my projekt, but I would like to use jakata ee 10, but they get stuck. (the probelem is jakarta ee annotation api)

**Describe the solution you'd like**
I think, If javax.annotation-api will change jakarta.annotation-api in jetcd-grpc and update vertx-grpc version which does not use javax.annotation-api, it could done the problem.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by lburgazzoli** [comment]
This pr should solve the problem: https://github.com/etcd-io/jetcd/pull/1106
