### ISSUE TITLE
Election throws exception: etcdserver: invalid auth token

### ISSUE THREAD

**Issue by hhhyang** [etcd-io/jetcd#1118]
**Versions**
- etcd: v3.5.0
- jetcd: 0.7.3
- java: 1.8

**Describe the bug**
after leader failed, follower node turns to be leader.  method get() of CompletableFuture<CampaignResponse> is invoked, but throw ExecutionException exception, the caused exception is: io.etcd.jetcd.common.exception.EtcdException: etcdserver: invalid auth token. and execute Election.leader() also throw "invalid auth token" exception

**To Reproduce**
the election code snippet is as follow:
```
// create client with user/password, create lease and eleciton instance
Client etcdClient = Client.builder().endpoints(StringSpilter.splitToArrayAndTrim(endpoints, ","))
                .user(user).password(passwd).build();
Election election = etcdClient.getElectionClient();

// to campain leader
CompletableFuture<CampaignResponse> campaign = election.campaign(electionKey, leaseId, proposal);
try {
    LeaderKey key = campaign.get().getLeader();
} catch () {
    CompletableFuture<LeaderResponse> leaderResponse = election.leader(electionKey);
}
```

1. start two nodes, node1 is leader , node2 is not leader
2. wait for perhaps 5 minutes 
3. stop node1
4. node2 throws "invalid auth token" exception

**Expected behavior**
after node1 is stoped, node2 is elected as leader, and no exception

**Additional context**

**Comment by lburgazzoli** [comment]
can you create a test with a reproducer ?
