### ISSUE TITLE
The keepAliveOnce delay increases after the jetcd version is upgraded to 0.7.3

### ISSUE THREAD

**Issue by Wackerle** [etcd-io/jetcd#1119]
**Versions**
- etcd: 3.4.10
- jetcd: 0.5.3 -> 0.7.3
- java: 1.8

**Describe the bug**
After we upgraded the jetcd from 0.5.3 to 0.7.3, we noticed that the latency increased. The cause is that the keepAliveOnce delay increased.

**To Reproduce**
The code is as follows:
```java
        long leaseId = client.getLeaseClient().grant(60).get().getID();
        long sum = 0L;
        for (int i = 0; i < 10; i++) {
            long startTime = System.currentTimeMillis();
            LeaseKeepAliveResponse response = client.getLeaseClient().keepAliveOnce(leaseId).get();
            long endTime = System.currentTimeMillis();
            sum += (endTime - startTime);
        }
        System.out.println("Average time required: " + sum / 10);
```

Before the upgrade, we get the result:
![image](https://user-images.githubusercontent.com/38138157/208006316-caba8e92-3ddc-4f57-be81-dae01c25d593.png)
After the upgrade, we get the result:
![image](https://user-images.githubusercontent.com/38138157/208006988-186d8cb2-1b6f-43ce-981c-0bf0307757fb.png)

**Expected behavior**
The delay does not change much after the upgrade.

**Additional context**
I found out that the implementation of keepAliveOnce was modified in the commit #1024.
The new implementation reuses the keepAlive method. 
![image](https://user-images.githubusercontent.com/38138157/208010047-fd83cde6-49cd-4c58-b6f5-1f154c4831a8.png)
And the keepAlive implementation is in a thread pool, so there is a delay.
![image](https://user-images.githubusercontent.com/38138157/208009153-660d17dc-4ed1-48a7-8f7f-20f077f8096a.png)

What is the reason for this modification? 
Am I using it wrong? And what can I do to avoid this problem?

**Comment by lburgazzoli** [comment]
It is likely a bug, do you have any time to investigate and contribute a PR ?

NOTE: please do not include screenshots of the code as it makes things more complicated.  Better to add a link to the relevant code instead.

**Comment by lburgazzoli** [comment]
@Wackerle do you have any time to work on a PR ?

**Comment by Wackerle** [comment]
> @Wackerle do you have any time to work on a PR ?

Sorry, I'm afraid I don't have time to invest. We have used other means to avoid this problem.
