### ISSUE TITLE
Is there any hook or intercept mechanism provided to  rewrite KV client's request or response?

### ISSUE THREAD

**Issue by hbyscx001** [etcd-io/jetcd#1120]
**Versions**
- etcd: _add the etcd version here_
- jetcd: _add the jetcd version here_
- java: _add the java version here_

**Describe the bug**

**To Reproduce**
Steps or reproducer to reproduce the behavior. 
This section *must* be provided, if not, the issue may not get attention.

**Expected behavior**

**Additional context**

**Comment by lburgazzoli** [comment]
Please try to be more clear when you report an issue.
Some examples of what you are looking for could be useful.
