### ISSUE TITLE
for ClientConnectionManager's executorService

### ISSUE THREAD

**Issue by xionlylovesisi** [etcd-io/jetcd#1128]
i just have a problem about ClientConnectionManager.executorService, by default, the threads is unlimit, i think it maybe cause OOM, isn't it?
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/11381735/226571990-7a139989-1810-41c0-b24a-00390c021d19.png">

**Comment by lburgazzoli** [comment]
can you work on a pr to make it configurable ?
