### ISSUE TITLE
jetcd cause cpu usage 100% when etcd cluster is not reachable

### ISSUE THREAD

**Issue by medusar** [etcd-io/jetcd#1134]
**Versions**
- etcd: 3.5.9
- jetcd: 0.7.5
- java: jdk17

**Describe the bug**
Ectd cluster: 3nodes without gateway or proxy
When i use `keepAlive` to prolong the lease of a key,  after 2 followers are crashed, the jectd client is not able to detect the failure, and it will keep reconnecting and eventually the cpu will go up to 100%.

**To Reproduce**
1. use the code to put a key with lease, and use keepAlive to keep the lease effective.
``` java 
private static void leaseAndRegister(Client client, Lease leaseClient) {
//        leaseClient.grant(5, 1, TimeUnit.SECONDS)

        leaseClient.grant(5).thenAccept(leaseGrantResponse -> {
            long leaseId = leaseGrantResponse.getID();
            long ttl = leaseGrantResponse.getTTL();

            logger.info("leaseGrantResponse={}", leaseGrantResponse);

            //put key value
            KV kvClient = client.getKVClient();
            kvClient.put(ByteSequence.from("ectc-demo/provider/instance", Charset.defaultCharset()),
                    ByteSequence.from("value:" + System.currentTimeMillis(), Charset.defaultCharset()),
                    PutOption.newBuilder().withLeaseId(leaseId).build()
            ).thenAccept(putResponse -> {

                leaseClient.keepAlive(leaseId, new StreamObserver<LeaseKeepAliveResponse>() {
                    @Override
                    public void onNext(LeaseKeepAliveResponse leaseKeepAliveResponse) {
                        logger.info("onNext received, leaseKeepAliveResponse={}", leaseKeepAliveResponse);
                    }

                    @Override
                    public void onError(Throwable throwable) {
                        System.out.println("onError.....");
                        throwable.printStackTrace();
                        
                        logger.error("onError received", throwable);

                        leaseAndRegister(client, leaseClient);
                    }

                    @Override
                    public void onCompleted() {
                        logger.info("onCompleted received");
                        leaseAndRegister(client, leaseClient);
                    }
                });
            });
        });
    }
```
2. kill 2 followers

**Expected behavior**
Raise an error instead of keep reconnecting 

**Additional context**

**Comment by lburgazzoli** [comment]
As far as I recall, there should be an option when you create a client using the builder to set retry delay and its max value then it should fail so it should not lead to a 100% usage.

Do you have any time to digg into the issue something more ?

**Comment by medusar** [comment]
@lburgazzoli Thank you for your advice, i will look into this and see if things will work.

**Comment by medusar** [comment]
@lburgazzoli Hi, i have tried this, but it does not work. Besides, when i kill two follower and then restart them again, the etcd cluster recovered, but the client will not be able to recover because no callback is invoked, so we don't know if the connection is recovered. Do you have any other suggestions?

**Comment by lburgazzoli** [comment]
need to digg into it, can you create a reproducer as. junit test ? that would help me a lot

**Comment by medusar** [comment]
@lburgazzoli Sorry for the delay, when 2 followers are killed, `onCompleted` will be called back, so i can retry. I made a mistake before so that the `onCompleted` callback is not triggered.  I will close this issue.
