### ISSUE TITLE
Connection timeout problem

### ISSUE THREAD

**Issue by euan-io** [etcd-io/jetcd#1161]
**Versions**
- etcd: 3.4.18
- jetcd: 0.7.5
- java: 1.8

**Describe the bug**

When I started the project, I used the singleton pattern to make the client a singleton object. While building the object using ClientBuilder, I set the connectTimeout and keepaliveTimeout to 10 seconds. However, when my etcd service was shut down, the project kept trying to reconnect, which made it tough for me to figure out that the issue was due to the etcd service not being started. So, I am not sure whether the connection timeout needs to be correctly configured or if the timeout duration did not work due to some internal logic issues.

**Comment by lburgazzoli** [comment]
@euan-io can you please provide a PR with an integration test for this issue ? that would help me a lot fixing/understanding the issue.

**Comment by liangyuanpeng** [comment]
@euan-io 
Do you have any suggesstion for this case? like add more log or just failed when can not connect to the etcd.

**Comment by lburgazzoli** [comment]
The `CompletableFuture` that is returned by most of the calls should let you detect errors like handling a failed completion, if not, the it is a bug. 

However `connectTimeout`and `keepaliveTimeout`are not meant to configure how disconnection is handled, for that there are a number of `retry*`method to configure the retry behavior.

**Comment by lburgazzoli** [comment]
@euan-io I think the root cause is in the grpc behavior so by default it waits for the connection to be ready which may lead to this kind of behavior. A solution is to set `waitForReady` to `false`, here an example:


```java
ClientBuilder builder = Client.builder()
    .endpoints("http://127.0.0.1:9999")
    .connectTimeout(Duration.ofMillis(250))
    .waitForReady(false)
    .retryMaxAttempts(5)
    .retryDelay(250);

AtomicReference<Throwable> error = new AtomicReference<>();

try (Client client = builder.build()) {
    CompletableFuture<?> unused = client.getKVClient().put(bytesOf("sample_key"), bytesOf("sample_value")).whenComplete(
            (r, t) -> {
                if (t != null) {
                    error.set(t);
                }
            }
    );

    await().untilAsserted(() -> {
        assertThat(error.get()).isNotNull();
        assertThat(error.get()).hasCauseInstanceOf(StatusRuntimeException.class);
        assertThat(error.get().getCause()).hasMessage("UNAVAILABLE: io exception");
    });
}
```

Let me know if this solves your problem.

**Comment by lburgazzoli** [comment]
@euan-io any feedback ?

**Comment by demonti** [comment]
Hi,

I am trying out jetcd and experiencing similar effects. If I start my application with the etcd server not running (i.e. no process listening on the configured address/port), the application waits forever for a response, even though I have configured connect, retry and keepalive timeouts, tried "waitForReady" both ways. Maybe this is a regression problem of the closed issue #970.

I am using Ubuntu 23.04 with x64, Java 20 (OpenJDK build 20+36-2344), version 0.7.6 of the jetcd library.

It would be nice if someone could investigate this further.

**Comment by lburgazzoli** [comment]
@demonti we have [this test](https://github.com/etcd-io/jetcd/blob/main/jetcd-core/src/test/java/io/etcd/jetcd/impl/RetryTest.java) in place that seems similar to the scenario you described, can you confirm ?

**Comment by demonti** [comment]
Hi Luca,

I ran the test and succeeded. I checked it against my test and discovered that first of all, I still had the "waitForReady (true)" in my code and after removal, it took a minute for the exception to come due to my retry settings – I was not aware that the retry mechanism applies to the connect as well. Thanks for pointing me into the right direction!

**Comment by lburgazzoli** [comment]
no updates from reporter
