### ISSUE TITLE
provide a timeout option for other operations besides grant

### ISSUE THREAD

**Issue by medusar** [etcd-io/jetcd#1184]
**Is your feature request related to a problem? Please describe.**
For now, we can pass a timeout parameter for method `lease.grant`,  but for other operations like put or get, no timeout parameter s are available.

For `lease.grant`:
```java 
CompletableFuture<LeaseGrantResponse> grant(long ttl, long timeout, TimeUnit unit);
```

After looking briefly into the code, it seems that there is no difference between `grant` and other operations, so may be for other operations, it will be much more convenient if methods like `someOperation(some parameter, long timeout, TimeUnit timeUnit)` are provied.

**Comment by lburgazzoli** [comment]
what do you want to achieve ? i.e. you can set a timeout with any CompletableFuture.get(timeout, unit)

**Comment by medusar** [comment]
it can be achieved with CompletableFuture.get(timeout, unit), just of out curiosity, why does `grant` method have a timeout parameter but other operations haven't ?

**Comment by lburgazzoli** [comment]
I don't know to be honest, it is something from 2019 so yeah, the same behavior can be added to any method but maybe it is better to add it as as part of the client configuration to avoid bloating the interface ?

**Comment by medusar** [comment]
ok, no problem.

**Comment by lburgazzoli** [comment]
@medusar do you have any time to make a PR with that behavior ?

**Comment by medusar** [comment]
> @medusar do you have any time to make a PR with that behavior ?

sure, i am glad to do that, sorry for the late response.
