### ISSUE TITLE
When I use the watch function, value of the response include some  garbled code,is this normal ?How can I fix the  garbled code? 

### ISSUE THREAD

**Issue by LanMingjin** [etcd-io/jetcd#1185]
**Versions**
- etcd: 3.5
- jetcd: 0.5.11
- java: jdk11

**Describe the bug**
the value of the response include some garbled code as following：
kv {
  key: "/registry/pods/ns-test/pod-create-ns-test"
  create_revision: 3859896
  mod_revision: 3974879
  version: 7
  value: "k8s\000\n\t\n\002v1\022\003Pod\022\312\022\n\250\t\n\022pod-create-ns-test\022\000\032\ans-test\"\000*$2b1abd8b-3672-4989-8cf8-fe54cd1763232\0008\000B\b\b\330\257\223\245\006\020\000J\b\b\316\334\232\245\006\020\000P\036z\000\212\001\377\003\n\026Kubernetes Java Client\022\006Update\032\002v1\"\b\b\330\257\223\245\006\020\0002\bFieldsV1:\302\003\n\277\003{\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"pod-create-ns-test1\\\"}\":{\".\":{},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:name\":{},\"f:resources\":{\".\":{},\"f:limits\":{\".\":{},\"f:cpu\":{},\"f:memory\":{}},\"f:requests\":{\".\":{},\"f:cpu\":{},\"f:memory\":{}}},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{}}},\"f:dnsPolicy\":{},\"f:enableServiceLinks\":{},\"f:restartPolicy\":{},\"f:schedulerName\":{},\"f:securityContext\":{},\"f:terminationGracePeriodSeconds\":{}}}B\000\212\001\276\004\n\akubelet\022\006Update\032\002v1\"\b\b\227\357\230\245\006\020\0002\bFieldsV1:\212\004\n\207\004{\"f:status\":{\"f:conditions\":{\"k:{\\\"type\\\":\\\"ContainersReady\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Initialized\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Ready\\\"}\":{\".\":{},\"f:lastProbeTime\":{},\"f:lastTransitionTime\":{},\"f:status\":{},\"f:type\":{}}},\"f:containerStatuses\":{},\"f:hostIP\":{},\"f:phase\":{},\"f:podIP\":{},\"f:podIPs\":{\".\":{},\"k:{\\\"ip\\\":\\\"10.244.1.124\\\"}\":{\".\":{},\"f:ip\":{}}},\"f:startTime\":{}}}B\006status\022\334\004\n\204\001\n\025kube-api-access-59gc5\022k\322\001h\n\016\"\f\n\000\020\227\034\032\005token\n(\032&\n\022\n\020kube-root-ca.crt\022\020\n\006ca.crt\022\006ca.crt\n)\022\'\n%\n\tnamespace\022\030\n\002v1\022\022metadata.namespace\020\244\003\022\351\001\n\023pod-create-ns-test1\022\fnginx:latest*\000B@\n\r\n\003cpu\022\006\n\004500m\n\017\n\006memory\022\005\n\0031Gi\022\r\n\003cpu\022\006\n\004500m\022\017\n\006memory\022\005\n\0031GiJL\n\025kube-api-access-59gc5\020\001\032-/var/run/secrets/kubernetes.io/serviceaccount\"\0002\000j\024/dev/termination-logr\fIfNotPresent\200\001\000\210\001\000\220\001\000\242\001\004File\032\006Always \0362\fClusterFirstB\adefaultJ\adefaultR\aserver3X\000`\000h\000r\000\202\001\000\212\001\000\232\001\021default-scheduler\262\0016\n\034node.kubernetes.io/not-ready\022\006Exists\032\000\"\tNoExecute(\254\002\262\0018\n\036node.kubernetes.io/unreachable\022\006Exists\032\000\"\tNoExecute(\254\002\302\001\000\310\001\000\360\001\001\372\001\024PreemptLowerPriority\032\275\004\n\aRunning\022#\n\vInitialized\022\004True\032\000\"\b\b\330\257\223\245\006\020\000*\0002\000\022\035\n\005Ready\022\004True\032\000\"\b\b\227\357\230\245\006\020\000*\0002\000\022\'\n\017ContainersReady\022\004True\032\000\"\b\b\227\357\230\245\006\020\000*\0002\000\022$\n\fPodScheduled\022\004True\032\000\"\b\b\330\257\223\245\006\020\000*\0002\000\032\000\"\000*\016192.168.84.1332\f10.244.1.124:\b\b\330\257\223\245\006\020\000B\324\002\n\023pod-create-ns-test1\022\f\022\n\n\b\b\226\357\230\245\006\020\000\032o\032m\b\377\001\020\000\032\005Error\"\000*\b\b\331\257\223\245\006\020\0002\b\b\325\356\230\245\006\020\000:Idocker://4c1efb761632730f7be05c50747b232722e02e4d275fd7b36bf920283a9e15ec \001(\0012\fnginx:latest:_docker-pullable://nginx@sha256:593dac25b7733ffb7afe1a72649a43e574778bf025ad60514ef40f6b5d606247BIdocker://9456bc9c9494793d793412b92e631986c27f8ebf0a5a0884566f3da939f332d3H\001J\nGuaranteedZ\000b\016\n\f10.244.1.124\032\000\"\000"
}

**To Reproduce**
use the watch function to watch the key change

**Expected behavior**
the value of the response shouldn't include these garbled code .

**Additional context**

**Comment by lburgazzoli** [comment]
Can you provide a reproducer ?

**Comment by liangyuanpeng** [comment]
Seems like you are looking the data of kubernetes. 

You can check the data with etcdctl to see what happen.

**Comment by liangyuanpeng** [comment]
I think this issue can be close now.

**Comment by lburgazzoli** [comment]
no feedback since a  month

**Comment by LanMingjin** [comment]
> Can you provide a reproducer ? what jetcd gets is just a set of bytes so be sure to use the right charset
The key and value are set by kubernetes with protobuf protocol, when the key changed and jetcd get the response, the value still encode with protobuf protocol, maybe we need to decode with protobuf protocol. However, I tried many ways to decode  it with protobuf protocol in java language, it's still not work.

**Comment by lburgazzoli** [comment]
1. provide a reproducer as requested
2. try with etcdctl

**Comment by LanMingjin** [comment]
> 1. provide a reproducer as requested
> 2. try with etcdctl

1.This is output by jetcd watched, printed in UTF-8 charset:
 {
key: "/registry/pods/ns-test/pod-create-ns-test"
create_revision: 3859896
mod_revision: 3974879
version: 7
value: "k8s\000\n\t\n\002v1\022\003Pod\022\312\022\n\250\t\n\022pod-create-ns-test\022\000\032\ans-test"\000*$2b1abd8b-3672-4989-8cf8-fe54cd1763232\0008\000B\b\b\330\257\223\245\006\020\000J\b\b\316\334\232\245\006\020\000P\036z\000\212\001\377\003\n\026Kubernetes Java Client\022\006Update\032\002v1"\b\b\330\257\223\245\006\020\0002\bFieldsV1:\302\003\n\277\003{"f:spec":{"f:containers":{"k:{\"name\":\"pod-create-ns-test1\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}B\000\212\001\276\004\n\akubelet\022\006Update\032\002v1"\b\b\227\357\230\245\006\020\0002\bFieldsV1:\212\004\n\207\004{"f:status":{"f:conditions":{"k:{\"type\":\"ContainersReady\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Initialized\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Ready\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}}},"f:containerStatuses":{},"f:hostIP":{},"f:phase":{},"f:podIP":{},"f:podIPs":{".":{},"k:{\"ip\":\"10.244.1.124\"}":{".":{},"f:ip":{}}},"f:startTime":{}}}B\006status\022\334\004\n\204\001\n\025kube-api-access-59gc5\022k\322\001h\n\016"\f\n\000\020\227\034\032\005token\n(\032&\n\022\n\020kube-root-ca.crt\022\020\n\006ca.crt\022\006ca.crt\n)\022'\n%\n\tnamespace\022\030\n\002v1\022\022metadata.namespace\020\244\003\022\351\001\n\023pod-create-ns-test1\022\fnginx:latest*\000B@\n\r\n\003cpu\022\006\n\004500m\n\017\n\006memory\022\005\n\0031Gi\022\r\n\003cpu\022\006\n\004500m\022\017\n\006memory\022\005\n\0031GiJL\n\025kube-api-access-59gc5\020\001\032-/var/run/secrets/kubernetes.io/serviceaccount"\0002\000j\024/dev/termination-logr\fIfNotPresent\200\001\000\210\001\000\220\001\000\242\001\004File\032\006Always \0362\fClusterFirstB\adefaultJ\adefaultR\aserver3X\000`\000h\000r\000\202\001\000\212\001\000\232\001\021default-scheduler\262\0016\n\034node.kubernetes.io/not-ready\022\006Exists\032\000"\tNoExecute(\254\002\262\0018\n\036node.kubernetes.io/unreachable\022\006Exists\032\000"\tNoExecute(\254\002\302\001\000\310\001\000\360\001\001\372\001\024PreemptLowerPriority\032\275\004\n\aRunning\022#\n\vInitialized\022\004True\032\000"\b\b\330\257\223\245\006\020\000*\0002\000\022\035\n\005Ready\022\004True\032\000"\b\b\227\357\230\245\006\020\000*\0002\000\022'\n\017ContainersReady\022\004True\032\000"\b\b\227\357\230\245\006\020\000*\0002\000\022$\n\fPodScheduled\022\004True\032\000"\b\b\330\257\223\245\006\020\000*\0002\000\032\000"\000*\016192.168.84.1332\f10.244.1.124:\b\b\330\257\223\245\006\020\000B\324\002\n\023pod-create-ns-test1\022\f\022\n\n\b\b\226\357\230\245\006\020\000\032o\032m\b\377\001\020\000\032\005Error"\000*\b\b\331\257\223\245\006\020\0002\b\b\325\356\230\245\006\020\000:Idocker://4c1efb761632730f7be05c50747b232722e02e4d275fd7b36bf920283a9e15ec \001(\0012\fnginx:latest:_docker-pullable://nginx@sha256:593dac25b7733ffb7afe1a72649a43e574778bf025ad60514ef40f6b5d606247BIdocker://9456bc9c9494793d793412b92e631986c27f8ebf0a5a0884566f3da939f332d3H\001J\nGuaranteedZ\000b\016\n\f10.244.1.124\032\000"\000"
}

2.This response is get by etcdctl without decode:
etcdctl get /registry/pods/ns-test/pod-create-ns-test112232
/registry/pods/ns-test/pod-create-ns-test112232
k8s

v1Pod▒

]
pod-create-ns-test112232ns-test"*$cff06135-1bf1-11ee-9da1-00505680b7592▒К▒z▒
1
default-token-rq5m62
default-token-rq5m6▒▒
nginx1:latest*B@st1122321

cpu
500m

memory
1Gi
cpu
500m
memory
1GiJH
default-token-rq5m6-/var/run/secrets/kubernetes.io/serviceaccount"j/dev/termination-logr
IfNotPresent▒▒▒▒FileAlways 2
ClusterFirstBdefaultJdefaultR
10.218.11.66X`hr▒▒▒default-scheduler▒6
node.kubernetes.io/not-readyExists"     NoExecute(▒▒8
node.kubernetes.io/unreachableExists"   NoExecute(▒▒▒▒▒
Running#

InitializedTru▒֚▒*2k
ReadyFals▒▒֮*ContainersNotReady2;containers with unready status: [pod-create-ns-test1122321]u
ContainersReadyFals▒▒֮*ContainersNotReady2;containers with unready status: [pod-create-ns-test1122321]$
PodScheduledTru▒К▒*2"*
10.218.11.662
             172.30.60.▒֚▒B▒
pod-create-ns-test1122321<
:
ImagePullBackOff&Back-off pulling image "nginx1:latest"rp       Completed▒▒▒֮:Idocker://8b81fbce210622ea1bccb8a2a3c2eb6af8f8271d874faa1ad39cb46b42bbd2b5 (2
nginx:latest:_docker-pullable://nginx@sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd53c9b31BIdocker://8b81fbce210622ea1bccb8a2a3c2eb6af8f8271d874faa1ad39cb46b42bbd2b5J
GuaranteedZ"

2.This response is get by etcdctl with decode:
etcdctl get /registry/pods/ns-test/pod-create-ns-test112232 | auger decode
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-06T11:39:48Z"
  name: pod-create-ns-test112232
  namespace: ns-test
  uid: cff06135-1bf1-11ee-9da1-00505680b759
spec:
  containers:
  - image: nginx1:latest
    imagePullPolicy: IfNotPresent
    name: pod-create-ns-test1122321
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rq5m6
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: 10.218.11.66
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-rq5m6
    secret:
      defaultMode: 420
      secretName: default-token-rq5m6
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-06T11:52:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-21T06:03:19Z"
    message: 'containers with unready status: [pod-create-ns-test1122321]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-21T06:03:19Z"
    message: 'containers with unready status: [pod-create-ns-test1122321]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-06T11:39:48Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://8b81fbce210622ea1bccb8a2a3c2eb6af8f8271d874faa1ad39cb46b42bbd2b5
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd53c9b31
    lastState:
      terminated:
        containerID: docker://8b81fbce210622ea1bccb8a2a3c2eb6af8f8271d874faa1ad39cb46b42bbd2b5
        exitCode: 0
        finishedAt: "2024-02-21T06:03:00Z"
        reason: Completed
        startedAt: "2024-02-21T05:43:43Z"
    name: pod-create-ns-test1122321
    ready: false
    restartCount: 5
    state:
      waiting:
        message: Back-off pulling image "nginx1:latest"
        reason: ImagePullBackOff
  hostIP: 10.218.11.66
  phase: Running
  podIP: 172.30.60.6
  qosClass: Guaranteed
  startTime: "2023-07-06T11:52:35Z"

Above resposne in json format:
etcdctl get /registry/pods/ns-test/pod-create-ns-test112232 --print-value-only | auger decode -o json
{"kind":"Pod","apiVersion":"v1","metadata":{"name":"pod-create-ns-test112232","namespace":"ns-test","uid":"cff06135-1bf1-11ee-9da1-00505680b759","creationTimestamp":"2023-07-06T11:39:48Z"},"spec":{"volumes":[{"name":"default-token-rq5m6","secret":{"secretName":"default-token-rq5m6","defaultMode":420}}],"containers":[{"name":"pod-create-ns-test1122321","image":"nginx1:latest","resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"volumeMounts":[{"name":"default-token-rq5m6","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","nodeName":"10.218.11.66","securityContext":{},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priority":0},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2023-07-06T11:52:35Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2024-02-21T06:03:19Z","reason":"ContainersNotReady","message":"containers with unready status: [pod-create-ns-test1122321]"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2024-02-21T06:03:19Z","reason":"ContainersNotReady","message":"containers with unready status: [pod-create-ns-test1122321]"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2023-07-06T11:39:48Z"}],"hostIP":"10.218.11.66","podIP":"172.30.60.6","startTime":"2023-07-06T11:52:35Z","containerStatuses":[{"name":"pod-create-ns-test1122321","state":{"waiting":{"reason":"ImagePullBackOff","message":"Back-off pulling image \"nginx1:latest\""}},"lastState":{"terminated":{"exitCode":0,"reason":"Completed","startedAt":"2024-02-21T05:43:43Z","finishedAt":"2024-02-21T06:03:00Z","containerID":"docker://8b81fbce210622ea1bccb8a2a3c2eb6af8f8271d874faa1ad39cb46b42bbd2b5"}},"ready":false,"restartCount":5,"image":"nginx:latest","imageID":"docker-pullable://nginx@sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd53c9b31","containerID":"docker://8b81fbce210622ea1bccb8a2a3c2eb6af8f8271d874faa1ad39cb46b42bbd2b5"}],"qosClass":"Guaranteed"}}

**Comment by lburgazzoli** [comment]
it does not seem very different, there are a number of control character here and there also in the etcdctl one.

Have you tried to use the library directly ? jetcd watch example is just an example

for further investigation you must provide a reproducer and open a new issue with it, unfortunately I do not have enough time to do it myself

**Comment by LanMingjin** [comment]
> it does not seem very different, there are a number of control character here and there also in the etcdctl one.
> 
> Have you tried to use the library directly ? jetcd watch example is just an example
> 
> for further investigation you must provide a reproducer and open a new issue with it, unfortunately I do not have enough time to do it myself

Thank you ,I will open a new issue
