### ISSUE TITLE
Expose WithCreatedNotify in WatchOption and isCreatedNotify in WatchResponse

### ISSUE THREAD

**Issue by giri-vsr** [etcd-io/jetcd#1186]
When I create a watch there is delay in watch starting and receiving events.So if I start a watch and put/delete keys in etcd I am missing events.

If I can get Created event in WatchResponse then I can wait for the event to put/delete keys in etcd.

Used Thread.sleep(1000) which seems to be working but not ideal.

Looks like WithCreatedNotify is already there in go client. 
https://github.com/etcd-io/etcd/blob/bdbbde998b7ed434b23676530d10dbd601c4a7c0/client/v3/op.go#L484

**Comment by lburgazzoli** [comment]
can you provide a pr ?

**Comment by giri-vsr** [comment]
@lburgazzoli PR #1187
