### ISSUE TITLE
The value of member id is out of bounds, and the actual value has exceeded the range of long.

### ISSUE THREAD

**Issue by tzfun** [etcd-io/jetcd#1188]
**Versions**
- etcd: 3.5.0
- jetcd: 0.6.1
- java: 11

**Describe the bug**
The actual value is 18305956170087212562

However, the value obtained in the jetcd interface is -8170086329776577000

The same problem exists in the Leader id, which makes me wonder whether the long value in other places is also out of bounds?

**Comment by lburgazzoli** [comment]
I think it is pretty much expected as Java does not have unsigned integer so unit64 is mapped to 'long' which if you print it can overflow but it is bit by bit correct.

You can use 'Long.toUnsignedString(...)' to get an unsigned string

See the protobuf reference guide to know more about type mapping: https://protobuf.dev/programming-guides/proto3/

Let me know if this answers your question/issue.

**Comment by tzfun** [comment]
Yes, this is how I currently handle it. I think that the current long type should be replaced by a wider range of types in the interface definition, such as double, so that at least the caller can get readable data. 😅

**Comment by lburgazzoli** [comment]
Well, it is already machine readable :) but yes, we can wrap it as a  BigInteger but if it is for the only purpose of having it nicely represented on screen, well then it can be easily done by the library consumer when/where needed.

If you have time, then you can provide a PR, however mind not to break backward compatibility.

**Comment by tzfun** [comment]
Yes, I am now using BigInteger to do the conversion.

Ok, next I will pull a branch and try to add some interfaces, I will ensure backward compatibility.
