### ISSUE TITLE
how to use txn.If()   check whether some key exists？

### ISSUE THREAD

**Issue by ww1223708191** [etcd-io/jetcd#1191]
**Is your feature request related to a problem? Please describe.**

java version 1.8
jetcd-core version 0.7.5

**Describe the solution you'd like**
I want to use txn.If() check key exists and do txn.Then()

**Describe alternatives you've considered**

**Additional context**

**Comment by liangyuanpeng** [comment]
Maybe you're looking the lock client? more message for it can help.

**Comment by ww1223708191** [comment]
>
