### ISSUE TITLE
获取Kubernetes集群1.24中etcd数据部分显示乱码

### ISSUE THREAD

**Issue by sun363587351** [etcd-io/jetcd#1202]
**Versions**
- etcd: 3.5.4
- jetcd: 0.7.6
- java: 17

**Describe the bug**
获取Kubernetes集群1.24中etcd数据部分显示乱码

**Comment by sun363587351** [comment]
import io.etcd.jetcd.*;
import io.etcd.jetcd.cluster.Member;
import io.etcd.jetcd.cluster.MemberListResponse;
import io.etcd.jetcd.kv.GetResponse;
import io.etcd.jetcd.options.GetOption;
import io.grpc.netty.GrpcSslContexts;
import io.netty.handler.ssl.SslContext;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class EtcdClientWithCertificate {
    public static void main(String[] args) throws Exception {
        // 加载客户端证书和密钥
        File certFile = new File("src/main/resources/etcdssl/server.crt");
        File keyFile = new File("src/main/resources/etcdssl/server.key");

        SslContext sslContext = GrpcSslContexts.forClient()
                // 设置使用的那种ssl实现方式
                .trustManager(new File("src/main/resources/etcdssl/ca.crt"))
                .keyManager(certFile, keyFile)
                .build();
        // 创建 etcd 客户端
        Client client = Client.builder()
                .endpoints("http://x.x.x.x:2379")
                .sslContext(sslContext)
                .build();

        KV kvClient = client.getKVClient();
        GetOption getOption = GetOption.newBuilder().withPrefix(ByteSequence.from("registry".getBytes())).build();
        GetResponse response = kvClient.get(ByteSequence.from("/registry/services/specs/kube-system/kube-dns", StandardCharsets.UTF_8), getOption).get();
        // Process the response
        response.getKvs().forEach(kv -> {
            String key = kv.getKey().toString(StandardCharsets.UTF_8);
            String value = kv.getValue().toString(StandardCharsets.UTF_8);
            }
        });
        client.close();
    }
}

**Comment by lburgazzoli** [comment]
Seems similar to https://github.com/etcd-io/jetcd/issues/1185 at least with the help of google translate (!).
jetcd does not alter the content of the data received by etcd and store it in a plain byte[].

I suggest to debug what is transmitted by etcd and/or to provide a reproducer.

**Comment by liangyuanpeng** [comment]
是的，因为数据时需要解码才能看得到。这是正常的。
注意：使用英语交流，至少通过翻译软件翻译一下.
---
Yes, Data need to decode.
Note: please use english, at least with  the help of google translate.
