### ISSUE TITLE
Drop java 8

### ISSUE THREAD

**Issue by liangyuanpeng** [etcd-io/jetcd#1218]
# :warning:  Here is a notification for drop java8  :warning:  
# :warning:   jetcd still support  run with java8    :warning:  

So far Jetcd still has only one active maintainer, and is active on personal time.

In order to reduce the pressure of maintenance and follow the development of java version, I think it is a good thing that jetcd no longer supports java 8.

Jetcd's maintenance requirements for the java version will likely be LTS-2, it's mean to drop java 8 when after java 21 GA.

The following is the impact on the user list:

:heavy_check_mark: -> No change.
:x: -> Breaking change.

- apache shardingshpere  :heavy_check_mark:
- apache pulsar  :heavy_check_mark:
- apache shenyu  :heavy_check_mark:
- apache eventmesh  :heavy_check_mark:
- apache dolphinscheduler :heavy_check_mark:
- apache bookkeeper
- apache kyuubi  ❌

**Comment by Pil0tXia** [comment]
I personally don’t think the Java version change made to etcd will affect EventMesh.

**Comment by johnshajiang** [comment]
Not sure many jetcd users are watching this project.
You may want to forward this proposal to `etcd-dev` for wide discussion.

P.S. `TLS-2` or `LTS-2`?

**Comment by lburgazzoli** [comment]
> P.S. `TLS-2` or `LTS-2`?

fixed

**Comment by lburgazzoli** [comment]
@liangyuanpeng will you work on this ?

**Comment by liangyuanpeng** [comment]
Yes, assign me please,Thanks.

**Comment by tulayang** [comment]
You've done a very bad thing and wasted a week of my time.

**Comment by johnshajiang** [comment]
@tulayang 
It also took me some time to investigate why couldn't build this project with JDK 8 ;-)
But currently the jars should still work with all the LTS JDK releases, including 8.

**Comment by liangyuanpeng** [comment]
@tulayang  
Could you please provide more info for it? JEtcd still support java8.

**Comment by pan3793** [comment]
Forward my concern from the Apache Kyuubi community.

> Thanks for the information, there is no plan, and not likely to happen in Kyuubi to drop support for Java 8 recently, especially for the client module.
>
> Actually, it's far from Java 8 to reach EOL, as a client library, I suggest the maintainer evaluate the decision of dropping support for Java8 seriously.
>
> https://www.azul.com/products/azul-support-roadmap/

BTW, any **specific issues** for keeping support for Java8?

**Comment by liangyuanpeng** [comment]
> BTW, any specific issues for keeping support for Java8?

https://github.com/etcd-io/jetcd/issues/1181#issuecomment-1702300819 vvv

> I don't think this can last forever as many libraries and tools will at some point drop java 8 support. Also, I'm the only maintainer so I would like to minimize maintenance as much as possible.

@pan3793 
Thanks for your feedback, this is important for project development.

Actually, there are not some specific issues for it, Except it is currently not possible to build with java8.

Jetcd depends on vertx-grpc. Currently, vertx-grpc 5.x CI no longer has java8, so may encounter obstacles when upgrading the vertx-grpc component in the future.


This issue just a notification now, I think we will still support java8 for some time to come.

**Comment by pan3793** [comment]
@liangyuanpeng thanks for supplying background, I just left my concerns from the Apache Kyuubi aspect and it's up to the project maintainer for final decision.

**Comment by lburgazzoli** [comment]
Java 8 will be dropped with v0.8.x releases
