### ISSUE TITLE
Pre-check non-Java files on PR

### ISSUE THREAD

**Issue by johnshajiang** [etcd-io/jetcd#1221]
Spotless Gradle plugin just focus on `.java` files, so it would be better to add one more GitHub workflow job to check non-Java files as the prerequisites for a PR.
This new job may run a shell script to check if trailing whitespaces exist and newlines miss.

**Comment by lburgazzoli** [comment]
@johnshajiang will you work on this issue ?

**Comment by johnshajiang** [comment]
@lburgazzoli 
Yes, I'm trying to do that.
