### ISSUE TITLE
jetcd-ctl may hang if no etcd

### ISSUE THREAD

**Issue by johnshajiang** [etcd-io/jetcd#1226]
If the server is unaccessible due to, for example, network issue or etcd doesn't start yet, `jetcd-ctl` may hang.

Don't start the etcd and just run the command `./gradlew run --args="put foo bar"`, this execution cannot complete.
The [client] (`CompletableFuture::get`) has being waited for the response, though never response comes.

For this case, the client should encounter an IOException due to the connection is refused.
And `CompletableFuture::get` may need a timeout specified by user.

[client]:
<https://github.com/etcd-io/jetcd/blob/main/jetcd-ctl/src/main/java/io/etcd/jetcd/examples/ctl/CommandPut.java#L46>

**Comment by liangyuanpeng** [comment]
This is https://github.com/etcd-io/jetcd/issues/1161#issuecomment-1585712603 

And same behavior with client-go of etcd.

```shell
func Test_etcd(t *testing.T) {
	etcdHost := "localhost:2379"

	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{etcdHost},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		panic(err)
	}
	kv := clientv3.NewKV(cli)
	_, err = kv.Put(context.TODO(), "/hello", "world")
	if err != nil {
		panic(err)
	}
}
```

```shell
lan@lan:~/app$ go test -timeout 120s -run ^Test_etcd$ manager -v
=== RUN   Test_etcd
panic: test timed out after 2m0s
running tests:
        Test_etcd (2m0s)
```

**Comment by lburgazzoli** [comment]
Seems to be related to https://github.com/etcd-io/jetcd/issues/1209#issuecomment-1695648397
in grpc-java there is a clear distinction between retry (which is what you can configure through the jetcd client) and reconnect (which is handled by grpc-java and there is not so much option to configure it)

**Comment by johnshajiang** [comment]
> And same behavior with client-go of etcd.

Executed `etcdctl put foo bar` without `etcd`, the client failed fast and outputted the error like the below,
```
connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused"
```

**Comment by lburgazzoli** [comment]
can you add disable waitForReady in the example ? I guess it should then fail

**Comment by johnshajiang** [comment]
@lburgazzoli 
> can you disable waitForReady in the example ? I guess it should then fail

`ClientBuilder.waitForReady(true)` worked for me, thanks!

**Comment by johnshajiang** [comment]
I suppose users generally use `jetcd` programmatically.
So, I'm OK if `jetcd-core` APIs are working.

Just out of curiosity, why does this project provide such client `jetcd-ctl`?
Is there any scenario that uses this client in command line?

**Comment by liangyuanpeng** [comment]
@lburgazzoli 
In production I believe people use `etcdctl` command line and not `jetcd-ctl`, so it is reasonable for `jetcd-ctl` to be used only as an example of `jetcd`. As an usage reference, I believe `jetcd-ctl` may have some reference value, but I'm a little on the fence about PR right now, do you want it to move forward?

@johnshajiang 
Would also like to hear your thoughts on the `jetcd-ctl` .

**Comment by johnshajiang** [comment]
@liangyuanpeng 
> Would also like to hear your thoughts on the jetcd-ctl.

Frankly, I'm new to `jetcd` and not familiar with the history.

Just from my point of view, `jetcd-ctl` may not helpful for almost all cases.
Especially it doesn't provide a standalone command tool, so-called `jetcdctl`, as `etcdctl` in `etcd` distribution.
It looks not convenient to run a tool from `java` command, even though you can provide a single executable (uber) jar.

As for the usage reference, I think the examples on `jetcd-core` APIs should be more meaningful.
In fact, it is much easer to build different and complicated cases programmatically.

**Comment by lburgazzoli** [comment]
@liangyuanpeng I do think jetcd-ctl is a little bit misleading as it give the false impression that there is a sort of java cli whereas it is far to be of any usefulness. 
@johnshajiang if someone has times to create concrete examples, then I'll be very happy to retire jetcd-ctl
