### ISSUE TITLE
Etcd memory leak when using jetcd-core 0.7.6

### ISSUE THREAD

**Issue by zivkovic** [etcd-io/jetcd#1236]
**Versions**
- etcd: 3.4.12
- jetcd: 0.7.6
- java: 17

**Describe the bug**
When using leases and keepAliveOnce function, there seems to be a memory leak inside of etcd, caused by jetcd-core version 0.7.6. This is easily reproducable by simply creating a key with a lease and using keepAliveOnce on that lease. To check if the problem exists, we can simply view etcd metrics (http://localhost:2379/metrics) and check the "go_goroutines" count. This count is rising out of control.  If I check the same code (same example project) using jetcd-core version 0.7.5 the problem is not present. Because of this I believe the problem to be caused by the following PR https://github.com/etcd-io/jetcd/pull/1165.

**To Reproduce**
Create a key with a lease and renew the lease periodically using keepAliveOnce. I have attached a simple example project which demonstrates this issue. Run the example project once with jetcd-core 0.7.6 and once with jetcd-core 0.7.5 and compare the outputs. The difference should be pretty big.
[example-project-jetcd-bug.zip](https://github.com/etcd-io/jetcd/files/12791865/example-project-jetcd-bug.zip)

**Expected behavior**
Etcd go_goroutines count should rise slightly (for this test count should be around 150 or less) and not as much as now (100k+ in attached test in 60 seconds)

**Additional context**
Because every go_routine uses a minimum of 8KB of memory, this can quickly spiral out of control and etcd instance consumes all available memory.

**Comment by liangyuanpeng** [comment]
@zivkovic  I have tested it and it's true, do you want to  create a PR for it?

**Comment by zivkovic** [comment]
I do not have the time currently for this. I tried some changes, but the tests for speed of leases were failing. If I manage to get some time at a later date, maybe, but until then no.

**Comment by lburgazzoli** [comment]
have you been able to determine the root cause of this behavior ?

**Comment by zivkovic** [comment]
So, the root cause seems to stem from this code:
```
leaseStub
            .leaseKeepAlive(s -> s.write(LeaseKeepAliveRequest.newBuilder().setID(leaseId).build()))
            .handler(r -> future.complete(new LeaseKeepAliveResponse(r)))
            .exceptionHandler(future::completeExceptionally);
```
If I update it like so:
```
leaseStub
            .leaseKeepAlive(s -> s.end(LeaseKeepAliveRequest.newBuilder().setID(leaseId).build()))
            .handler(r -> future.complete(new LeaseKeepAliveResponse(r)))
            .exceptionHandler(future::completeExceptionally);
```

Seems like the mistake here was forgetting to end the actual stream. Using `s.end` instead of `s.write`, the problem disappears, but reintroduces keepAliveOnce delay as reported on the following issue: https://github.com/etcd-io/jetcd/issues/1119

**Comment by lburgazzoli** [comment]
@zivkovic can you test if https://github.com/etcd-io/jetcd/pull/1240 fixes the memory leak ?

**Comment by lburgazzoli** [comment]
@liangyuanpeng @zivkovic added a test to check the go routines, please have a look.
