### ISSUE TITLE
The 0.7.6 version does not throw an exception when keepAliveOnce failed

### ISSUE THREAD

**Issue by sukidesuka** [etcd-io/jetcd#1254]
**Versions**
- etcd: 3.5.9
- jetcd: 0.7.6
- java: 11

**Describe the bug**

If you use keepAliveOnce on an expired lease, it should throw an 
`io.etcd.jetcd.common.exception.EtcdException: etcdserver: requested lease not found` exception. 
However, in version 0.7.6, nothing happens and it behaves as if the lease is successfully renewed.

When I used jetcd 0.7.5, it immediately worked fine.

**To Reproduce**
1. Use grant to create a lease.
1. Wait for the lease to expire.
1. Use keepAliveOnce to renew the lease.

**Expected behavior**
throw an `io.etcd.jetcd.common.exception.EtcdException: etcdserver: requested lease not found` exception. 

**Additional context**

Normally, I would start by creating a lease and then binding it to a key. So if the reproduction fails, you can try binding the lease to a key.

My ETCD is running in a Kubernetes cluster and using 3 replicas.

**Comment by sukidesuka** [comment]
@lburgazzoli

**Comment by lburgazzoli** [comment]
@sukidesuka do you have any time to provide a reproduce in a form of an integration test ?

**Comment by lburgazzoli** [comment]
@sukidesuka I've created a pr https://github.com/etcd-io/jetcd/pull/1256, can you out the fix ?
