### ISSUE TITLE
How to the get the response in JSON format 

### ISSUE THREAD

**Issue by irfanjs** [etcd-io/jetcd#1259]
I have below code to get the value from specific key.   the response is coming in string format , can we get it in JSON format ??

 ```
  String cluster0 = "http://<IP:PORT>";
        ClientBuilder clientBuilder = Client.builder()
                .user(ByteSequence.from("root".getBytes()))
                .password(ByteSequence.from("pass".getBytes()))
                .endpoints(cluster0);
        Client client = clientBuilder.build();
        KV kvClient = client.getKVClient();
        
        ByteSequence key = ByteSequence.from("admin".getBytes());
        ByteSequence value = ByteSequence.from("admin123".getBytes());
        
        kvClient.put(key, value).get();
        
        CompletableFuture<GetResponse> getFuture = kvClient.get(key);
        GetResponse response = getFuture.get();
        
        System.out.println(response.toString());

```

in command line , there is option like this :  `etcdctl get mykey -w=json`

how can i achieve this using JAVA client ? please suggest

**Comment by irfanjs** [comment]
we just want the value of specific key in the response. 
currently , it provides all extra information like raft, version , header etc. .
 
How can I exclude all the info and just get the value of key ?

**Comment by lburgazzoli** [comment]
the `GetResponse.getKvs` returns the key/values pair associated with the response, that is likely what you are looking for.

**Comment by irfanjs** [comment]
I tried below code . but it is just printing the object . Am I missing anything ??

```
   java.util.List a;
        a = response.getKvs();
        for (int i = 0; i < a.size(); i++) {
            // Print all elements of List
            System.out.println(a.get(i));
        }
        
```
output is : io.etcd.jetcd.KeyValue@628c5463

**Comment by lburgazzoli** [comment]
This example https://github.com/etcd-io/jetcd/blob/main/jetcd-ctl/src/main/java/io/etcd/jetcd/examples/ctl/CommandGet.java may help, let me know

**Comment by irfanjs** [comment]
@lburgazzoli : Thanks a lot . It worked
