### ISSUE TITLE
watch without waitForReady sometimes not reschedule when all servers are down

### ISSUE THREAD

**Issue by tunefun** [etcd-io/jetcd#1261]
**Versions**
- etcd: 3.5.8
- jetcd: 0.7.6
- java: 1.8

**Describe the bug**
Watch without waitForReady sometimes not reschedule when all servers are down. When we reboot part of servers, watch stream on those servers rescheduled as expected;When we shutdown all servers and reboot all servers after a while, watch not rescheduled as expected.

Review code below, we will loss the event when event comes before setting handler.
https://github.com/etcd-io/jetcd/blob/c51adfb74874357f64a351490219c11385b614ab/jetcd-core/src/main/java/io/etcd/jetcd/impl/WatchImpl.java#L180-L188

example: 
connect failed -> StreamObserverReadStream.onError() -> WatcherImpl.onError()  -> WatcherImpl.reschedule() -> WatcherImpl.resume() -> WatchVertxStub.watch() -> connect failed -> StreamObserverReadStream.onError() -> StreamObserverReadStream.exceptionHandler is null  -> rstream.exceptionHandler(this::onError)

**To Reproduce**
as description

**Expected behavior**
watch rescheduled

**Comment by lburgazzoli** [comment]
@tenghuanhe can you provide a reproducer and/or willing to work on a PR ?

**Comment by giri-vsr** [comment]
We are also facing same issue.I am not able to reproduce using test containers.

This is what is happening.
For creating watch `io.vertx.grpc.stub.ClientCalls.manyToMany` is called which returns rstream and after that we register exceptionHandler but in this case exception happens before rstream is returned thats why StreamObserverReadStream.exceptionHandler is null.So it not rescheduling(onError is not called).

Exception occurs in `StreamObserver<I> request = delegate.apply(response);`

```
  public static <I, O> ReadStream<O> manyToMany(ContextInternal ctx, Handler<WriteStream<I>> requestHandler, Function<StreamObserver<O>, StreamObserver<I>> delegate) {
    StreamObserverReadStream<O> response = new StreamObserverReadStream<>();
    StreamObserver<I> request = delegate.apply(response);
    requestHandler.handle(new GrpcWriteStream<>(request));
    return response;
  }
```

@lburgazzoli I am not sure what will be the fix?

**Comment by lburgazzoli** [comment]
@giri-vsr I do have some very limited time at this stage and I need to digg into the issue more to understand what to do
If you have any time,  maybe it would be good to chat with the vert.x folks to see what a solution could be.

**Comment by giri-vsr** [comment]
Maybe we need to move to https://github.com/eclipse-vertx/vertx-grpc since https://github.com/vert-x3/vertx-grpc is deprecated

**Comment by lburgazzoli** [comment]
> Maybe we need to move to https://github.com/eclipse-vertx/vertx-grpc since https://github.com/vert-x3/vertx-grpc is deprecated

can you try to work on a PR ?

**Comment by giri-vsr** [comment]
Issue is fixed in https://github.com/vert-x3/vertx-grpc 4.5.1 and Move to https://github.com/eclipse-vertx/vertx-grpc should be handled separately.

**Comment by tunefun** [comment]
@lburgazzoli @giri-vsr hello, it seems that election observe have the same problem
https://github.com/etcd-io/jetcd/blob/85a9a54c3f42c310bf861a37ce909aa584571f0b/jetcd-core/src/main/java/io/etcd/jetcd/impl/ElectionImpl.java#L116-L119

and maybe we can also registers end handler before watch request？

**Comment by tunefun** [comment]
also LeaseImpl,MaintenanceImpl：
https://github.com/etcd-io/jetcd/blob/85a9a54c3f42c310bf861a37ce909aa584571f0b/jetcd-core/src/main/java/io/etcd/jetcd/impl/LeaseImpl.java#L150-L163
https://github.com/etcd-io/jetcd/blob/85a9a54c3f42c310bf861a37ce909aa584571f0b/jetcd-core/src/main/java/io/etcd/jetcd/impl/LeaseImpl.java#L197-L199
https://github.com/etcd-io/jetcd/blob/85a9a54c3f42c310bf861a37ce909aa584571f0b/jetcd-core/src/main/java/io/etcd/jetcd/impl/MaintenanceImpl.java#L122-L136
https://github.com/etcd-io/jetcd/blob/85a9a54c3f42c310bf861a37ce909aa584571f0b/jetcd-core/src/main/java/io/etcd/jetcd/impl/MaintenanceImpl.java#L144-L147
