### ISSUE TITLE
not able to read any other etcd key while processing a etcd watch event. its blocked indefinitely

### ISSUE THREAD

**Issue by ankit2610** [etcd-io/jetcd#1285]
**Versions**
- etcd: v3.4.28
- jetcd: 0.7.6
- java: 17

**Describe the bug**
I have some keys in etcd like **key1/123** and **key2/456**.

I have created a watcher on delete of a key prefixed with  key1.
when I process a key1 delete event, I am trying to get all the keys prefixed with key2, and its blocked here.

**To Reproduce**
Create a watch for one key and while processing the watch event , read another key. It will hang indefinitely.
**Expected behavior**
it should be able to read etcd keys irrespective of the context from where it is called.

**Additional context**

**Comment by lburgazzoli** [comment]
https://github.com/etcd-io/jetcd/issues/1089

**Comment by ankit2610** [comment]
sure . thanks for the update

**Comment by lburgazzoli** [comment]
@ankit2610 can this be closed ?
