### ISSUE TITLE
election observe sometimes lose the first event

### ISSUE THREAD

**Issue by tunefun** [etcd-io/jetcd#1308]
@lburgazzoli @giri-vsr hello, it seems that election observe have the same problem
https://github.com/etcd-io/jetcd/blob/85a9a54c3f42c310bf861a37ce909aa584571f0b/jetcd-core/src/main/java/io/etcd/jetcd/impl/ElectionImpl.java#L116-L119

and maybe we can also registers end handler before watch request？

_Originally posted by @tunefun in https://github.com/etcd-io/jetcd/issues/1261#issuecomment-1887149993_

**Comment by lburgazzoli** [comment]
a pr and related integration test would be more than welcome
