### ISSUE TITLE
concurrency/coordination APIs

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/jetcd#212]
This is to track supporting locks and elections, probably through RPCs.

**Comment by christian-pinto** [comment]
Hello,

do you have a rough estimation of when distributed locks and other coordination facilities will be supported?

Thanks a lot,
Christian

**Comment by fanminshi** [comment]
@christian-pinto the distributed lock and leader election are easier to implement since etcd supports those from service side. I can probably get those two done fair quickly.  Will those two recipes to be sufficient for you?

**Comment by christian-pinto** [comment]
Thanks @fanminshi , I think those recipes are going to be enough for my needs. BTW, besides the standard blocking mutexes, is there also going to be a try-lock kind of functionality?

Thanks again,
Christian

**Comment by fanminshi** [comment]
@christian-pinto do you mean try-lock as described here https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/Lock.html#tryLock()?

**Comment by christian-pinto** [comment]
Exactly, that's what I meant with try-lock.

Thanks,
Christian

**Comment by fanminshi** [comment]
@christian-pinto no plan to implement `try-lock` yet. I'll take a look into this once i get the distributed lock and leader election working.

**Comment by lburgazzoli** [comment]
@fanminshi as far as I can see the go client implements leader election and locks leveraging txn so as they are not part of the core functionalities does it make sense to have a structure like :

- jetcd-recupes/leader-election
- jetcd-recupes/mutex
- ...

btw, I'm also interested in having the leader election receipe so I can use it in Apache Camel.

**Comment by dinoopt** [comment]
@fanminshi I use a jetcd client to talk to etcd in my project and I'm specifically looking for the locking feature support in jetcd. As I understand, currently only the 'go' etcd client supports the lock API. Could you kindly let know when the locking support would be available in jetcd ?
