### ISSUE TITLE
Support for Java 9

### ISSUE THREAD

**Issue by lburgazzoli** [etcd-io/jetcd#242]
Java 9 GA has been released so we should plan to properly support it

**Comment by fanminshi** [comment]
is there any java 9 feature that jetcd might want?

**Comment by lburgazzoli** [comment]
no it is more about compatibility of jetcd and its dependencies and to trst if we can make jetcd play with JPMS

**Comment by jmaasing** [comment]
Tried on Java 11 in an application using JPMS and jetcd does not work. The application can not even start due to the dependecy on gRPC :

`Modules grpc.api and grpc.context export package io.grpc to module protobuf.java`

https://github.com/grpc/grpc-java/issues/3522
