### ISSUE TITLE
Disabling hostname checking for connecting via SSL

### ISSUE THREAD

**Issue by agarman** [etcd-io/jetcd#258]
Attempting to connect to compose.io etcd service using example in [SssTest.java](https://github.com/coreos/jetcd/blob/master/jetcd-core/src/test/java/com/coreos/jetcd/internal/impl/SslTest.java#L44). It looks like compose.io uses certificates that do not `matchDNS`. Is there a way to disable `HostnameChecker` exposed by `ClientBuilder` or `GrpcSslContexts`?

```
CertificateException No subject alternative DNS name matching etcd found.
	sun.security.util.HostnameChecker.matchDNS (HostnameChecker.java:204)
	sun.security.util.HostnameChecker.match (HostnameChecker.java:95)
	sun.security.ssl.X509TrustManagerImpl.checkIdentity (X509TrustManagerImpl.java:455)
	sun.security.ssl.X509TrustManagerImpl.checkIdentity (X509TrustManagerImpl.java:436)
	sun.security.ssl.X509TrustManagerImpl.checkTrusted (X509TrustManagerImpl.java:252)
sun.security.ssl.X509TrustManagerImpl.checkServerTrusted (X509TrustManagerImpl.java:136)
io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify (ReferenceCountedOpenSslClientContext.java:221)
io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify (ReferenceCountedOpenSslContext.java:644)
io.netty.internal.tcnative.SSL.readFromSSL (SSL.java:-2)
io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData (ReferenceCountedOpenSslEngine.java:482)
io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap (ReferenceCountedOpenSslEngine.java:1020)
io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap (ReferenceCountedOpenSslEngine.java:1127)
```

**Comment by lburgazzoli** [comment]
You can set the right authority via the builder:

    https://github.com/coreos/jetcd/blob/master/jetcd-core/src/test/java/com/coreos/jetcd/internal/impl/SslTest.java#L46

**Comment by agarman** [comment]
@lburgazzoli thanks - looks like I need to use a SNAPSHOT to get access to that.

**Comment by kingpong** [comment]
@lburgazzoli How should one set the authority correctly when there are multiple endpoints, each with distinct names and certificates?

**Comment by lburgazzoli** [comment]
I think there was a discussion about this issue on grpc-java about this so I need to check what solution has been implemented and reflect it on jetcd but I had no time so far. The issue is on how the grpc-java NameResolver.

**Comment by agarman** [comment]
Re-opening as this is still not usable. Authority needs to be set per endpoint.

**Comment by lburgazzoli** [comment]
@agarman I'm not sure about what we can do on jetcd side, see the following conversations:

- https://github.com/grpc/grpc-java/pull/2662
- https://groups.google.com/forum/#!msg/grpc-io/xtwACYjZ2p8/Vg23_VTSAAAJ
- https://github.com/ExampleDriven/spring-boot-grpc-example/pull/3

**Comment by lburgazzoli** [comment]
@agarman @kingpong I think I need to wait for https://github.com/grpc/grpc-java/issues/4469 to be implemented to provide a solution.

**Comment by agarman** [comment]
@lburgazzoli understood

**Comment by im-bravo** [comment]
I updated the library version to the latest version to solve this problem
https://mvnrepository.com/artifact/io.etcd/jetcd-all
