### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by hexfusion** [etcd-io/jetcd#300]
@fanminshi could you take some time and flag issues you feel would be good for someone just getting involved with the project to take on. This might help those who want to help, contribute. Thanks!

**Comment by fanminshi** [comment]
@hexfusion good idea. I will create concrete issues like what we do in etcd repo.

**Comment by fanminshi** [comment]
cc/ @lburgazzoli Would you also like to create any issues that you think community members can help.
