### ISSUE TITLE
Client Feature matrix

### ISSUE THREAD

**Issue by fanminshi** [etcd-io/jetcd#307]
It will be nice to know which features that the java client supports and which one doesn't. 
This also gives us an idea on what works still needed to be done for jetcd.

**Comment by fanminshi** [comment]
cc/ @gyuho

**Comment by gyuho** [comment]
@fanminshi ack, I am writing high-level feature docs to share sometime this/next week.

**Comment by hexfusion** [comment]
@fanminshi sure I will see what @gyuho comes up with and see where I can help.

**Comment by gyuho** [comment]
@fanminshi @hexfusion Sounds good. I will keep you updated once draft is up. This will be better to be documented in etcd side (related https://github.com/coreos/etcd/issues/9156).

**Comment by gyuho** [comment]
I've added Go client part http://etcd.readthedocs.io/en/latest/client-feature-matrix.html here. Whoever interested in keeping Java part up-to-date is welcome to contribute.

**Comment by hexfusion** [comment]
@gyuho I can take this on would be good for me to dig into jetcd a little anyway. What are the requirements for adding new client packages to etcd-io have we outlined that yet?

**Comment by gyuho** [comment]
@hexfusion Sure, please work with @lburgazzoli who has some roadmap on jetcd development.

**Comment by hexfusion** [comment]
@lburgazzoli any details you can shed are appreciated. Feel free to email if it is information not in the repo.

**Comment by lburgazzoli** [comment]
@hexfusion there's definitively a need for:

* better testing
    - remove testng
    - migrate to junit5
    - better and standalone unit tests using mock objects (a framework to easily mock etcd's grpc communication would be really useful)
    - better and standalone integration tests 
    - add more coverage

* dcumentation
    - improve javadoc
    - create a user guide
