### ISSUE TITLE
Support async apis

### ISSUE THREAD

**Issue by fanminshi** [etcd-io/jetcd#308]
APIs [Watch](https://github.com/coreos/jetcd/blob/master/jetcd-core/src/main/java/com/coreos/jetcd/Watch.java), [keepAlive](https://github.com/coreos/jetcd/blob/master/jetcd-core/src/main/java/com/coreos/jetcd/Lease.java#L73), and [snapshot](https://github.com/coreos/jetcd/blob/master/jetcd-core/src/main/java/com/coreos/jetcd/Maintenance.java#L118) are synchronous operation.

Few users want to have async version of those because creating extra thread to handle the sync api is expensive, and also the user usually doesn't want the main executing thread to be blocked.

ref:  https://github.com/coreos/jetcd/issues/281

**Comment by lburgazzoli** [comment]
keep alive and snapshot are now async, watch will be implemented after etcd 3.4 is released
