### ISSUE TITLE
ByteSequence should offer methods with an encoding argument

### ISSUE THREAD

**Issue by vorburger** [etcd-io/jetcd#342]
`com.coreos.jetcd.data.ByteSequence` uses java.lang.String's `getBytes()` which is _using the platform's default charset_. 

ByteSequence's `toString()` method already has a `java.nio.charset.Charset` argument, but e.g. its `fromString()` and several other methods do not.

Ideally, all ByteSequence's methods (static and constructors) should have variant which also accept an `java.nio.charset.Charset` argument?

**Comment by vorburger** [comment]
@lburgazzoli there's more to be done here IMHO... I'll open a 2nd PR following up on your 1st one.

**Comment by vorburger** [comment]
FTR - more discussion about this now in #364 ...

**Comment by lburgazzoli** [comment]
ok
