### ISSUE TITLE
dependabot

### ISSUE THREAD

**Issue by vorburger** [etcd-io/jetcd#350]
I've used [my github2github.sh](https://github.com/vorburger/vorburger-dotfiles-bin-etc/commit/6280479c242055882035eefddca732f1ce0874e9) to "manually port" and contribute a few version bumps proposed by https://dependabot.com (@dependabot) such as #347 and #348 and #349 to this project.

Perhaps someone with permissions on this project would like to enable dependabot directly on this repo?

**Comment by lburgazzoli** [comment]
I've never used it, is it possible to exclude of the dependencies from the check ?

**Comment by vorburger** [comment]
@lburgazzoli they do it differently, it's one of those "bot" things... it raises PRs, and if you close a PR without merging it it's smart enough to shut up about it :smile: Or at least for a while - and I think with different comments in such PRs you can make it exclude longer (I've never tried, but if you read the "Dependabot commands and options" e.g. on https://github.com/vorburger/jetcd/pull/2 that seems to be for that).

**Comment by lburgazzoli** [comment]
ah yeah, let me try

**Comment by lburgazzoli** [comment]
done
