### ISSUE TITLE
Mixed JUL & SLF4J logging framework use

### ISSUE THREAD

**Issue by vorburger** [etcd-io/jetcd#370]
Code review in #363 has stumbled upon that this project currently uses mixed JUL & SLF4J logging frameworks - [some JUL here](https://github.com/etcd-io/jetcd/search?q=java.util.logging&unscoped_q=java.util.logging) and [some slf4j here](https://github.com/etcd-io/jetcd/search?q=slf4j&unscoped_q=slf4j).

The goal of this issue, if everyone agrees, is to move those 2-3 JUL usages to SLF4j, and then to have some Checkstyle/-FindBugs-SpotBugs rule which fails the build just in case anyone else in the future were to re-introduce any `java.util.logging` usage again.

@lburgazzoli is this something you would have time for doing? Just asking! :smile:

**Comment by lburgazzoli** [comment]
@vorburger at the moment no but I can check next week but if you have time, you're more than welcome (and thx for all the fixes btw)
