### ISSUE TITLE
ByteSequence toString ?

### ISSUE THREAD

**Issue by vorburger** [etcd-io/jetcd#399]
For debugging, I've found it sometimes useful to log the ByteSequence of a KV.

Our `io.etcd.jetcd.data.ByteSequence` currently does not implement `java.lang.Object.toString()`. 

I have therefore implemented [this helper utility for this](https://github.com/vorburger/opendaylight-etcd/blob/d0ea73c1181f27d33a7aa4d199d9c4887e26cdfc/ds/src/main/java/org/opendaylight/etcd/utils/ByteSequences.java) (see also [its usage in ByteSequencesTest](https://github.com/vorburger/opendaylight-etcd/blob/e2af4a37e2b0fe73168ccc8c8fdbe3efa473b40d/ds/src/test/java/org/opendaylight/etcd/utils/test/ByteSequencesTest.java)), and was wondering if a contribution with that here would be welcome? 

Keys (and Values) of course may well contain arbitrary byte sequences. The escaping I implemented is more meant to "look nice, and compact, in logs" than being a reliable bi-directional "codec" (i.e. my goal was only to be able to go from byte[] to readable text, NOT to come up with a representation where said text can be re-transformed into a byte[]). It looks like e.g. «A·00B·FF» for 4 bytes ('A', 0 _b_, 'B', FF _b_). 

PS: `ByteSequence` does have a `toString(Charset)` but that is not for debug logging, and perhaps should have instead better be named `getString()`, like its `getBytes()`, or even `asString()`, but it's already too late for that now, I guess?)

PPS: Perhaps `etcdctl ls` could print using the same format? I'll file an issue there.

**Comment by lburgazzoli** [comment]
@vorburger we could ad an `toHexString` ?

**Comment by adamlehenbauer** [comment]
`toHextString` wouldn't really help because that's not in the java.lang.Object contract.

My vote would be for a toString() that uses the platform default CHARSET to transform.

**Comment by Hendrik-H** [comment]
I don't think platform default is a good choice in a cluster application. I would either use UTF-8, make it configurable or return a hey string from `toString`.
