### ISSUE TITLE
 set keepAlive, when one of computer disconnect and connect later, the all keepAlive invalid

### ISSUE THREAD

**Issue by wenjin227** [etcd-io/jetcd#400]
set keepAlive, when one of computer disconnect and connect later, the all keepAlive invalid

**Comment by lburgazzoli** [comment]
can you provide more details ?

**Comment by vorburger** [comment]
@wenjin227 or just directly raise a Pull Request :smile: to illustrate what you mean in code instead words?

**Comment by wenjin227** [comment]
there is three computer,each computer install etcd server,they are A ,B ,C
in the A ,run a program to put a key-value(just  like fooa - test) with TTL(2 s) and  keepAlive it.
in the B ,run a program to put a key-value(just  like foob - test) with TTL(2 s) and  keepAlive it
when the A network disconnect and connect(the time between more then 10s ), find the key foob has been deleted or delete later, because the keepAlive in B failure

**Comment by lburgazzoli** [comment]
looks like you have to open an issue on etcd, not jetcd

**Comment by wenjin227** [comment]
maybe the config GRPC make it, when the TTL time is small (1 s)

ETCD_GRPC_KEEPALIVE_MIN_TIME="5s"
ETCD_GRPC_KEEPALIVE_INTERVAL="2h0m0s"
ETCD_GRPC_KEEPALIVE_TIMEOUT="20s"

**Comment by lburgazzoli** [comment]
@wenjiaswe would it be possible to provide a PR with a test case that reproduces the problem ?
