### ISSUE TITLE
QUESTION: Frequent io.grpc.StatusRuntimeException: CANCELLED

### ISSUE THREAD

**Issue by MustAdmin** [etcd-io/jetcd#405]
Hi Jetcd team,

I am using Jetcd driver to connect to ETCD and off late we are seeing a lot of occurrence of this error while reading from ETCD.
```
Exception: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: CANCELLED: Failed to stream message and stacktrace:
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: CANCELLED: Failed to stream message at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) at com.ibm.wml.scoring.online.runtime_manager.utils.Etcd_Get$.get(ETCD_client.scala:482) at 
```
I am thinking this is something related to the time outs that we see while using ETCDCTL. To counter that we use `--dial-timeout=120s` and `--command-timeout=120s` parameters.
I am wondering whether something similar is available in Jetcd to configure the ETCD Client with?

If not, is there any plan to provide it?

**Comment by lburgazzoli** [comment]
Can you add more information about what operation you are trying to do ?

**Comment by dinoopt** [comment]
@lburgazzoli I'm also looking for a similar feature where in like Go client for Etcd, we can provide a timeout value for jetcd also.

eg:
```
ctx, cancel := context.WithTimeout(context.Background(), timeout)
resp, err := kvc.Put(ctx, "sample_key", "sample_value")
```
In this case, the Go client is expected to timeout if the `kvc.Put` operation takes more time than what was specified in `timeout`.

Is there a similar feature available in jetcd, where we can specify a timeout for an Etcd call like put or get which we do through jetcd ?

**Comment by dinoopt** [comment]
@lburgazzoli  Is there a plan for jetcd to implement the timeout feature requested above ? Any feedback would be much appreciated.

**Comment by lburgazzoli** [comment]
I'm currently very busy on other topics so I'm not sure when I can have a look at this, do you have time to work on a PR ?
