### ISSUE TITLE
How to keep watching

### ISSUE THREAD

**Issue by Fangfeikun** [etcd-io/jetcd#411]

**Comment by Fangfeikun** [comment]
I user this to keep listen directory, is there graceful way.
```
  while (true)
    {
              WatchResponse response = watcher.listen();
               for (WatchEvent event : response.getEvents())
                {
                    if (event.getEventType() == WatchEvent.EventType.PUT)
                    {
                        //doing something;
                    }
                }
   }
```

**Comment by Fangfeikun** [comment]
The example code need to set maxEvents, but i want to keep watching.
```
 try (Client client = Client.builder().endpoints(cmd.endpoints.toArray(new String[0])).build();
         Watch watch = client.getWatchClient();
         Watch.Watcher watcher = watch.watch(ByteSequence.from(cmd.key, UTF_8))) {
      for (int i = 0; i < cmd.maxEvents; i++) {
        LOGGER.info("Watching for key={}", cmd.key);
        WatchResponse response = watcher.listen();

        for (WatchEvent event : response.getEvents()) {
          LOGGER.info("type={}, key={}, value={}",
              event.getEventType(),
              Optional.ofNullable(event.getKeyValue().getKey())
                  .map(bs -> bs.toString(UTF_8))
                  .orElse(""),
              Optional.ofNullable(event.getKeyValue().getValue())
                  .map(bs -> bs.toString(UTF_8))
                  .orElse("")
          );
        }
      }
    } catch (Exception e) {
      LOGGER.error("Watching Error {}", e);
      System.exit(1);
    }
```

**Comment by vorburger** [comment]
@Fangfeikun not sure I understand your precise question here... the {{while (true)}} loop kind of thing is the right approach.  Your {{for (int i = 0; i < cmd.maxEvents; i++)}} seems wrong - you may miss watch events like this, no? Also, depending on your application, {{catch (Exception e) { System.exit(1);}} may or may not be the best idea.

But this is all about your application using jetcd - none of this is a bug or feature request for jetcd?!

**Comment by Fangfeikun** [comment]
@vorburger Thanks for your reply,   [examples](https://github.com/etcd-io/jetcd/blob/master/jetcd-examples/jetcd-watch-example/src/main/java/io/etcd/jetcd/examples/watch/Main.java)  use `for (int i = 0; i < cmd.maxEvents; i++)} ` , i want to keep watching, so i use while(true) . The question is i am not sure it is good way.

**Comment by lburgazzoli** [comment]
The interface ha now changed and it is now async:

```java
Watch watch = client.getWatchClient();
Watcher watcher = = watch.watch(key, response -> {
});
```

**Comment by ZhangShangyu** [comment]
wow  nice work 👍    by the way, when will this feature be released?

**Comment by ZhangShangyu** [comment]
look forward to it
