### ISSUE TITLE
Release 0.0.3

### ISSUE THREAD

**Issue by dkellenb** [etcd-io/jetcd#440]
There are quite some PR merged since 0.0.2. What about new release? I'm especially interested to use the new watch API. Please merge #439 before doing the release.

**Comment by lburgazzoli** [comment]
I'm working on in

**Comment by Grisu118** [comment]
It would be great if #437 is also part of the release

**Comment by vorburger** [comment]
@lburgazzoli perhaps this would be a good opportunity to start creating real Release Notes for this project? Dunno if there is any particular great format that is machine readable by update bump tools such as dependabot and others like it (@greysteil do you have any tips?), but we could make a start by just having a CHANGES.md (e.g. [like this one](https://github.com/vorburger/MariaDB4j/blob/master/CHANGES.md)) at the root of the repo? Shout if you would welcome help for this, and I could find a moment to raise a PR add that.. if you agree to keep it maintained?

**Comment by vorburger** [comment]
BTW: Let's mention the new launcher (from #384) in whatever form we document the release!

**Comment by greysteil** [comment]
By far the best guide on changelogs is https://keepachangelog.com/en/1.0.0/ by @olivierlacan.

**Comment by shyamradhakrishnan** [comment]
Please provide any update on the new release

**Comment by lburgazzoli** [comment]
We are working on it, sorry for the delay

**Comment by zonghaishang** [comment]
When is it released?

**Comment by lburgazzoli** [comment]
release done, should be available soon on maven central

**Comment by lburgazzoli** [comment]
yes, it is in my todo list, unfortunately this release was not as easier as it should have been and I had no time, do you want to help ?

**Comment by zonghaishang** [comment]
@lburgazzoli 

v0.3.0 released, but I found that build(tag jetcd-parent-0.3.0) is failed,  can this be used in a production environment?
