### ISSUE TITLE
Correct value for  authority

### ISSUE THREAD

**Issue by shyamradhakrishnan** [etcd-io/jetcd#451]
Has anyone figured out what is the right value of authority to use when using TLS and multiple etcd servers? As far as I understood, the authority must be equal to the hostname of the etcd server itself, but that will not work in case of multiple etcd servers right? Does this mean that TLS cannot be used with multiple etcd servers?

**Comment by lburgazzoli** [comment]
There is an issue with grpc java at the moment that make it not so easy to set up ssl, for more info see:

    https://github.com/grpc/grpc-java/pull/2662
