### ISSUE TITLE
jetcd-core requires quava-jre

### ISSUE THREAD

**Issue by yaskoo** [etcd-io/jetcd#452]
Tried to use jetcd-core 0.3.0-SNAPSHOT as a dependency to my project so I can  register values to etcd v3 and use the new lease functionality.

After adding jetcd-core
```
        ...
        <repositories>
		<repository>
			<id>ssr</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		</repository>
	</repositories>
        <dependencies>
		<dependency>
			<groupId>io.etcd</groupId>
			<artifactId>jetcd-core</artifactId>
			<version>0.3.0-SNAPSHOT</version>
		</dependency>
	</dependencies>
        ....
```
and running my code I get:
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:628)
	at io.grpc.Metadata$Key.<init>(Metadata.java:636)
	at io.grpc.Metadata$Key.<init>(Metadata.java:566)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:735)
	at io.grpc.Metadata$Key.of(Metadata.java:592)
	at io.grpc.Metadata$Key.of(Metadata.java:588)
	at io.etcd.jetcd.ClientConnectionManager.<clinit>(ClientConnectionManager.java:61)
	at io.etcd.jetcd.ClientImpl.<init>(ClientImpl.java:49)
	at io.etcd.jetcd.ClientBuilder.build(ClientBuilder.java:298)
	at com.sirma.itt.seip.configration.proxy.Register.register(Register.java:23)
	at com.sirma.itt.seip.configration.proxy.Register.main(Register.java:70)
```
After some searching I figured that this class comes from guava and looking at the dependency graph I see that jetcd-core only has a transitive dependency to guava 26.0-android trough grpc-core.

After adding an explicit dependency to guava-jre 26.0 to my project - things seem to work properly.
```
                <dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>26.0-jre</version>
		</dependency>
```

**Comment by vorburger** [comment]
@yaskoo Oups. Would you be willing to contribute to this project with a PR which adds a small simple new test which uses the new lease functionality and which fails with the `NoSuchMethodError` and then add the missing dependency to fix that test?

**Comment by yaskoo** [comment]
Sure, but I'm just not sure how log it will take me to do that, I mean I'll need to get a bit more familiar with the internals of the project.
Also I added guava 26.0, but I think I saw some issues which were for bumping guava version to 27.0.
So which version should I set?

**Comment by vorburger** [comment]
>  get a bit more familiar with the internals of the project.

You could probably [find inspiration in the existing tests which are here](https://github.com/etcd-io/jetcd/tree/master/jetcd-core/src/test/java/io/etcd/jetcd). You'll find how they use the `EtcdCluster` _[Launcher](https://github.com/etcd-io/jetcd#launcher)_; I'm guessing your test would also want to do that.

> but I think I saw some issues which were for bumping guava version to 27.0

where?

> So which version should I set?

I think in general bumping to the latest is fine in a project like this. But perhaps that could be separate PR  contribution? What I mean is, it may be clearest if you fix the problem you raised here using the current Guava version, and then separately propose to bump it? It's nice to keep things clear. Just a suggestion.

**Comment by yaskoo** [comment]
Actually, I think after all everything is fine and my project was the real problem.
After forking the repo and starting to work on a test case everything appeared to work just fine and there're already are tests for the leases.
So I created a brand new project, added the jetcd-core dependency, granted a lease, put some keys ...everything works.

After some more digging in the many (many) modules that the project I work on has, it seems that one of the modules has a dependency on an older version of guava which ends up to be the one that's used.

So, apologies for the fuzz. I'll dig some more and probably will close the issue. 

btw 
> where?

I think it was this, https://github.com/etcd-io/jetcd/pull/447 but I guess this is some "tools" dependency.

**Comment by yaskoo** [comment]
yup, the problem was on my side, sorry for the trouble.
