### ISSUE TITLE
jetcd support etcd version limit

### ISSUE THREAD

**Issue by LinLshare** [etcd-io/jetcd#456]
Could anyone tell me jetcd support etcd version limit ?
I use etcd version v3.3.8, and use jetcd v0.0.2, connect failed

**Comment by hexfusion** [comment]
> Could anyone tell me jetcd support etcd version limit ?I use etcd version v3.3.8, and use jetcd v0.0.2, connect failed

@LinLshare to be clear this same code worked with an older version of etcd? If yes what version?

**Comment by LinLshare** [comment]
@hexfusion I have no idea, I try to lower the etcd version to 3.3.3, but still the problem, I just use the sample code below

```java
      // create client
      Client client = Client.builder().endpoints("http://localhost:2379").build();
      KV kvClient = client.getKVClient();

      ByteSequence key = ByteSequence.fromString("/test/testkey");
      ByteSequence value = ByteSequence.fromString("test_value");

      // put the key-value
      kvClient.put(key, value).get();
```

then I use `docker exec -it etcd3.3.3 /bin/sh` connect to etcd, and type `etcdctl ls -r`
but found nothing with key `/test/testkey`.

**Comment by hexfusion** [comment]
> then I use docker exec -it etcd3.3.3 /bin/sh connect to etcd, and type etcdctl ls -r
but found nothing with key /test/testkey.

@LinLshare the client writes to the v3 store you are checking v2 with `etcdctl ls`

try

 `ETCDCTL_API=3 etcdctl get --prefix=true ""` to list all keys

**Comment by LinLshare** [comment]
@hexfusion It works, thank you so much !!!
