### ISSUE TITLE
"com.beust.jcommander.ParameterException" is caught while running io.etcd.jetcd.examples.jetcdctl.Main

### ISSUE THREAD

**Issue by MalcolmSanders** [etcd-io/jetcd#460]
https://github.com/etcd-io/jetcd/blob/34864cd0b2fc0376b6e1f8c8b9f1b40903c5206e/jetcd-examples/jetcd-simple-ctl/src/main/java/io/etcd/jetcd/examples/jetcdctl/CommandGet.java#L36

When I runs this example - io.etcd.jetcd.examples.jetcdctl.Main, I catch the following exception:
-----------------------------------------------------------------------------------------------
```
Exception in thread "main" com.beust.jcommander.ParameterException: Cannot use final field io.etcd.jetcd.examples.jetcdctl.CommandGet#key as a parameter; compile-time constant inlining may hide new values written to it.
	at com.beust.jcommander.Parameterized.setFieldAccessible(Parameterized.java:241)
	at com.beust.jcommander.Parameterized.<init>(Parameterized.java:38)
	at com.beust.jcommander.Parameterized.parseArg(Parameterized.java:115)
	at com.beust.jcommander.JCommander.addDescription(JCommander.java:594)
	at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:587)
	at com.beust.jcommander.JCommander.addCommand(JCommander.java:1533)
	at com.beust.jcommander.JCommander$Builder.addCommand(JCommander.java:1189)
	at io.etcd.jetcd.examples.jetcdctl.Main.main(Main.java:42)
```
-----------------------------------------------------------------------------------------------

I found the reason is that two member variables "key" and "rev" of class io.etcd.jetcd.examples.jetcdctl.CommandGet should not be set "final" otherwise JCommander could not set such variables.

**Comment by lburgazzoli** [comment]
@MalcolmSanders do you mind sending a PR to fix it ?

**Comment by MalcolmSanders** [comment]
Sorry to reply late. This is not my working email, so I don't check
frequently.

Previously I'm working on using jetcd to achieve leadership election for
high availability service.
According to current jetcd APIs, I'm trying to composite APIs such as
"lease", "lock", "KV" and "watch" to fulfill my target.
Considering various scenarios such as network disconnection and retry
policy, I find it takes efforts to make it work robust.
I don't know whether you have the plan to provide leadership election
functionality just like class LeaderLatch in curator for zookeeper.
If so, I'm very much looking forward to it.

At last, thanks for your reply.

Luca Burgazzoli <notifications@github.com> 于2018年12月12日周三 下午7:01写道：

**Comment by lburgazzoli** [comment]
Yes we do have plans but at the moment we are quite busy on other topics so I can't promise an ETA

**Comment by MalcolmSanders** [comment]
Got it. No hurry. Current API works for me.
BTW, do you have any design for it ? Maybe I can contribute for the project
since I'm working on flink which is also an open source project.

Luca Burgazzoli <notifications@github.com> 于2018年12月13日周四 下午8:39写道：

**Comment by lburgazzoli** [comment]
No but we can have a look at what the go client does to have a rough idea

**Comment by MalcolmSanders** [comment]
Thanks. I will work out a design doc on leadership election in a couple of
days (maybe next week), do you mind reviewing it or giving any suggestions ?

Luca Burgazzoli <notifications@github.com> 于2018年12月13日周四 下午9:07写道：

**Comment by lburgazzoli** [comment]
not at all :)

**Comment by MalcolmSanders** [comment]
Thanks :)

Luca Burgazzoli <notifications@github.com> 于2018年12月13日周四 下午9:16写道：
