### ISSUE TITLE
Client support for etcd dynamic cluster membership reconfiguration

### ISSUE THREAD

**Issue by rcillo** [etcd-io/jetcd#464]
When running etcd server on the cloud (AWS, for example), as instances get terminated new instances with different IP addresses are launched to replace them. With time, an etcd cluster that used to be reachable through a set of IP addresses, will have a totally different set of addresses.

In order for the client to be able to keep connected and working with an ever changing set of cluster IP addresses, somethings are required. It seems that this client already has some of them. It already supports the configuration of both `URIResolver` and `LoadBalancer` which are essential for properly discovering all the nodes of a cluster but also implementing fallback strategies, as described in etcd client architecture docs https://etcd.readthedocs.io/en/latest/client-architecture.html#client-architecture

Nevertheless, I was not able to achieve the behaviour described in such architecture docs. The problems are the following:

1. once an etcd host goes down, the client does not fallback to another host
2. when a new host is added, it's not automatically added in the channel

How do you think would be the correct way to achieve 1 and 2?

Ideally it would be possible to "fix" a channel by managing connections to hosts, adding and removing connections.

**Comment by rcillo** [comment]
@lburgazzoli yes, I do have time and I'm willing to implement this. But I need some guidance since I'm gRPC is fairly new to me, I don't know exactly where I should implement the solution.

I thought to start by investigating if gRPC channels can somehow establish connections to new hosts dynamically or if I would have to create a completely new channel. A second question I could not answer is, is there any feature in the channel that allow me to do some "introspection" and look at the state of connections, in order to mark then as "unrecoverable". After that is answered, I need to think about making this solution optional, since not all developer care about it and I don't want to complicate things for everyone.

**Comment by lburgazzoli** [comment]
I think the best would be to look at the go implementation and see what they come up with and see if it is applicable to grpc-java too.

**Comment by vorburger** [comment]
One way to achieve this kind of thing, from a higher level architectural point of view, is to not bake this into code but use an external proxy which does; this is pretty much the "sweet spot" which the hyped "service mesh" infrastructure was created for... check out [Envoy](https://www.envoyproxy.io/) (and may be [Istio](https://istio.io/)).

**Comment by rcillo** [comment]
@vorburger in this case specifically, the DNS is resolved only once https://github.com/etcd-io/jetcd/blob/c734d207693e5286905bde8217b9882949610edd/jetcd-resolver/src/main/java/io/etcd/jetcd/resolver/DirectUriResolver.java#L77 which means that even if we pointed the service to some proxy, this proxy would have to have static IP address. So, the solution would boil down to having static IP addresses, regardless of proxy or not, something I already tried in the past with Zookeeper https://jobs.zalando.com/tech/blog/rock-solid-kafka/

I'm experimenting with go etcd as @lburgazzoli suggested. I imagine that if we can build it, then the benefit for the community would be huge. Not having to deploy and maintain additional proxies, having a nice resilient client out of the box, leveraging the HA from the server.

**Comment by lburgazzoli** [comment]
> @vorburger in this case specifically, the DNS is resolved only once
> 
> [jetcd/jetcd-resolver/src/main/java/io/etcd/jetcd/resolver/DirectUriResolver.java](https://github.com/etcd-io/jetcd/blob/c734d207693e5286905bde8217b9882949610edd/jetcd-resolver/src/main/java/io/etcd/jetcd/resolver/DirectUriResolver.java#L77)
> 
> Line 77 in [c734d20](/etcd-io/jetcd/commit/c734d207693e5286905bde8217b9882949610edd)
>  u -> Collections.singletonList(new InetSocketAddress(uri.getHost(), uri.getPort())) 
> which means that even if we pointed the service to some proxy, this proxy would have to have static IP address. So, the solution would boil down to having static IP addresses, regardless of proxy or not, something I already tried in the past with Zookeeper https://jobs.zalando.com/tech/blog/rock-solid-kafka/
> 

I think that cache can be removed, don't remember why it was there or at leas there should be a way to invalidate it.

> I'm experimenting with go etcd as @lburgazzoli suggested. I imagine that if we can build it, then the benefit for the community would be huge. Not having to deploy and maintain additional proxies, having a nice resilient client out of the box, leveraging the HA from the server.

**Comment by rcillo** [comment]
In fact, it's already possible to achieve the behaviour I described.

```
final String[] etcdEndpoints = {"srv://_etcd-client._tcp.example.com"};
Client.builder().endpoints(etcdEndpoints)
                .uriResolverLoader(() -> {
                    final Collection<URIResolver> resolvers = new ArrayList<>();
                    resolvers.add(new DnsSrvUriResolver());
                    return resolvers;
                })
                .loadBalancerFactory(Objects.requireNonNull(LoadBalancerRegistry.getDefaultRegistry()
                        .getProvider("round_robin")))
                .build()
```

The load balancer is optional. There is a listener in the resolver which gets called by the channel  in case of some events. The resolver then can `refresh` the list of nodes so that connectivity is not lost in case of replacing all etcd server IPs.

Do you think it would be fine to remove the cache from `DirectUriResolver`? So that even if someone is not using DNS SRV, they can still get a similar behavior and avoid running into this issue.

**Comment by lburgazzoli** [comment]
> In fact, it's already possible to achieve the behaviour I described.
> 
> ```java
> final String[] etcdEndpoints = {"srv://_etcd-client._tcp.example.com"};
> Client.builder().endpoints(etcdEndpoints)
>   .uriResolverLoader(() -> {
>     final Collection<URIResolver> resolvers = new ArrayList<>();
>     resolvers.add(new DnsSrvUriResolver());
>     return resolvers;
>   })
>   .loadBalancerFactory(Objects.requireNonNull(LoadBalancerRegistry.getDefaultRegistry()
>   .getProvider("round_robin")))
>   .build()
> ```
> 
> The load balancer is optional. There is a listener in the resolver which gets called by the channel in case of some events. The resolver then can `refresh` the list of nodes so that connectivity is not lost in case of replacing all etcd server IPs.
> 

I think you can omit the `uriResolverLoader` 

> Do you think it would be fine to remove the cache from `DirectUriResolver`? So that even if someone is not using DNS SRV, they can still get a similar behavior and avoid running into this issue.

I think the best would be to have an option to enable/disable the cache, maybe we can have the cache off by default.

But you could also add an additional resolver that - if enabled - get the lists of endpoints from etcd

**Comment by rcillo** [comment]
I think there are already enough options. I think that the fact that we discussed this issue here already has some value so that people can find it and use it. I'll close this by now. Thank you for the attention.

**Comment by User979269852** [comment]
> In fact, it's already possible to achieve the behaviour I described.
> 
> ```java
> final String[] etcdEndpoints = {"srv://_etcd-client._tcp.example.com"};
> Client.builder().endpoints(etcdEndpoints)
>   .uriResolverLoader(() -> {
>     final Collection<URIResolver> resolvers = new ArrayList<>();
>     resolvers.add(new DnsSrvUriResolver());
>     return resolvers;
>   })
>   .loadBalancerFactory(Objects.requireNonNull(LoadBalancerRegistry.getDefaultRegistry()
>   .getProvider("round_robin")))
>   .build()
> ```
> 
> The load balancer is optional. There is a listener in the resolver which gets called by the channel in case of some events. The resolver then can `refresh` the list of nodes so that connectivity is not lost in case of replacing all etcd server IPs.
> 
> Do you think it would be fine to remove the cache from `DirectUriResolver`? So that even if someone is not using DNS SRV, they can still get a similar behavior and avoid running into this issue.

Can you tell me where I can get the function "LoadBalancerRegistry.getDefaultRegistry()"

**Comment by rcillo** [comment]
@User979269852 I think this is part of grpc-core. I have a line like this in my project `import io.grpc.LoadBalancerRegistry;`

**Comment by luomengY** [comment]
Whether jetcd supports that after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endpoints.

**Comment by luomengY** [comment]
https://github.com/etcd-io/jetcd/issues/464#issuecomment-476443244

is this way support after adding nodes, the client can automatically sense the new nodes and add the new node IP to the endpoints? has  jetcd good eay now?

**Comment by luomengY** [comment]
> @User979269852 I think this is part of grpc-core. I have a line like this in my project `import io.grpc.LoadBalancerRegistry;`

How is the "DnsSrvUriResolver" defined? Is there any specific implementation code?
