### ISSUE TITLE
Support namespace in jetcd

### ISSUE THREAD

**Issue by MalcolmSanders** [etcd-io/jetcd#472]
Previously client API in golang has already supported [namespace](https://godoc.org/github.com/coreos/etcd/clientv3/namespace), it'll be quite useful if jetcd also support namespace since it's error-prone to concatenate a namespace prefix with each key before KV/Lock/Watch operations.

**Comment by lburgazzoli** [comment]
I'm fine with that, do you have any room to contribute ?

**Comment by MalcolmSanders** [comment]
Yes, and thanks for the invitation. I'll create the PR in this week.

**Comment by MalcolmSanders** [comment]
@lburgazzoli Sorry for the delay. The patch for jetcd namespace is ready for reviewing.
