### ISSUE TITLE
Propose a utility API for a sequencer API

### ISSUE THREAD

**Issue by MalcolmSanders** [etcd-io/jetcd#473]
In our user cases, we need to use etcd to share an integer and concurrently increase it on demand. While it could be achieved by transactions without too many codes, I thought it might be useful for some users. So just a proposal.

**Comment by lburgazzoli** [comment]
Can you elaborate this a little bit more ? some example would help

**Comment by MalcolmSanders** [comment]
The initial idea of this proposal comes from curator [SharedCount](https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedCount.java) for zookeeper which manages a shared integer. All clients watching the same path will have the up-to-date value of the shared integer.

While our user case is simpler, we only need to make sure that multiple client can atomically increase the shared integer and don't need watchers. 

I thought shared integer utility APIs or its somewhat simplified version might be useful for some user scenarios.

**Comment by lburgazzoli** [comment]
I'm fine with that, do you mind sending a PR ? I think this kind of utilities deserve a dedicate module, such as jetcd-receipes / jetcd-extensions, what do you think ?

**Comment by xiang90** [comment]
@lburgazzoli 

in the go client, we have a concurrency package to put extensions: https://github.com/etcd-io/etcd/tree/master/clientv3/concurrency

**Comment by MalcolmSanders** [comment]
@lburgazzoli 
I agree, such a module is a set of APIs of higher level than previous APIs such as lease, KV and lock. And higher level APIs such as session, election could be part of it.

**Comment by lburgazzoli** [comment]
I've created an jetcd-extesions module for which the base package is io.etcd.jetcd.extensions, feel free to send a PR

**Comment by lburgazzoli** [comment]
@MalcolmSanders have you had any time to work on this ?

**Comment by MalcolmSanders** [comment]
> @MalcolmSanders have you had any time to work on this ?

Sorry, I've been occupied in some urgent things last month.
Previously I haven't had time on this issue, but I'm working on #472 since this week and accomplish dev coding yesterday and I'm going to create a RP on #472 this week.

**Comment by fanminshi** [comment]
@MalcolmSanders  This is a good idea. I would like jetcd to have more high level APIs.

**Comment by MalcolmSanders** [comment]
> @MalcolmSanders This is a good idea. I would like jetcd to have more high level APIs.

Thanks. I'll work on it and several other utilities including LeaderLatch which is similar to what in Curator, so that it will be easier to migrate from zookeeper to etcd.

**Comment by fanminshi** [comment]
@MalcolmSanders Cool, I have a similar goal for jetcd too. To make it a replacement for curator such that java people can use etcd as an alternative to zookeeper. Anyways, I am curious about your use-case to use etcd.

**Comment by MalcolmSanders** [comment]
@fanminshi  Our user cases are listed in this[ design doc](https://docs.google.com/document/d/12-gIZDuT4IOWG7gmwSqNFsOHuGlkdRHge0ahJ7M311Y/edit#heading=h.sqkj9zjvgicu). Please feel free to relay your comments or suggestions~

**Comment by fanminshi** [comment]
@MalcolmSanders cool, will take a look.
