### ISSUE TITLE
Error:(19, 25) java: package io.etcd.jetcd.api does not exist

### ISSUE THREAD

**Issue by pdgetrf** [etcd-io/jetcd#478]
Seeing this error from intellij

![image](https://user-images.githubusercontent.com/252020/50715734-6f686580-1033-11e9-8d41-1b2b95c7750c.png)

Although command line build with "./mvnw clean package -Dmaven.test.skip=true" works fine!

**Comment by lburgazzoli** [comment]
you need to set the folder in which the maven protobuf plugin generates the java code from protobuf as sn itellij source folder

**Comment by pdgetrf** [comment]
please add this to a doc somewhere unless I miss it already

**Comment by vorburger** [comment]
>
> please add this to a doc somewhere unless I miss it already
>
A warm welcome to the wonderful collaborative world of open source! YOU can
help out and contribute to this project by raising a Pull Request which
proposes a clarification in doc like a README... ;-)
