### ISSUE TITLE
KubeCon / Cloud Native Con Europe 2019 (Barcelona May 20–23) Panel to meet-up

### ISSUE THREAD

**Issue by vorburger** [etcd-io/jetcd#483]
Are any of you watching this repo planning to be at [KubeCon / Cloud Native Con Europe 2019 in Barcelona, Spain from May 20–23](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/) ? 

I'm asking because it occurred to me that I could [Submit a Proposal for a Panel](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/cfp/), something general like _Present & Future of jetcd, the Java client for etcd, the distributed reliable key-value store_ as an opportunity for people interested in this project to have a chance to meet up and get to know each other face to face, learn about what we are each doing with jetcd, perhaps discuss future ideas / requirements / requests, and encourage new contributors.

Added bonus: If the proposal is accepted, then up to 5 people participating in such a panel would get a free KubeCon / Cloud Native Con entry pass! You (your employer) would still have to pay for travel and accommodation, of course. Please reply here in the next 48 hours if this is of interest to you (CFP is closing very soon) ...

/Cc @lburgazzoli @fanminshi @philips

**Comment by fanminshi** [comment]
I am interested

**Comment by vorburger** [comment]
> I am interested

Would love to add you; could you please ASAP send me a private email at my GitHub UID `@redhat.com` with your:
* Company
* Title
* Email
* Twitter Handle 
* Other Social (i.e. LinkedIn)
* Biography (provide a biography that includes employer (if any), ongoing projects and previous speaking experience)
* Country of Residence
* Has Speaker spoken at any KubeCon + CloudNativeCon conferences before?
* What gender does Speaker identify with?
* If accepted, will you, or any speaker(s) listed above, require travel support?

**Comment by vorburger** [comment]
@gyuho @hexfusion in case you are planning to be at 
KubeCon / Cloud Native Con Europe 2019 (Barcelona May 20–23), would you be interested in being added to a panel about jetcd?

**Comment by gyuho** [comment]
@vorburger Yes, I will be interested!

**Comment by gyuho** [comment]
@vorburger Just emailed you. Thank you.

**Comment by vorburger** [comment]
Cool; I've just submitted a Panel proposal for including @lburgazzoli @fanminshi @gyuho @vorburger.

I'll try to remember to update this issue on:

* CFP Notifications: March 5, 2019
* Schedule Announced: March 7, 2019

**Comment by vorburger** [comment]
Hello everyone, FYI I just got the following:

> I am writing to notify you that your submission for KubeCon + CloudNativeCon Europe, Panel about the Present & Future of the etcd Java client library (jetcd), has regrettably not been accepted due to the overwhelming number of submissions we received for the event. The decisions made by the co-chairs have been difficult, however, we greatly appreciate the time you invested drafting your submission.
