### ISSUE TITLE
Jetcd framework is not scalable

### ISSUE THREAD

**Issue by zonghaishang** [etcd-io/jetcd#488]
I want to implement custom dns parsing and use my own factory object `NameResolver.Factory`，
But I found that the jetcd code does not allow users to extend.

`io.etcd.jetcd.ClientConnectionManager#defaultChannelBuilder`：

```java
  protected ManagedChannelBuilder<?> defaultChannelBuilder() {
    final NettyChannelBuilder channelBuilder = NettyChannelBuilder.forTarget("etcd");

    //...

    channelBuilder.nameResolverFactory(
        //  #1 Why is the use of SmartNameResolverFactory mandatory?
        forEndpoints(
          Util.supplyIfNull(builder.authority(), () -> "etcd"),
          builder.endpoints(),
          Util.supplyIfNull(builder.uriResolverLoader(), URIResolverLoader::defaultLoader)
        )
    );

    //...

    return channelBuilder;
  }
```
Because `SmartNameResolverFactory` is responsible for creating the `SmartNameResolver` object, it forces the use of `DirectUriResolver` as a parser in the constructor, which prevents the user from extending the parsing implementation.

I think `nameResolverFactory` should be designed to be extensible to developers.

**Comment by vorburger** [comment]
@zonghaishang if you would like to make a contribution (PR) to this project, we would be happy to review it!

**Comment by lburgazzoli** [comment]
that's not correct.

we do not expose NameResolver.Factory but we have an URIResolver interface you can implement (as references about how to do it, you can have a look at the https://github.com/etcd-io/jetcd/tree/master/jetcd-resolver-dns-srv).

If you then want to restrict resolver lookup, you can provide your own  resolver loader that return a static list of resolvewrs.

**Comment by lburgazzoli** [comment]
> @lburgazzoli
> I understand your idea, I am doing local dns lookup now, not relying on etcd server.
> 
> ```java
> protected ManagedChannelBuilder<?> defaultChannelBuilder() {
>   //  #1 Support extension
>   final NettyChannelBuilder channelBuilder =
>           NettyChannelBuilder.forTarget(Util.supplyIfNull(builder.authority(), () -> "etcd"));
>   //...
> 
>   channelBuilder.nameResolverFactory(
>       forEndpoints(
>               Util.supplyIfNull(builder.authority(), () -> "etcd"),
>         builder.endpoints(),
>               Util.supplyIfNull(builder.uriResolverLoader(), URIResolverLoader::defaultLoader)
>       )
>   );
> ```
> 
> I found that custom extensions must modify the source code, which is less friendly.
> `#1` code modification is a change made by the client to support dns (no need for etcd cluster configuration). Of course, I have implemented `DnsUriResolver` and `DnsSmartNameResolver` myself.
> 

I do not understand what you mean here, you do not need to modify jetcd code but provide your implementation and configure the builder. It is not so different from providing a custom  NameResolver.Factory.

> Of course, I will start a pr at the latest before the end of next week. @vorburger
> 
> I know that the current change is not the best way, next week will launch pr to solve this problem, providing better scalability. :-)

**Comment by lburgazzoli** [comment]
outdated
