### ISSUE TITLE
SSL configuration guide

### ISSUE THREAD

**Issue by herbalizer404** [etcd-io/jetcd#492]
Hi,
We dont success to use our etcd TLS server with jetcd.
To connect with curl or etcdctl, we provide these 3 files and it works well:
etcd-client-ca.cert
etcd-client.crt
etcd-client.key
How to provide exactly these 3 files to jetcd to work in the configuration?

Thank you

**Comment by herbalizer404** [comment]
Hi,
We found a way to success, here is our config:
```
ClientBuilder clientBuilder = Client.builder( ).endpoints(ep);
        clientBuilder = clientBuilder.maxInboundMessageSize(max);
              clientBuilder.authority(auth);
           SslContext sslContext = GrpcSslContexts.forClient()
                 .trustManager(caFile)
                 .keyManager(certFile, keyFile)
                 .build();
           clientBuilder = clientBuilder.sslContext(sslContext);
     client = clientBuilder.build();
```
Note that the value of authority must be the url of the server "etcd.example.com"

**Comment by vorburger** [comment]
@herbalizer404 cool. Perhaps you'd like to submit a PR to add this as doc to the README?

**Comment by liurongwei** [comment]
> SslContext sslContext = GrpcSslContexts.forClient()
>                  .trustManager(caFile)
>                  .keyManager(certFile, keyFile)
>                  .build();

IllegalArgumentException: ALPN must be enabled and list HTTP/2 as a supported protocol

use the code I got a exception like above , did you have the same problem ?

**Comment by nsirohi-ps** [comment]
@herbalizer404 , what exactly do you mean be the url of the server? the fqdn?

**Comment by enataraj** [comment]
> > SslContext sslContext = GrpcSslContexts.forClient()
> > .trustManager(caFile)
> > .keyManager(certFile, keyFile)
> > .build();
> 
> IllegalArgumentException: ALPN must be enabled and list HTTP/2 as a supported protocol
> 
> use the code I got a exception like above , did you have the same problem ?

What is the resolution for this? Likely I am running into this.
