### ISSUE TITLE
Can I connect behind a proxy server?

### ISSUE THREAD

**Issue by gcalvojp** [etcd-io/jetcd#510]
I am using `io.etcd.jetcd.ClientBuilder` to build my etcd client, but I don't know how can I specify an HTTP proxy that needs to be used to access the endpoints.

```java
        Client client = Client.builder()
            .endpoints("foo", "bar", "foobar")
            //.proxy(proxy) ???
            .build();
        KV kvClient = client.getKVClient();
        ...
```

Is there an easy way to do that?

**Comment by fanminshi** [comment]
@gcalvojp  can you elaborate your use-case a bit more. I don't understand what's this HTTP proxy that you are talking about.

**Comment by gcalvojp** [comment]
My use case is an etcd client which is in a different network space than the etcd server (direct access is not possible). However, the client can access another host (an HTTP proxy) which can directly reach the etcd server.

Assuming that communication between etcd client and etcd server goes over HTTP, how can I make the client connect to the server through the HTTP proxy?

The idea is that the HTTP proxy will forward client requests to the etcd server and then return the responses to the client. I know I can make requests to the etcd server by simply using cURL, so I think this solution should be possible; but so far I haven't found a way to specify an HTTP proxy when I create the client.

Thanks for your help.

**Comment by fanminshi** [comment]
@gcalvojp have you tried to connect the proxy addr from jetcd directly? e.g use the proxy endpoint when constructing the jetcd client? `client.builder().endpoints("proxy.endpoint")...`

**Comment by gcalvojp** [comment]
Yes, I've tried that but it doesn't work. The proxy host does not act as a *tunnel*; it does not blindly do port forwarding. It is a regular HTTP proxy; it forwards HTTP requests to the appropriate host, that's all.

If I can [set the value of a key](https://coreos.com/etcd/docs/latest/v2/api.html#key-space-operations) by simply doing an HTTP request to the etcd server:

```bash
curl http://my-server:2379/v2/keys/message -XPUT -d value="Hello world"
```

Then it should be possible to have an HTTP proxy sitting between the client and the server.
