### ISSUE TITLE
Migrate to JUnit5

### ISSUE THREAD

**Issue by yb172** [etcd-io/jetcd#545]
Update all tests to use JUnit5 instead of JUnit4 based on discussion in #506.

At least two things would have to be done:
 * Remove dependency on junit4 and move all tests to junit5
 * Refactor [EtcdClusterResource](https://github.com/etcd-io/jetcd/blob/8314aafbd1833b1b10960fccba6f240608111397/jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/junit/EtcdClusterResource.java) to be JUnit5 extension instead of JUnit4 `ExternalResource`

**Comment by yb172** [comment]
@fanminshi @lburgazzoli I've migrated tests to JUnit5 in https://github.com/etcd-io/jetcd/pull/547

A few notes:
 * Moving `@BeforeClass`, `@AfterClass`, `@Before` and `@After`, and `@Test` was trivial
 * Moving to `@ParametrizedTest` was not very trivial but ok. Code seem to be a [bit more concise](https://github.com/etcd-io/jetcd/pull/547/files#diff-013647774aa78a78b529067f19bbdc58R51).
 * There are not many examples on JUnit5. It took a while to figure out how to wire [`EtcdClusterExtension`](https://github.com/etcd-io/jetcd/pull/547/files#diff-32db6da40a7564e3b9bda37fa8289dfcR18) to a [field](https://github.com/etcd-io/jetcd/pull/547/files#diff-013647774aa78a78b529067f19bbdc58R52). Had to look at third-party extensions source.
 * [Extensions state](https://junit.org/junit5/docs/current/user-guide/#extensions-keeping-state) is very confusing. [Some articles are saying that extension must be stateless](https://blog.codefx.org/design/architecture/junit-5-extension-model/#Stateless) so it's not clear if provided way of doing `EtcdClusterExtension` is correct. It looks ok, but it's not clear if that's the case. And code to work with extension `store` is [super cumbersome](https://github.com/JensPiegsa/wiremock-extension/blob/master/src/main/java/com/github/jenspiegsa/wiremockextension/WireMockExtension.java#L175).
 * There is no support for proper test-level timeouts ([feature request](https://github.com/junit-team/junit5/issues/80) was opened in 2015 and is still open) which results in `assertTimeoutPreemptively` for every test: https://github.com/etcd-io/jetcd/pull/547/files#diff-1f8fc953ba87e8787c95a7605b2d7796R85. And `assertTimeoutPreemptively` [could result in side-effects](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions).
 * [Some tests](https://github.com/etcd-io/jetcd/pull/547/files#diff-1f8fc953ba87e8787c95a7605b2d7796R59) have external `@Rule`s so we can't completely move to JUnit5 and have to use `@EnableRuleMigrationSupport` which is [experimental](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-rule-support). And it doesn't look that `GrpcServerRule` would be [migrated to extension in nearest future](https://github.com/grpc/grpc-java/issues/5331#issuecomment-461552284).

Given absence of global timeout support and that we would have to keep junit dependency anyway to support `@Rule` I'm not sure if https://github.com/etcd-io/jetcd/pull/547 should be merged.

What do you think?

**Comment by dbyron0** [comment]
This is a long shot, but by any chance would @marcphillipp mind taking a look at this and help point us in the right direction?  You've been super helpful with junit info elsewhere (e.g. in the gradle repo) so I figured I'd give it a whirl here too.  Thanks much.

**Comment by fanminshi** [comment]
`Some tests have external @Rules so we can't completely move to JUnit5 and have to use @EnableRuleMigrationSupport which is experimental. And it doesn't look that GrpcServerRule would be migrated to extension in nearest future.`

I wrote the those unit tests way before we had the test-container capability. I think in the future, we can just write integration tests. I don't see too much utility of writing unit tests beside using a stub grpc server to return specific errors. I think those can be removed.

`There is no support for proper test-level timeout`
That't a good finding! I don't like the `assertTimeoutPreemptively` to be added in every test. it is too verbose.  Is it possible to use the junit4 timeout `rule` within a  junit5 test? Alternatively, we don't require timeout for each test. We can configure a global suite timeout at travis level. By default, any job doesn't finish within 50 minutes will be killed. ref: https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts and we can configure those timeout seen from https://stackoverflow.com/questions/29836823/how-to-increase-timeout-in-travis-ci-for-my-selenium-tests-written-on-java.

Overall, our integration tests should complete in a reasonable time. I can see the test level timeout in debugging hanging tests. However, I don't think that's a strict requirement. I think it is fine we can remove the restriction on test timeout for now until junit5 add those feature. Then we can revisit this problem.

**Comment by marcphilipp** [comment]
> Extensions state is very confusing. Some articles are saying that extension must be stateless...

It should be stateless because the same extension instance might be used concurrently when using parallel execution for different test methods or even classes (if the extension is registered globally). Thus, I'd recommend storing state in the store. There's a bit of a learning curve to it, let me know if you have questions. If we can improve the docs based on your feedback, that'd be great.

> There is no support for proper test-level timeouts

Test-level timeouts are on the agenda for JUnit 5.5.

@dbyron0 Please let me know how I can help. 🙂

**Comment by yb172** [comment]
@marcphilipp does it mean that [this implementation](https://github.com/etcd-io/jetcd/pull/547/files#diff-32db6da40a7564e3b9bda37fa8289dfcR39) is incorrect even if it's used with `@RegisterExtension` ([example](https://github.com/etcd-io/jetcd/pull/547/files#diff-2a2c9cd2e9015d6398f91c9d9da3063eR41))?

Thanks for letting us know about timeouts!

**Comment by marcphilipp** [comment]
It will work as long as you don't use `@Nested` classes.

**Comment by dbyron0** [comment]
Thank you @marcphilipp !

**Comment by lrozenblyum** [comment]
Hi @dbyron0, @marcphilipp.
Sorry for bring up a pretty old thread.
I'm facing a similar challenge in migrating from JUnit4 to JUnit5 in a private repository. 

We have a JUnit4 `@Rule` that provides an accessor to change its private field data during execution (the accessor was called from the test itself), so its proper work was based on the stateful behavior.

Now we're going to migrate it to an `Extension` and use it via `@RegisterExtension`.

So the question is: does this way of usage of an extension requires making it stateless?
The official JUnit5 doc doesn't seem mention it explicitly although some internet articles mention this requirement (like this one https://nipafx.dev/junit-5-extension-model/#Stateless).

The paragraph https://junit.org/junit5/docs/current/user-guide/#extensions-keeping-state mentions need to use the `ExtensionContext` but this doesn't seem a feasible option to use from the test itself.

Also it mentions `Usually, an extension is instantiated only once`. Is it some guarantee from the library? In this case, the state should be preserved and no problems about keeping something in the extension's fields?

Thanks in advance for clarifying this!

**Comment by marcphilipp** [comment]
It's still a good practice to manage state via `ExtensionContext` because that makes it more versatile. If you make it stateful, you should only use it via `@RegisterExtension` which instantiates it per test class.
