### ISSUE TITLE
Remove GrpcServerRule

### ISSUE THREAD

**Issue by yb172** [etcd-io/jetcd#549]
To fully migrate to JUnit5 `GrpcServerRule grpcServer` have to be removed from tests.

Two test classes are using it:
 * [`LeaseUnitTest`](https://github.com/etcd-io/jetcd/blob/8314aafbd1833b1b10960fccba6f240608111397/jetcd-core/src/test/java/io/etcd/jetcd/LeaseUnitTest.java)
 * [`WatchUnitTest`](https://github.com/etcd-io/jetcd/blob/8314aafbd1833b1b10960fccba6f240608111397/jetcd-core/src/test/java/io/etcd/jetcd/WatchUnitTest.java)

**Comment by lburgazzoli** [comment]
done
