### ISSUE TITLE
something confuse about watcher

### ISSUE THREAD

**Issue by Liubey** [etcd-io/jetcd#551]
there are some question,thanks a lot:
1.I have a three node cluster,and when I change a path,I receive more than 3 times notify???why,neen some ack when I process the notify?
2.I can't get the old value byevent.getPrevKV(),how?

my code just like this:
`                ByteSequence pathPrefix = ByteSequence.from(path,  RegisterConstants.DEFAULT_CHARSET_UTF8);
                WatchOption wo = WatchOption.newBuilder().withPrefix(pathPrefix)..withPrevKV(true).withProgressNotify(true).build();
                watcher = client.getWatchClient().watch(pathPrefix, wo, new Watch.Listener() {
                    @Override
                    public void onNext(io.etcd.jetcd.watch.WatchResponse response) {
                        if (!isConnected()) {
                            return;
                        } `

                        `if (listener != null) {
                            Iterator<WatchEvent> iterator = response.getEvents().iterator();
                            while (iterator.hasNext()) {
                                WatchEvent event = iterator.next();
                                String oldValue = event.getPrevKV().getValue().toString(RegisterConstants.DEFAULT_CHARSET_UTF8);
                                String newValue = event.getKeyValue().getValue().toString(RegisterConstants.DEFAULT_CHARSET_UTF8);
`

**Comment by fanminshi** [comment]
cc/ @lburgazzoli

**Comment by Liubey** [comment]
When I debug about that,I found that when New Event,the input maybe without prekv

**Comment by Macgrady4Ever** [comment]
I meet the same problem , when the last operation on the key is PUT, then watch-client onNext method always notify  put-event. when I delete this Key without other operation any more ,then watch-client onNext method always notify a DELETE event.
The other problem : After I build a watch-client by jetcd api, log print periodically:
err:io.etcd.jetcd.common.exception.EtcdException: Network closed for unknown reason
I tried to debug and find in the onError method invoke trace, but the Impl code which throw this
Exeption is an anonymous Impl. so I can`t find the cause accurately.
