### ISSUE TITLE
Implement Compare.CompareResult.NOT_EQUAL

### ISSUE THREAD

**Issue by devinrsmith** [etcd-io/jetcd#558]
It looks like Cmp.Op does not implement NOT_EQUAL, but NOT_EQUAL is in the proto specs.

**Comment by fanminshi** [comment]
yeah, that's right. if you can pull up a pr to fix that, that would be great! 
ref: https://github.com/etcd-io/etcd/blob/master/clientv3/compare.go#L40

**Comment by actien** [comment]
Hey, I fixed this issue in my PR but I couldn't get license headers to work so I closed it. Feel free to work it in if it's relevant, thanks.

**Comment by pengfeiwang-cn** [comment]
is there any one still working on jetcd? why such a issue exists?

**Comment by lburgazzoli** [comment]
1. yes there still someone working on this
2. because the PR never reached this repository

**Comment by pengfeiwang-cn** [comment]
"the PR never reached this repository" causes such an issue exists for such a long time? I can't believe it...

**Comment by lburgazzoli** [comment]
believe it or not maybe this was not a huge problem for those using jetcd.

would be nice if you could be a little bit more constructive, like help to fix this issue.

**Comment by pengfeiwang-cn** [comment]
I won't do anything if you jetcd guys so negative. 
you knew this issue before, right? if no one fix it, your a little bit more constructive way is just leave it as it is, right? then let it be what it is.

**Comment by lburgazzoli** [comment]
I’m sorry if you feel that we are negative and let me share some info:
- I’m working on this project on my spare and very limited time
- this issue, but that’s true for lit of other issue raised agains this project, have mot been updated by the reporter for long time which usually means that nor the reporter nor other user are impacted

that said, you started complaining about this issue being open for long time and I asked for help but it does not like you are willing to help so I may fix it if I’ll find time but the priority for me is low as it does not seem it is in huge request.

**Comment by pengfeiwang-cn** [comment]
Sorry to be so rough.
