### ISSUE TITLE
invalid prefix calculation

### ISSUE THREAD

**Issue by devinrsmith** [etcd-io/jetcd#561]
`OptionsUtil` is not correctly calculating the end range from a prefix. The condition `endKey[i] < 0xff` is *always* true. I've work up a simple PR w/ unit testing.

**Comment by fanminshi** [comment]
`the condition endKey[i] < 0xff is always true`? can you elaborate?
the code is based on the etcd implementation. see https://github.com/etcd-io/etcd/blob/master/clientv3/op.go#L369

**Comment by devinrsmith** [comment]
Sure - java implicit casting is tricky sometimes. In this case, the statement `endKey[i] < 0xff` is the same as `(int)endKey[i] < (int)256`. `byte`s have a range of -128 to 127, so that's why it always evals to true. You can check out the unit test against the old code, and verify that things seem to be broken.

**Comment by fanminshi** [comment]
@devinrsmith good point!
