### ISSUE TITLE
Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available

### ISSUE THREAD

**Issue by Koprvhdix** [etcd-io/jetcd#571]
I use jetcd-all with version 0.3.1-SNAPSHOT without any other dependencies. When I run `GrpcSslContexts.forClient()`, I got an `java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available` issue. What should I do to fix this bug? Is there any example about buildSslContext? thanks.

**Comment by 781545872** [comment]
hello,did you solve this problem?

**Comment by 781545872** [comment]
@Koprvhdix

**Comment by Koprvhdix** [comment]
Yes. You should use jetcd-core，then see https://github.com/grpc/grpc-java/blob/master/SECURITY.md

  <dependencies>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.20.Final</version> 
      <scope>runtime</scope>
    </dependency>
  </dependencies>
 
And use the correct version, the version is on the same page.

**Comment by 781545872** [comment]
Thanks so much.I have troubled by this problem for a long time.I am so glad to solve it.
