### ISSUE TITLE
Jetcd on android

### ISSUE THREAD

**Issue by p00h** [etcd-io/jetcd#580]
Hello!
It appears the grpc-netty is hardcoded at core, but grpc-netty does not have Android support according to grpc-java security guide. It should be replaced with grpc-okhttp.
Is there a chance to use jetcd on Android? Could anyone make it work?

**Comment by alanjuster** [comment]
ok   about what  you  say   is it means  in android  we can not use etcd    yes ?   i try gradle this module in my demo   but is does not work , jar modules  conflict ,then i  sove  jar conflict,  but there is no use , so what is your suggest

好吧你说的是它在android中意味着我们不能使用etcd是吗？ 我在我的演示中尝试gradle这个模块但是不起作用，jar模块冲突，然后我发现jar冲突，但是没有用，所以你的建议是什么

**Comment by lburgazzoli** [comment]
@p00h we have no plan to switch to grpc-okhttp at the moment, but you cna give a try an see if it works or not

**Comment by p00h** [comment]
@lburgazzoli I already did but with no luck. I've been trying to make it work for a week or so and decided to open an issue eventually.
