### ISSUE TITLE
Questions about KeyValue and TTL

### ISSUE THREAD

**Issue by kenttanl** [etcd-io/jetcd#581]
I need to iterate over the value of ETCD, but if I want to know the TTL of the key, I must first use `KeyValue.getLease()` and then continue to use `LeaseClient` to get it, so why not include the TTL attribute in KeyValue class? This will reduce the number of network requests, especially when traversing，like etcd4j.jar. Thanks and sorry my English

**Comment by lburgazzoli** [comment]
The tll attribute is not available from the API so we can't expose it
