### ISSUE TITLE
if   android  can use jetcd？

### ISSUE THREAD

**Issue by alanjuster** [etcd-io/jetcd#583]
if android can use it , Can the official give an example?  Thank u!

**Comment by lburgazzoli** [comment]
@alanjuster I never tested it on android but I do not have any time to test it/support so it would be nice if you can test it and eventually contribute fixed to make jetcd working on android

**Comment by alanjuster** [comment]
Thank  u  your answer  ,   i has do it ,it also can use in android, what we only need do is  add into gradle  then  use it  what we has used in java
