### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by devinrsmith** [etcd-io/jetcd#586]
Would it be possible to publish a new release to maven? I'm particularly looking forward to the testing improvements in jetcd-launcher when the container fails to start.

**Comment by lburgazzoli** [comment]
need to fix a number of issues the I can do a nw release

**Comment by itzg** [comment]
I would be interested in a new release in order to pick up https://github.com/etcd-io/jetcd/commit/d42722530d86579231905512c70fe3521532dcf3

**Comment by lburgazzoli** [comment]
working on it, hope this week

**Comment by lburgazzoli** [comment]
@devinrsmith @itzg  there is a new snapshot whit some changes related to watch and retry, would be awesome if you could test it so I can do a release soon

**Comment by itzg** [comment]
@lburgazzoli, I was able to confirm that the latest `0.3.1-SNAPSHOT` does indeed fix the issue I was encountering.

**Comment by style95** [comment]
I am also waiting for the next release.
Is there any update on this issue?

@itzg Could you guide me on how to use the snapshot version in the meantime?

**Comment by style95** [comment]
I could resolve the snapshot version with the following configuration.
Sharing just for those who want this.

**build.gradle**
```gradle
repositories {
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}
.
.
.
compile "io.etcd:jetcd-core:0.3.1-SNAPSHOT"
```

**Comment by lburgazzoli** [comment]
Version 0.4.1 has been released

**Comment by style95** [comment]
@lburgazzoli Thank you for the update.
Is the new version `0.4.1` or `0.3.1`?

**Comment by lburgazzoli** [comment]
0.4.1

**Comment by style95** [comment]
ok, then it seems it is about to be released in the maven repository as well.
Thank you for the confirmation.
