### ISSUE TITLE
Why not replace grpc-netty with grpc-netty-shaded?

### ISSUE THREAD

**Issue by riverlee2014** [etcd-io/jetcd#598]
Grpc has a shaded module "grpc-netty-shaded"to hide netty dependency in one jar.
If a project has two grpc dependencies version，the "grpc-netty-shaded" and "grpc-netty" will cause some trouble.

**Comment by lburgazzoli** [comment]
You need to fix your dependency tree as you may end-up with conflicts on grpc itself. eventually you can use jetcd-all that shadeds all the jetcd deps

**Comment by lburgazzoli** [comment]
btw, I do not see any grpc-netty-shaded in project's dependency list, @riverlee2014  can you please clarify ?

**Comment by riverlee2014** [comment]
This is my PR for reference:  #633 
According to the grpc official recommendation. Use of grpc-netty-shaded can shield many explicit netty library dependencies.

**Comment by lburgazzoli** [comment]
So looks like you are doing the opposite of what the issue was about, right ?

**Comment by riverlee2014** [comment]
No, I hope the jetcd to be like a stand-alone and mini component. 
In some scenarios, which user's project may depend on different versions of netty, if grpc-netty explicit import more netty component to user's project, it may be cause jar load conflicts. 
Any better suggestions?

**Comment by lburgazzoli** [comment]
Well the title of the issue is:

     Why not replace grpc-netty-shaded with grpc-netty?

which to me seems like you want to get rid of grpc-netty-shaded.

That said, we can do what you require but what about other dependencies ? if you want to have a dependency free jetc, there is jetcd-all which shades grpc too.

**Comment by riverlee2014** [comment]
Oh, I made a looooow mistake. Sorry!
![image](https://user-images.githubusercontent.com/7055799/64575719-ccc56b00-d3a7-11e9-8571-b361853edcd2.png)
```
<dependency>
	<groupId>io.etcd</groupId>
	<artifactId>jetcd-all</artifactId>
	<version>0.3.0</version>
</dependency>
```
It seems that jetcd-all shaded does not have a fully packaged dependency.

**Comment by lburgazzoli** [comment]
need to fix it

**Comment by lburgazzoli** [comment]
should be fixed by the latest snapshot

**Comment by JoeHegarty** [comment]
We ran into this issue and have tried the latest snapshot and it appears to be resolved.
Any ETA on a new release?

**Comment by lburgazzoli** [comment]
Version 0.4.1 has been released

**Comment by riverlee2014** [comment]
Waiting for you to push to the central maven repo.

**Comment by lburgazzoli** [comment]
Should be already there, https://repo1.maven.org/maven2/io/etcd/jetcd-all/0.4.1/ may take sopme time to appear on search.maven.org
