### ISSUE TITLE
jetcd gives java.lang.IncompatibleClassChangeError when working with JDK 11

### ISSUE THREAD

**Issue by dinoopt** [etcd-io/jetcd#612]
In my project, there is a requirement to upgrade to JDK 11.  We use jetcd to connect to the Etcd server. After recompiling the code with JDK 11  using jetcd 0.0.2 version jar, it is failing to connect to the Etcd server with the following error.
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Method 'com.coreos.jetcd.ClientBuilder com.coreos.jetcd.Client.builder()' must be InterfaceMethodref constant
```
From what I could see, starting JVM 9 onwards, the byte code has some strict checking which doesn't allow the calling of static methods within interfaces. Here are couple of references.
https://clojure.atlassian.net/browse/CLJ-2298
https://clojure.atlassian.net/browse/CLJ-2284

The code that fails in Jetcd does have a static method within the Client interface.

```
static ClientBuilder builder() {
    return new ClientBuilder();
  }
```

As I understand, Jetcd supports only JDK 8 as of now. Is there a version that is supported with JDK 11 ?  Will rebuilding the code with JDK 11 as the version help in this case ? Or would this require to change the static method all together ?

**Comment by lburgazzoli** [comment]
I never tested againts java 11 so it may require some changes, do you have any time to work a PR if needed ?

**Comment by lburgazzoli** [comment]
Any update ?
