### ISSUE TITLE
Put failed without any error message

### ISSUE THREAD

**Issue by guanyufen123** [etcd-io/jetcd#621]
`
  public static void put() {
        try {
            Client client = Client.builder().endpoints("http://127.0.0.1:2379").build();
            ByteSequence key2 = ByteSequence.from("test/4".getBytes());
            String v = "23456yu";
            ByteSequence value2 = ByteSequence.from(v.getBytes());
            CompletableFuture<PutResponse> response = client.getKVClient().put(key2, value2);
            System.out.println(response.isDone());
            client.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

`

**Comment by lburgazzoli** [comment]
What error should it throw ?
