### ISSUE TITLE
can't set up TLS, maybe because of incorrect authority

### ISSUE THREAD

**Issue by nsirohi-ps** [etcd-io/jetcd#624]
(I see that there's an open issue to add some documentation around this).

etcd version: 3.1.9
In the terminal:

ETCDCTL_API=3 etcdctl --endpoints=[https://localhost:2379] --cert {cert} --key {key} --cacert {cacert} get {} works just fine. 

In my code (Java 11, latest jetcd):

SslContext sslContext1 = GrpcSslContexts.forClient().trustManager(caCert).keyManager(pk1, certificate).build();
client = Client.builder()
                    .endpoints("https://localhost:2379")
                    .authority({dns of the machine})
                    .sslContext(sslContext1)
                    .build();

KV kvClient = client.getKVClient();
ByteSequence key = ByteSequence.from("test_key".getBytes());
ByteSequence value = ByteSequence.from("test_value".getBytes());

kvClient.put(key, value).get(); --> that fails with: 

"java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception"

What might I be doing wrong?

**Comment by lburgazzoli** [comment]
Yes that could be a reason, you need to set an authority that  matches you certificate.
