### ISSUE TITLE
java.security.cert.CertificateException: No name matching etcd found

### ISSUE THREAD

**Issue by ThorOrtinson** [etcd-io/jetcd#627]
I used the curl command on the machine where the etcd cluster is installed to carry the certificate request etcd server, which can be successful

 [root@10-8 etcd-v3.3.13]# curl --cacert /etc/ssl/ca.pem --cert /etc/ssl/client.pem  --key /etc/ssl/client-key.pem https://127.0.0.1:2389/v3beta/kv/put -X POST -d '{"key": "AA==", "value": "AA=="}'
{"header":{"cluster_id":"17685980671696090536","member_id":"6407630177957592132","revision":"40","raft_term":"1860"}}

 but when I tried to use the java code to carry the certificate to access the etcd service

 javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:629)
	at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextDat

 this is my code

      Client client = Client.builder().endpoints("https://etcd-server:2379")
                .sslContext(GrpcSslContexts.forClient().trustManager(ca)
                .keyManager(cert,certKey).build()).build();
        KV kvClient = client.getKVClient();

        ByteSequence key = ByteSequence.from("key".getBytes());
        ByteSequence value = ByteSequence.from("value".getBytes());
        
         PutResponse putResponse = kvClient.put(key, value).get();

**Comment by lburgazzoli** [comment]
By default, the jetcd client sets the authority to `jetcd`, you need to set it to the one that matches your certificate:

    client.authority("yourAuthority");
