### ISSUE TITLE
LeaseClient grant api caused thread leak

### ISSUE THREAD

**Issue by YJFinBJ** [etcd-io/jetcd#634]
If create client with default threadPool ,  that is `Executors.newCachedThreadPool()` in `ClientConnectionManager`, when using grant api with a ttl for a lease , It make a listenableFuture call in grpc stub, since no deadline or timeout set in, in java it will be a unlimited call util server response。In while, jetcd client make a listenableFuture type to  a
completableFuture  response ,but when to use listenableFuture f.get()，there still no timeout ,so if etcd server cannot response, it will infinite waiting for the listenableFuture call in grpc stub as mentioned before, and the thread for leaseClient.grant will be waiting indifinitely。 since it's a newCachedThreadPool, the threads in JVM will keep rising util the limit of kernel just make s thread leak.

So， why don't set a timeout in listenableFuture f.get() ,just as `targetFuture.complete(resultConvert.apply(f.get(long timeout, TimeUnit unit)))`when converte listenableFuture type to  completableFuture  response for waiting a future response ? 

Best regards

**Comment by lburgazzoli** [comment]
`get()` is invoked inside a listener which is triggered when the future is done so it should not block indefinitely, however we could set a configurable deadline in the gRPC invocation: would you like working on it ?

**Comment by YJFinBJ** [comment]
Hi~ lburgazzoli.If the future is not done all the time, then the get() will block indefinitely. I think there are two ways to fix it. One is configing the gRPC invocation a deadline, the other way is change the get() with get(timeout). In my individual, I think the latter is more simple and effective,since a deadline in grpc should do some change on stub and only some works on grpc server to make the deadline effective

**Comment by lburgazzoli** [comment]
I guess we need both, what to work on it ?
