### ISSUE TITLE
What's new in the tag 0.4.1 13 day ago？

### ISSUE THREAD

**Issue by hxwabc** [etcd-io/jetcd#653]
What's new in the tag 0.4.1 13 day ago？
I can't find detail infomation on the 'release' url.

**Comment by lburgazzoli** [comment]
What jetcd does is nothing more than implement this method:

    https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/NameResolver.java#L70

so the authority should match what you have in your certificates.

**Comment by lburgazzoli** [comment]
I do not have time to maintain a proper release note at the moment so any help would me more than welcome
