### ISSUE TITLE
Exclude grpc-protobuf-lite from dependencies

### ISSUE THREAD

**Issue by SButterfly** [etcd-io/jetcd#657]
Hello!
There is a classpact clash between:
```
com/google/protobuf/protobuf-java/3.6.1/protobuf-protobuf-java-3.6.1.jar
com/google/protobuf/protobuf-lite/3.0.1/protobuf-protobuf-lite-3.0.1.jar
Conflicted classes:
    com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream
    com.google.protobuf.AbstractMessageLite$Builder
    com.google.protobuf.AbstractMessageLite
    and 137 more
```

As suggested in https://github.com/grpc/grpc-java/issues/6332#issuecomment-545997451
Let's exclude io.grpc:grpc-protobuf-lite from dependencies

**Comment by lburgazzoli** [comment]
looks like it is not possible till the issue is solved on grpc-java side

**Comment by lburgazzoli** [comment]
looks like it is not possible till the issue is solved on grpc-java side

**Comment by sudoHackIn** [comment]
Looks like issue is no longer actual, because there is no longer com.google.protobuf:protobuf-lite in dependency tree, only
![protobuf-java](https://user-images.githubusercontent.com/9380854/146642484-e80e03fa-1498-4703-89dd-4986f0c7c0ba.png)
@SButterfly can you retest again?

**Comment by SButterfly** [comment]
Yes, thank you)
