### ISSUE TITLE
Using a proxy, the request is stuck and there is no exception

### ISSUE THREAD

**Issue by xieziqiang** [etcd-io/jetcd#661]
I have two ETCD clusters and a proxy server
First, the proxy server forwards traffic to the first cluster.
My application use jetcd, the endpoint is set to the proxy server ip, and now the requests is normal.
Then, I stopped the first cluster and the proxy server forwarded the traffic to the second cluster. At this time, the requests will get stuck, and there is no exception.
When I restart the application, the request is back to normal.
How can I solve this problem?  Thanks

**Comment by lburgazzoli** [comment]
can you provide a reproducer ?
