### ISSUE TITLE
How to convert the value of etcd into the bean object of Java

### ISSUE THREAD

**Issue by BoyHello** [etcd-io/jetcd#681]
How to convert the value of etcd into the bean object of Java？If the value of etcd obtained normally is serialized by protobuf, go can be deserialized normally. Is there a solution for Java deserialization

**Comment by lburgazzoli** [comment]
You are responsible to serialize and deserialize the value to a ByteSequence

**Comment by BoyHello** [comment]
The data put to etcd after I serialized it by myself can be deserialized normally. But the value obtained from etcd, deserialization exception. What should I do with the data fetched by etcd? Is there a serialization prefix?

**Comment by lburgazzoli** [comment]
I really don't get what you are trying to describe. 
you put ByteSequence and get ByteSequence, what you do with such values is out of jetcd control

**Comment by BoyHello** [comment]
Now I can get the value of bytesequence, but I can't convert it to a format similar to yaml file, so as to parse the data I want

**Comment by lburgazzoli** [comment]
Can you post an example ?

**Comment by BoyHello** [comment]
When I deserialize, I throw the following exception
