### ISSUE TITLE
Why no exception on Lease keepAliveOnce? while leaseId has time out

### ISSUE THREAD

**Issue by chenzhiguo** [etcd-io/jetcd#686]
The lease thread do logic by this:    
```java 
client.getLeaseClient().keepAliveOnce(leaseId).whenComplete((res, err) -> {
    if (err != null) {
       //DO something
    } else {
       // lease success!
    }
}
```    
I found that when the leaseId timed out and the value in etcd has disappeared, the exception(err) still did not occur!    
But if I call another method, an exception will be reported, such as:      
```java
client.getLeaseClient().revoke(leaseId).get();
```      
Exception message is:     
`Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: etcdserver: requested lease not found`

**Comment by chenzhiguo** [comment]
No problem?

**Comment by sukidesuka** [comment]
I encountered this issue with jetcd 0.7.6, but it was resolved when I rolled back to version 0.7.5.

**Comment by liangyuanpeng** [comment]
Provide any test or simple code and reproduce it? Thanks. @sukidesuka

**Comment by lburgazzoli** [comment]
can you create a reproducer ?
