### ISSUE TITLE
When is the next release scheduled?

### ISSUE THREAD

**Issue by ness2u** [etcd-io/jetcd#687]
There are a handful of bug-fixes and newly supported features that have been merged to the master-branch since the 0.3.0 release.
Notably, the 0.3.0 release has a bug where retries are blocking; which has been fixed, but not released.

When is the next release scheduled?

Is there another way that I can get the latest-greatest-stable release, including the changes added since October? (other than building it myself?)

**Comment by lburgazzoli** [comment]
jetcd 0.4.1 is available in maven central

**Comment by ness2u** [comment]
Fantatsic, so there are tagged versions... that gets me some of the changes I need.
Since 0.4.1 is from October, it won't include the changes I submitted back in November.

Is there another upcoming release scheduled?

**Comment by lburgazzoli** [comment]
I can make one beginning next week

**Comment by ness2u** [comment]
That would be greatly appreciated. 0.4.1 solves my biggest problem... 
and it would be great to get the other changes in when convenient.
Thank you.

**Comment by ness2u** [comment]
Any update on the next release?

**Comment by lburgazzoli** [comment]
working on it, sorry for the delay

**Comment by lburgazzoli** [comment]
0.5.0 has been released, should be available soon on maven central
