### ISSUE TITLE
ByteSequence API missing functionality

### ISSUE THREAD

**Issue by cfarinis** [etcd-io/jetcd#710]
Hello,

I need to perform operations with "prefixed" etcd keys, which are represented in jetcd as ByteSequence objects.
Specifically, I would like to be able to:

- Remove a prefix from a ByteSequence.
- Prepend a ByteSequence with a prefix.

The only performant way to achieve this with a ByteSequence is to get the underlying ByteString object and then use ByteString::substring / ByteString::concat.

However, the ByteSequence::getByteString method is not public.
So, I believe that the ByteSequence class should either expose its ByteString member variable, or be extended with more ByteString methods such as substring() and concat()

Thank you in advance,
Christos

**Comment by lburgazzoli** [comment]
I think it is better to have some additional methods can you list what you need or even better provide a PR ?
