### ISSUE TITLE
Question: How to perform a non-ranged get request?

### ISSUE THREAD

**Issue by alkismavridis** [etcd-io/jetcd#715]
I am using jetcd version 0.4.1 and etcd server 3.4.3.
All of the GET requests that I perform from jetcd expect a single (or possibly no) result.
So I am never interested in fetching ranges.

Still, I saw this in my etcd logs:
`2020-03-03 14:23:53.336256 W | etcdserver: read-only range request "key:\"AC.AT.ab234-beaa86-2345b3\" " with result "range_response_count:1 size:805" took too long`

So, I would like to ask two questions:

1. Should I care about range requests in the first place? Can this factor be detrimental to etcd performance? Or maybe should I search the cause of the warning elsewhere?

2. What is the proper way for jetcd to perform a single-result get request? Would a get option like this do the job?
`GetOption.newBuilder().withLimit(1).build()`

Thanks in advance!

**Comment by lburgazzoli** [comment]
For point 1, I think the best is to ask the etcd guys
For point 2, I think so, we do not set any limit at the moment but that can be changed or made configurable
