### ISSUE TITLE
The following error occurred while locking

### ISSUE THREAD

**Issue by baoyiquan** [etcd-io/jetcd#732]
HI,
The following error occurred while locking.

io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service v3lockpb.Lock
LockResponse rsp = client.getLockClient().lock(ByteSequence.from(lockName, UTF_8), leaseId).get();
please Do you know how to solve it?

**Comment by lburgazzoli** [comment]
Can you give more info ?

**Comment by lukasz-antoniak** [comment]
My guess is that a request hits old ETCD server, earlier than version 3.

**Comment by chuansuo12** [comment]
> My guess is that a request hits old ETCD server, earlier than version 3.

My ETCD cluster version is 3.4.7, but i also had this error.Is it necessary to specify the version when  the ETCD server starting?

**Comment by chuansuo12** [comment]
You should connect to port 2379, not 2380.The error would occur when i connect to 2380, but lease.grant was available.Please check your endpoints.
