### ISSUE TITLE
When I use jectd to get all keys from etcd server,it occurs an error:RESOURCE_EXHAUSTED:gPRC message exceeds maximum size 4194304:17319112

### ISSUE THREAD

**Issue by linww** [etcd-io/jetcd#745]
When I use jectd to get all keys from etcd server,it occurs an error:RESOURCE_EXHAUSTED:gPRC message exceeds maximum size 4194304:17319112，and how can I increase the limit 4M for one request from ectd server?
![image](https://user-images.githubusercontent.com/10493366/80661777-3672c080-8ac2-11ea-9de9-84507b2f38c0.png)

**Comment by lburgazzoli** [comment]
You can use `maxInboundMessageSize`, see https://github.com/etcd-io/jetcd/blob/55a4de66dd6934b33303a1e268762815d33e8a0c/jetcd-core/src/main/java/io/etcd/jetcd/ClientBuilder.java#L320

**Comment by linww** [comment]
> You can use `maxInboundMessageSize`, see
> 
> https://github.com/etcd-io/jetcd/blob/55a4de66dd6934b33303a1e268762815d33e8a0c/jetcd-core/src/main/java/io/etcd/jetcd/ClientBuilder.java#L320

Thanks a lot,it works!
