### ISSUE TITLE
KeepAlive doesn't have effort when there are tens of thousands of lease

### ISSUE THREAD

**Issue by peopleone** [etcd-io/jetcd#749]
I invoke keepAlive method which in the Class of LeaseImpl for 25,000 leases when running the performance test.When using cmd "`etcdctl endpoints  lease list | wc -l`" to get the size,i found that when the size up to 25000 or more,the keepAlive method in LeaseImpl has no effort.I have seen a gradual decline in the number of lease,and the log printed that the lease already expired.

What i miss is why the keepalive method doesn't work  and how can i  make the lease keep alive?

**Comment by lburgazzoli** [comment]
It is probably keeping more time to refresh them than the TTL, btw are you creating 25000 leases for benchmark purpose or it is a real use case ?

**Comment by peopleone** [comment]
> It is probably keeping more time to refresh them than the TTL, btw are you creating 25000 leases for benchmark purpose or it is a real use case ?

it is a real use case in our web application,may be more than 25000 when running.I think is the 
 etcd cluster blocking while creating lease ? if the etcd cluster  took too long to grant lease,when the cluster try to keep alive ,the lease already expired/

**Comment by lburgazzoli** [comment]
that could be, do you have time to digg into the issue ?

**Comment by peopleone** [comment]
> that could be, do you have time to digg into the issue ?

I tried to trace the keepalive request and found that the keep alive request was send every 500 mills,but didn't get any response ,so that the KeepAlive Object still old value.I was ashamed that the problem has not yet been identified.May be  jectd , or etcd .
