### ISSUE TITLE
Make managed channel connection timeout configurable.

### ISSUE THREAD

**Issue by jcferretti72** [etcd-io/jetcd#769]
Hello,

First of all, thanks for all your work on making jetcd possible.

We are using jetcd in a Java application connecting to an etcd cluster of 3 peers.  When one of the peers is down, our application is hitting our own defined timeout of 10 seconds for waiting for a future response on a KV put.

An explanation of the jetcd logic similar to
  https://etcd.io/docs/v3.3.12/learning/client-architecture/
would be useful to try to understand what is the failover behavior and timing expectations for fialover, when an etcd peer is down, for setting our own application level timeout.

In particular, if an etcd peer is down, and that down peer had been selected by the jetcd grpc load balancer for the underlying grpc channel, would the individual grpc stub be automatically retried on another healthy peer (assume cluster consensus still exists, eg, 2 out of 3 peers still healthy in a 3 member cluster), without failing to the application?.  If yes, what is the deadline for jetcd retrying in the failed peer versus switching to retry in a different peer?   If no, what is the expected way an application using jetcd can retry that stub?

Thanks in advance,

-Cristian

**Comment by jcferretti72** [comment]
After enabling grpc logging (which was very tricky btw), we figured out what out issue is.  It results from the interaction on idle timeout and connection timeount.

When an idle jetcd client hits the idle timeout (30 minutes it seems), the channel is disconnected.  If one (say, in a cluster of 3) etcd server peer goes down at this point, and then the jetcd client attempts a stub operation, the channel logic will try to reconnect to all 3 peers and the stub will not be able to execute until the connection to the down peer times out (the default is 30 minutes too I believe).   This prevents proper fault tolerant behavior, stalling the operation of the client when one of the 3 etcd peer goes down.

**Comment by lburgazzoli** [comment]
@jcferretti72 what should we do on jetcd side ? 
As far as I recall, we don't do anything but we rely on the behavior of grpc-java in such case.

**Comment by jcferretti72** [comment]
I think the solution would be to add a `connectionTimeoutMillis` Integer option to `ClientBuilder`, and then use it from ClientConnectionManager, very similar to how `maxInboundMessageSize` is handled already:

```
    @VisibleForTesting
    protected ManagedChannelBuilder<?> defaultChannelBuilder() {
         final NettyChannelBuilder channelBuilder = NettyChannelBuilder.forTarget("etcd");

         if (builder.maxInboundMessageSize() != null) {
             channelBuilder.maxInboundMessageSize(builder.maxInboundMessageSize());
         }
+        if (builder.connectTimeoutMillis() != null) {
+            channelBuilder.withOption(ChannelOption.CONNECT_TIMEOUT_MILLIS, builder.connectTimeoutMillis());
+        }
```

For a single peer etcd cluster the current default value is reasonable; this would allow customization from jetcd calling code to set a more reasonable value for 3 or 5 node clusters (where holding on a single peer down is not desirable, as discussed earlier).

Thanks in advance!

**Comment by lburgazzoli** [comment]
do you have any spare time to send a pr ?

**Comment by jcferretti72** [comment]
I can try to do that over the weekend.

**Comment by lburgazzoli** [comment]
Fixed by https://github.com/etcd-io/jetcd/pull/779
