### ISSUE TITLE
the memory leak happens when etcd connection timed out for a period of time

### ISSUE THREAD

**Issue by linww** [etcd-io/jetcd#786]
I run a thread which tries to using jetcd utils to connect to etcd every five minutes,but when the connection keeps unavailable and the connection is  timed out ,some time later, memory leak happens,the heap memory keeps increasing,how should I close the connection and release the object(etcd client) when the connection is timed out? Is it because that jetcd util will retry to connetc when it connects failure or the ManageChannel isn't shutdown successfully when it connects timed out?

![image](https://user-images.githubusercontent.com/10493366/88752277-19669000-d18c-11ea-921f-e0dbd3d2d914.png)

![image](https://user-images.githubusercontent.com/10493366/88752309-3307d780-d18c-11ea-93dc-12c7adcb4a98.png)

![image](https://user-images.githubusercontent.com/10493366/88752337-431fb700-d18c-11ea-9379-518a81a30afe.png)

![image](https://user-images.githubusercontent.com/10493366/88761404-a700aa80-d1a1-11ea-8156-a4ba1809c0f2.png)

**Comment by lburgazzoli** [comment]
there's a reconnect policy you can configure to customize when the reconnection happens, however I don't know if the channel is properly closed.

@linww do you have time to investigate the issue and eventually open a PR ?

**Comment by linww** [comment]
> there's a reconnect policy you can configure to customize when the reconnection happens, however I don't know if the channel is properly closed.
> 
> @linww do you have time to investigate the issue and eventually open a PR ?

I am not authorized to upload the project code to github,but I can create a demo project for the PR,is it OK?

**Comment by lburgazzoli** [comment]
yes

**Comment by lburgazzoli** [comment]
@linww did you create the demo project ?
