### ISSUE TITLE
Role creation: line break issue

### ISSUE THREAD

**Issue by mcorbin** [etcd-io/jetcd#816]
Hello,

I'm trying to create an etcd role using jetcd. Here is my code:

```java
 public static void main (String[] args) {
        Client client = Client.builder().endpoints("http://localhost:2379").build();
        Auth auth = client.getAuthClient();
        AuthRoleAddRequest req = AuthRoleAddRequest.newBuilder().setName("myrole").build();

        auth.roleAdd(ByteSequence.from(req.toByteString())).join();
    }
```

When I execute this code, my role is created but the name starts with a line break. For example, I see in the etcd logs:

```
2020-08-31 09:54:08.843740 N | auth: Role 
myrole is created
```

With ectdctl:

```
./etcdctl role list

myrole
```

As you can see, the role starts with a `\n` (I don't have this behavior with I create roles from etcdctl). Am I doing something wrong in the code ?

I use these versions:

etcd version: 3.4.13
jetcd version: 0.5.3

Regards,

**Comment by mcorbin** [comment]
I also listed the created rome from Java:

```
       AuthRoleListResponse resp = auth.roleList().join();
        for (String role: resp.getRoles()) {
            System.out.println(role);
        }
```

The output is:

```
myrole
```

We see that the role is prefixed by a weird character.

**Comment by lburgazzoli** [comment]
I think the issues is that you are serializing the request but it is not the way it works as the method expect the role name, something like:


```
auth.roleAdd(ByteSequence.from("myrole", StandardCharset.UTF8)).join();
```

**Comment by mcorbin** [comment]
Indeed, `auth.roleAdd(ByteSequence.from("myrole2", StandardCharsets.UTF_8)).join();` works. I thought I had to use the *Request classes (AuthRoleAddRequest, AuthRoleDeleteRequest...) to manage roles.

Thanks you for the quick answer.
