### ISSUE TITLE
How to cancel keepalive

### ISSUE THREAD

**Issue by septyy** [etcd-io/jetcd#836]
When invoking keepalive, it will add a etcd keepAlive event which will periodically extend the lease by the internal etcd thread.  
I couldn't find a corresponding method to cancel the etcd keepAlive event. Maybe it will cause memory leak when another new leases would be added into the etcd keepAlive event queue.

**Comment by lburgazzoli** [comment]
if you are talking about https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/main/java/io/etcd/jetcd/Lease.java#L86, then it should be enough to close the client the methods returns.

**Comment by septyy** [comment]
If the client is not closed, many leaseId will be added to the etcd keepalive event queue continuously, will it eventually cause a memory leak?

**Comment by lburgazzoli** [comment]
can you add a little bit more details ? I'm not sure I follow

**Comment by septyy** [comment]
`
int ttl =1;
while(true){
long leaseID = leaseClient.grant(ttl).get().getID();
feature = kvClient.put(kvKey, kvValue, PutOption.newBuilder().withLeaseId(leaseID).build());
LeaseResponse.keepAlive(leaseClient, leaseID);
ttl++;
}
`
If the client is not closed, many leaseId will be added to the etcd keepalive event queue continuously, I couldn't find a corresponding method to cancel the etcd keepAlive event, maybe it eventually cause a memory leak.

**Comment by lburgazzoli** [comment]
not closing the client is a resource leak in your application, like it would be if you don't close an input stream, however doesn't [Lease::revoke](https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/main/java/io/etcd/jetcd/Lease.java#L60) work for you ?
