### ISSUE TITLE
is there a problem in the method close of the class ClientConnectionManager?

### ISSUE THREAD

**Issue by hubeicaolei** [etcd-io/jetcd#840]
hi,guys

I have got a  java.util.concurrent.RejectedExecutionException when I ran my project with jetcd, the log like as :

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@ab75a3b rejected from java.util.concurrent.ThreadPoolExecutor@5db34d1[Terminated, pool size = 6, active threads = 0, queued tasks = 0, completed tasks = 3107809]

I double checked my code, and found the root cause: in my project, I use the same executorService in the jetcd and my code, like as: 

**ExecutorService executorService = Executors.newCachedThreadPool();
executorService.execute(task);
....
Client client = Client.builder.executorService(executorService).endpoints("http://localhost:8379").build();
....
client.close();
...
...
executorService.execute(task);**

when the method close of the client was invoked, the executorService was shutdownNow, and I had got a RejectedExecutionException immediately after I excuted a task.

so I think it does not make sense that executorService is shutdown directly when closing the client. the executorService maybe be using by the other codes in that time.

 maybe fix the problem like as: 

void close() {
        synchronized (lock) {
            if (managedChannel != null) {
                managedChannel.shutdownNow();
            }
        }
        **_if (builder.executorService() == null) {
            executorService.shutdownNow();
        }_**
 }

**Comment by lburgazzoli** [comment]
mind sending a pr to fix it ?

**Comment by hubeicaolei** [comment]
I'm pleasure to fix it. will send a pr tomorrow.
