### ISSUE TITLE
retryMaxDuration not respected for the Lock

### ISSUE THREAD

**Issue by magiccrafter** [etcd-io/jetcd#847]
**Problem:**  
When `retryMaxDuration` is set I expect that any lock after the first `c.getLockClient().lock()` will keep retrying to get the lock until the `retryMaxDuration` is reached. Sadly based on my tests thats not the case.

```java
Client c = Client.builder()
                .endpoints("http://localhost:32784")
                .namespace(bs("test"))
                .retryMaxDuration("PT10S")
                .build();

        LeaseGrantResponse lease1 = c.getLeaseClient().grant(Duration.ofSeconds(60).toSeconds()).get();
        LockResponse lock1 = c.getLockClient().lock(bs("worker_id"), lease1.getID()).get();
        System.out.println("lock_id: " + bsToStr(lock1.getKey()));
        LeaseGrantResponse lease2 = c.getLeaseClient().grant(Duration.ofSeconds(10).toSeconds()).get();
        // Doesn't work
        await().atMost(Duration.ofSeconds(15))
                .untilAsserted(() -> assertThrows(Exception.class,
                        () -> c.getLockClient().lock(bs("worker_id"), lease2.getID()).get())) ;
```

Here you can find the full code to reproduce the issue:
https://github.com/magiccrafter/jetcd-lock-retry
 
Not 100% sure if thats expected behaviour since I couldn't find anywhere in the documentation information about the way it is supposed to work. In the code is says: `the retries max duration`. 
and thats for the `io.etcd.jetcd.api.lock.Lock`:
```
/**
     * <pre>
     * Lock acquires a distributed shared lock on a given named lock.
     * On success, it will return a unique key that exists so long as the
     * lock is held by the caller. This key can be used in conjunction with
     * transactions to safely ensure updates to etcd only occur while holding
     * lock ownership. The lock is held until Unlock is called on the key or the
     * lease associate with the owner expires.
     * </pre>
     */
```
It doesn't say anything about what is expected on Error :(

**Comment by sudoHackIn** [comment]
@lburgazzoli may be we should add additional documentation, that retries only works on unsuccessful operations? (network and authentication problems?)

**Comment by lburgazzoli** [comment]
feel free to document it
