### ISSUE TITLE
Can provide watch async api usage?

### ISSUE THREAD

**Issue by septyy** [etcd-io/jetcd#856]
Sorry, I can not find the example how to call watch async ? Can you please share the example with UT or other ways?

**Comment by septyy** [comment]
Is there any update?

**Comment by lburgazzoli** [comment]
what do you mean exactly ?

**Comment by septyy** [comment]
Does the jetcd provide async watch implementation?

**Comment by lburgazzoli** [comment]
watch is asynchronous, have a look at https://github.com/etcd-io/jetcd/blob/master/jetcd-examples/jetcd-watch/src/main/java/io/etcd/jetcd/examples/watch/Main.java
