### ISSUE TITLE
question: Beta annotation for KV and Election clients

### ISSUE THREAD

**Issue by marcosflobo** [etcd-io/jetcd#857]
Hello,

There are 2 clients, KV and Election, which are annotated with `@Beta` meaning that "is declared as unstable interface"

May I ask why is still unstable and if there is a plan to make it stable?

Thanks for your time on this!

/question

**Comment by lburgazzoli** [comment]
I think they are leftovers, you are wlcome to send a PR to remove them

**Comment by marcosflobo** [comment]
I'll do, thanks!
