### ISSUE TITLE
jetcd depends on spotbugs, which is not compatible with APL 2.0

### ISSUE THREAD

**Issue by javasoze** [etcd-io/jetcd#861]
Though jetcd is APL 2.0, the included spotbugs-annotations is LGPL: https://github.com/spotbugs/spotbugs/blob/master/LICENSE

Its dependency should probably be removed: https://github.com/etcd-io/jetcd/blob/master/pom.xml#L315

**Comment by lburgazzoli** [comment]
@javasoze do you have time to work on a PR ?
