### ISSUE TITLE
Redacted

### ISSUE THREAD

**Issue by niklaskhf** [etcd-io/jetcd#880]
Redacted. Please feel free to delete this issue.

**Comment by lburgazzoli** [comment]
no, looks like a bug

**Comment by lburgazzoli** [comment]
@niklaskhf I have very limited time to look at the issue, do you maybe have some spare time to check what's going on and send a PR ?

**Comment by niklaskhf** [comment]
@lburgazzoli I'm unfortunately not really familiar with Java's gRPC and netty channels. I know that in the grpc-go library there is a dial option [WithBlock](https://pkg.go.dev/google.golang.org/grpc#WithBlock) that would block until the channel is connected, but can't find something similar for Java.  
At first I thought `connectTimeoutMs` would accomplish this, but on re-testing it doesn't seem to be solving the actual issue.  
It seems like the channel itself has an `isActive` function that would identify whether the channel is connected, so maybe this could be used in an optional blocking check with a configurable timeout after building the channel?  

Something like this, but really I'm just guessing here.
```
if (blockUntilAlive) {
    withTimeout(blockingConnectTimeout) {
        while(true) {
            if(channel.isAlive()) break 
            sleep(100)
        }
    }
}
```
