### ISSUE TITLE
When is the next release scheduled?

### ISSUE THREAD

**Issue by koo-taejin** [etcd-io/jetcd#900]
Hi, my name is Taejin.
First of all, I really thanks for creating such a wonderful project.

Currently, I am using jetcd in my personal project, and I am using grpc 1.36.1, 
and it is difficult to change the grpc version because some libraries used grpc.

I checked that my project does not work properly due to a compatibility issue with grpc 1.33.0 version and 1.36.1 version.
(Link to related issues.: https://github.com/grpc/grpc-java/issues/7211)

But, I have checked at the jetcd master branch, it already updated grpc version to 1.36.1

For above reason,  I am wondering about the release schedule of the source to which this version was applied.
If it is released, it will be of great help to me.
If you consider this part, I would really appreciate it.

Best Regards,

**Comment by lburgazzoli** [comment]
I'll try to do a release in the coming days

**Comment by cfz** [comment]
hi @lburgazzoli, do you have a release plan for this? if you have some TODO, i'm also willing to help. we heavily use jetcd in production.

**Comment by lburgazzoli** [comment]
Version 0.5.7 should be available soon on maven central

**Comment by lburgazzoli** [comment]
0.5.7 available on maven central https://search.maven.org/artifact/io.etcd/jetcd-core/0.5.7/jar
