### ISSUE TITLE
Can access to classes and methods be properly opened

### ISSUE THREAD

**Issue by breaksilence** [etcd-io/jetcd#914]
Why are most of the classes or methods final or private, which almost blocks the extension of jetcd

**Comment by breaksilence** [comment]
> use

1. When the grpc on which jetcd depends has a security problem and the grpc has to be upgraded, it may need to be compatible with jetcd

2. When I want to set retrypolicy, I find that it is a fixed write dead policy, and it is difficult to extend it

3. I want to add a specific implementation, such as implementing a custom clientimpl, but I can't inherit it. After copying the source code in time, it's difficult to reuse the internal logic, because the internal references are protected

**Comment by lburgazzoli** [comment]
> > use
> 
>     1. When the grpc on which jetcd depends has a security problem and the grpc has to be upgraded, it may need to be compatible with jetcd
> 
>     2. When I want to set retrypolicy, I find that it is a fixed write dead policy, and it is difficult to extend it
> 
>     3. I want to add a specific implementation, such as implementing a custom clientimpl, but I can't inherit it. After copying the source code in time, it's difficult to reuse the internal logic, because the internal references are protected

can you open an issue on point 2 and 3 ? I think the policy and the client impl can be eventually be mad possible, maybe you can provide also some example.
