### ISSUE TITLE
Hard for  custom clientimpl and set retrypolicy 

### ISSUE THREAD

**Issue by breaksilence** [etcd-io/jetcd#915]
this issue Discussion based on issue #914

1. When I want to set retrypolicy, I find that it is a fixed write dead policy, and it is difficult to extend it

2. I want to add a specific implementation, such as implementing a custom clientimpl, but I can't inherit it. After copying the source code in time, it's difficult to reuse the internal logic, because the internal references are protected

two simple case for this question:

case 1:In an environment where etcd is used as the registry center, etcd has its own problems, leading change happens occasionally. At this time, jetcd clients connectioned timeout. To adapt to this problem, I first looked at the source code to find the connection timeout retrial mechanism, and found that I can't adjust the client connection manager retrypolicy dynamically, However, the code cost of implementing clientImpl or ClientConnectionManageris very high. 

    static boolean isRetryable(Throwable e) {
        return isInvalidTokenError(Status.fromThrowable(e));
    }

    static boolean isInvalidTokenError(Status status) {
        return status.getCode() == Status.Code.UNAUTHENTICATED
            && "etcdserver: invalid auth token".equals(status.getDescription());
    }

case 2: Another scenario is that we find that there is a security problem with grpc dependency, which leads to the incompatibility of jetcd ,In case of emergency, I may first hope to extending my jetcd connection implementation

**Comment by lburgazzoli** [comment]
@breaksilence can you provide some exemplar code about what you are doing as today ?

**Comment by breaksilence** [comment]
> @breaksilence can you provide some exemplar code about what you are doing as today ?

ClientImpl and ClientConnectionManager is not public , Client is a interface , ClientConnectionManager  is not a public class, when I want custom implementation , overwrite some method ,not easy to did it

**Comment by lburgazzoli** [comment]
This was clear but I need some clear examples as most of the classes are not supposed to be overridden by the user.

The fact that we have interface is mainly for implementation purpose so I need to understand what are the bits that may need to be customized and then I can evaluate the introduction of the right extension points but you can understand that we cannot open everything up as it would become impossible to maintain and support

**Comment by breaksilence** [comment]
>
 The current design is actually reasonable,If necessary I think we can start from two points. 
eg:
1.Open necessary parameters or configured API methods, such as timeout retry mechanism
2.Provide a basic abstraction layer to implement the necessary methods, liberalize the protection of classes, and provide the requirements of specific reconstruction scenarios

If the API method is flexible enough, the second point can be ignored. In fact, we do not expect to rewrite the components in the process of use, and the original API may be more strong


> This was clear but I need some clear examples as most of the classes are not supposed to be overridden by the user.
> 
> The fact that we have interface is mainly for implementation purpose so I need to understand what are the bits that may need to be customized and then I can evaluate the introduction of the right extension points but you can understand that we cannot open everything up as it would become impossible to maintain and support

**Comment by lburgazzoli** [comment]
> 1.Open necessary parameters or configured API methods, such as timeout retry mechanism 

You are very welcome to provide a PR 

> 2.Provide a basic abstraction layer to implement the necessary methods, liberalize the protection of classes, and provide the requirements of specific reconstruction scenarios

can you give a concrete example ?
