### ISSUE TITLE
request help ： using Jetcd watch api cannot receive evnet 

### ISSUE THREAD

**Issue by ysc972** [etcd-io/jetcd#927]
Hello . When I use Jetcd's Watch function after a while ,I put something to etcd with Jetcd  put api ,but My Application can not receive the put event. I don't know what the problem is caused by this problem.

**Comment by lburgazzoli** [comment]
it is very hard to provide any sort of help with issues reported this way as:

- no information about what are the versions of jetcd and etcd
- no logs / stack trace
- no reproducer

I have very little time to work on this project so if you are seeking for help, please try to set-up a reproducer (i.e. you can send a PR with a unit/integration test) and I'll do my best to help/fix the issue.

**Comment by ysc972** [comment]
Thank you for your reply. `jetcd-core.version`:`0.5.7`,`etcd version` : '3.5.0' .
My code is as follows. 

```
ByteSequence routeKey = ByteSequence.from(ROUTE_PATH, StandardCharsets.UTF_8);


Watch.Listener listener = Watch.listener(response -> {
    logger.info("Watching for key={}",ROUTE_PATH);

    for (WatchEvent event : response.getEvents()) {
        KeyValue keyValue = event.getKeyValue();
        String key = keyValue.getKey().toString(StandardCharsets.UTF_8);
        String value = keyValue.getValue().toString(StandardCharsets.UTF_8);
        logger.info("key = {},value= {} ",key,value);
        logger.info("type = {}",event.getEventType());
        switch (event.getEventType()){
            case PUT:
                Route route = Route.jsonToObject(value);
                RouteDb routeDb = new RouteDb(route);
                RouteDbRepository.SaveOrUpdate(routeDb);
                break;
            case DELETE:
                String id = key.replace(ROUTE_PATH, "");
                RouteDb deleteRouteDb = QueryCache.get(RouteDb.class, id);
                RouteDbRepository.delete(deleteRouteDb);
        }
    }
}
);
watchClient.watch(routeKey, WatchOption.newBuilder()
        .withPrefix(routeKey)
        .build(),listener);


```
Thank you.

**Comment by lburgazzoli** [comment]
This is the code of the watcher, I need some sort of a reproducer for the issue

**Comment by ysc972** [comment]
When this problem occurs, I didn't get any logs and stack trace. When I put something to etcd , the watch did not executed . I am waiting for this problem now. I would like to know when I use wacher api , need I use some api to keep alive with etcd . When the connettion of etcd disconected ,should I watcher again . Thank you for your reply .

**Comment by lburgazzoli** [comment]
it should automatically reconnect but now you are adding another info that war missing in the original description: are you saying that the problem happen after a disconnection ?

**Comment by ysc972** [comment]
I'm just guessing this is the reason. I closed etcd for a while and then restarted. The jetcd running normally.So, now I don’t know the cause of this problem.I don't know what I should do when the problem happend again . The watcher does not execute ,so i can not get any log or stack trace . Thank you for your reply .

**Comment by lburgazzoli** [comment]
can you maybe enable more tracing on etcd and jetcd ? 
so maybe etcd would report additional info ?

In the past I saw some issue because jetcd was not reconnecting properly or because there were issues in re-starting the etcd cluster so some node did not receive any update.

Maybe you can also add a callback to the watcher for the error and log it.

**Comment by ysc972** [comment]
I only ran one etcd node. I don't know if it is caused by this.

My startup command is as follows.


```
nohup ./etcd --name infra1 --listen-client-urls http://10.10.150.14:2379 --advertise-client-urls http://10.10.150.14:2379 &
```
