### ISSUE TITLE
Support for RequestProgress for Watch?

### ISSUE THREAD

**Issue by mikehuston** [etcd-io/jetcd#928]
I'd like to use the RequestProgress functionality added https://github.com/etcd-io/etcd/pull/9869 in this Java etcd client.

Use case is similar to the one mentioned in that PR; I'd like to maintain an in-memory cache of an etcd key range and use RequestProgress in combination with a quorum read so that I can know when my cached data may be out of date.

I looked at the Watch [interface](https://github.com/etcd-io/jetcd/blob/02b9e226d25ce32db75a6a1dfb34899e0353f334/jetcd-core/src/main/java/io/etcd/jetcd/Watch.java) and [impl](https://github.com/etcd-io/jetcd/blob/02b9e226d25ce32db75a6a1dfb34899e0353f334/jetcd-core/src/main/java/io/etcd/jetcd/WatchImpl.java) and it did not appear RequestProgress support had been added yet. Are there plans to add this functionality and/or would you welcome a pull request if I can find time?

**Comment by lburgazzoli** [comment]
A PR would be very welcome !

**Comment by mikehuston** [comment]
Excellent, thanks @lburgazzoli! I'll take a shot at a PR, using the Go client change as a reference.

**Comment by juliankung-db** [comment]
PR opened for this change https://github.com/etcd-io/jetcd/pull/957

**Comment by mikehuston** [comment]
Thanks @juliankung-db! (we work at same company). After this merges, @lburgazzoli do you know how soon a new release including it might be available? We're trying to weigh different options for being able to use this functionality in our company's codebase. Many thanks!

**Comment by juliankung-db** [comment]
Thanks for the quick turnaround on the review and merge @lburgazzoli :^)

In terms of the release, it'd be great on our side if it'd be possible to create a new release in the next week or two (please let us know if we can help). If not, we can look at short-term workarounds until the next release.

**Comment by lburgazzoli** [comment]
> In terms of the release, it'd be great on our side if it'd be possible to create a new release in the next week or two (please let us know if we can help). If not, we can look at short-term workarounds until the next release.

I can plan to do a release over the week-end or beginning next week.
Ping me if you don't hear back from me about the release.

**Comment by lburgazzoli** [comment]
Sorry for the delay, I have released it now.
Should be available on maven central in a few hours

**Comment by lburgazzoli** [comment]
@juliankung-db can we close this issue now ?

**Comment by juliankung-db** [comment]
Yep, looks like everything's good and working on our end, thanks :^)

Feel free to close it, @mikehuston is OOO until next week so he won't be able to close it until then
