### ISSUE TITLE
Change prefix param type to boolean.

### ISSUE THREAD

**Issue by horizonzy** [etcd-io/jetcd#934]
the param prefix at get api is ByteString, it's weird, it can be replace by boolean.

https://github.com/etcd-io/jetcd/blob/76637dc28dcf1beef89c5e07cb3a32cbff86231f/jetcd-core/src/main/java/io/etcd/jetcd/options/GetOption.java#L180-L185

**Comment by horizonzy** [comment]
At go version, prefix is a flag which to get value by input key prefix. We just need `set prefix = true or false`, instead of `set prefix = key` again. It makes me confuse, after see the source code, I understant it. 
So make the prefix param easier to understand, modify the param type, user didn't set key as the prefix value again.

**Comment by lburgazzoli** [comment]
Ok, I think we need two thing here otherwise is even more confusing:
- withPrefix does not sound right for a boolean value, it seems to suggest you have to provide a prefix, maybe isPrefix could be better
- it need to be handled consistently in any method not only Get

**Comment by horizonzy** [comment]
That's fine.

**Comment by horizonzy** [comment]
All done, see the newest commit.

**Comment by lburgazzoli** [comment]
Fixed by https://github.com/etcd-io/jetcd/pull/935
