### ISSUE TITLE
Resuming a watch on the latest revision that may be older than requested by the caller

### ISSUE THREAD

**Issue by jtgrabowski** [etcd-io/jetcd#946]
`WatcherImpl` sets the internal `revision` to `WatchOption#getRevision()` during instantiation but `WatcherImpl` overwrites the field on stream creation [here](https://github.com/etcd-io/jetcd/blob/8270c7301b0e7de2a359d0f772b5597b677ff097/jetcd-core/src/main/java/io/etcd/jetcd/WatchImpl.java#L221) with the latest existing revision.
If the latest existing revision is older than the provided by the caller via `WatchOption`, a `resume` fetches the latest existing revision. 
Here's an example.
- a watcher is created with requested revision 100, etcd server knows about revision 40
- the internal `revision` field of the watcher is overwritten with revision 40
- the watcher is resumed due to a network failure with revision 40
- revision 40 is propagated to the caller despite the fact that the caller explicitly asked for revision 100 and newer
- new incoming revisions (41, ...) will be passed to the caller as well

**Comment by lburgazzoli** [comment]
What should be the behavior here ? 
Should the call fail because the revision do not exists ?

**Comment by jtgrabowski** [comment]
We could simply resume on the provided revision if it's newer than the latest existing. 
afaik etcd server doesn't consider calls with "future revisions" as invalid.

**Comment by lburgazzoli** [comment]
ok, make sense: do you have any time to work on a pr ?

**Comment by jtgrabowski** [comment]
Yeah, I'll create a PR.

**Comment by lburgazzoli** [comment]
That's really appreciated, I have very limited time so contributions are really welcome

**Comment by jtgrabowski** [comment]
The PR is ready.
