### ISSUE TITLE
ClientConnectionManager retries work only for auth errors

### ISSUE THREAD

**Issue by jtgrabowski** [etcd-io/jetcd#947]
`Util.isRetryable` returns `true` only for token auth errors which seams like a typo. Should we retry on everything but auth errors?
As a result retries don't work for intermittent failures like temporary unavailability of etcd server.

**Comment by lburgazzoli** [comment]
As far as I remember the idea was that if the token is expired, then we should retry and regenerate one so it may be still a valid case.

**Comment by jtgrabowski** [comment]
Thanks, that makes sense. I refreshed the attached PR so that `UNAVAILABLE` and token errors are retried.
