### ISSUE TITLE
run exception

### ISSUE THREAD

**Issue by zliangliang1024** [etcd-io/jetcd#956]
```
ERROR 15388 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [Channel<3>: (etcd)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V
	at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:172) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.netty.Utils.access$000(Utils.java:71) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:93) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:140) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:231) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:258) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:200) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95) [grpc-api-1.39.0.jar:1.39.0]
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127) [grpc-api-1.39.0.jar:1.39.0]
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1863) [grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.NameResolver$Listener2.onAddresses(NameResolver.java:208) [grpc-api-1.39.0.jar:1.39.0]
	at io.etcd.jetcd.resolver.SmartNameResolver.doResolve(SmartNameResolver.java:141) [jetcd-core-0.5.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_271]
```

**Comment by lburgazzoli** [comment]
can you please provide a reproducer or at least the instruction to reproduce it ?

**Comment by zhengyuyzhao** [comment]
tai la ji la ba

**Comment by zliangliang1024** [comment]
> can you please provide a reproducer or at least the instruction to reproduce it ?

just use example, ctl and watcher both exception

```
// create client
        Client client = Client.builder().endpoints("http://localhost:2379").build();
        KV kvClient = client.getKVClient();

        ByteSequence key = ByteSequence.from("test_key".getBytes());
        ByteSequence value = ByteSequence.from("test_value".getBytes());

// put the key-value
        kvClient.put(key, value).get();

// get the CompletableFuture
        CompletableFuture<GetResponse> getFuture = kvClient.get(key);

// get the value from CompletableFuture
        GetResponse response = getFuture.get();
        System.out.println("res：" + response);
```

**Comment by zhengyuyzhao** [comment]
![image](https://user-images.githubusercontent.com/23691991/126960493-4525809e-edba-4717-a365-9330b32c0af3.png)

**Comment by lburgazzoli** [comment]
> > can you please provide a reproducer or at least the instruction to reproduce it ?
> 
> 
> 
> just use example, ctl and watcher both exception
> 
> 
> 
> ```
> 
> // create client
> 
>         Client client = Client.builder().endpoints("http://localhost:2379").build();
> 
>         KV kvClient = client.getKVClient();
> 
> 
> 
>         ByteSequence key = ByteSequence.from("test_key".getBytes());
> 
>         ByteSequence value = ByteSequence.from("test_value".getBytes());
> 
> 
> 
> // put the key-value
> 
>         kvClient.put(key, value).get();
> 
> 
> 
> // get the CompletableFuture
> 
>         CompletableFuture<GetResponse> getFuture = kvClient.get(key);
> 
> 
> 
> // get the value from CompletableFuture
> 
>         GetResponse response = getFuture.get();
> 
>         System.out.println("res：" + response);
> 
> ```

did you copy the examples or run them from the jetcd repo ?

**Comment by zliangliang1024** [comment]
> > > can you please provide a reproducer or at least the instruction to reproduce it ?
> > 
> > 
> > just use example, ctl and watcher both exception
> > ```
> > 
> > // create client
> > 
> >         Client client = Client.builder().endpoints("http://localhost:2379").build();
> > 
> >         KV kvClient = client.getKVClient();
> > 
> > 
> > 
> >         ByteSequence key = ByteSequence.from("test_key".getBytes());
> > 
> >         ByteSequence value = ByteSequence.from("test_value".getBytes());
> > 
> > 
> > 
> > // put the key-value
> > 
> >         kvClient.put(key, value).get();
> > 
> > 
> > 
> > // get the CompletableFuture
> > 
> >         CompletableFuture<GetResponse> getFuture = kvClient.get(key);
> > 
> > 
> > 
> > // get the value from CompletableFuture
> > 
> >         GetResponse response = getFuture.get();
> > 
> >         System.out.println("res：" + response);
> > ```
> 
> did you copy the examples or run them from the jetcd repo ?

yes

**Comment by lburgazzoli** [comment]
@zliangliang1024 yesy to what of the question ?

**Comment by lburgazzoli** [comment]
I have followed the readme document in the example folder and they are working as expected 
If you have copied the code in your project, please be sure the netty version is compatible with grpc-java

**Comment by zliangliang1024** [comment]
> I have followed the readme document in the example folder and they are working as expected
> If you have copied the code in your project, please be sure the netty version is compatible with grpc-java

relation dependencies just follow，i have not depdency netty alone, example dependenies also follow
```
    implementation "io.grpc:grpc-all:1.39.0"
    implementation group: 'com.google.protobuf', name: 'protobuf-java', version: '3.17.3'
    compile "io.etcd:jetcd-core:0.5.0"
```

**Comment by lburgazzoli** [comment]
it may come transitively from the grpc dependency so better not to declare it as it would come automatically from jetcd.

**Comment by zliangliang1024** [comment]
> it may come transitively from the grpc dependency so better not to declare it as it would come automatically from jetcd.

ok, thank you very much, i need  modify grpc-all version is 1.27.1 , because jetcd grpc-netty version is 1.27.1
io.grpc:grpc-all:1.27.1 and io.etcd:jetcd-core:0.5.0 work correctly
suggest describing version correspondence  on the official website or readme

**Comment by zliangliang1024** [comment]
> > it may come transitively from the grpc dependency so better not to declare it as it would come automatically from jetcd.
> 
> ok, thank you very much, i need modify grpc-all version is 1.27.1 , because jetcd grpc-netty version is 1.27.1
> io.grpc:grpc-all:1.27.1 and io.etcd:jetcd-core:0.5.0 work correctly
> suggest describing version correspondence on the official website or readme

**Comment by lburgazzoli** [comment]
you can use jetcd-all if you want to use a "self-containing" artifact as it shades all the needed dependencies.

**Comment by zliangliang1024** [comment]
> you can use jetcd-all if you want to use a "self-containing" artifact as it shades all the needed dependencies.

ok,I tried it just now ，it's also work correctly,thank you!

**Comment by LERSONG** [comment]
@zhengyuyzhao 你的问题解决了吗？我也有同样的问题

**Comment by lburgazzoli** [comment]
@LERSONG @zhengyuyzhao would be nice to use english here

**Comment by zhengyuyzhao** [comment]
State secrets

**Comment by LERSONG** [comment]
@zhengyuyzhao i use netty-buffer-4.1.66.Final in jetcd-core-0.5.10, then it run successfully. 
`

             <dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-buffer</artifactId>
			<version>4.1.66.Final</version>
			<exclusions>
				<exclusion>
					<groupId>io.netty</groupId>
					<artifactId>netty-common</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-common</artifactId>
			<version>4.1.66.Final</version>
		</dependency>

		<dependency>
			<groupId>io.etcd</groupId>
			<artifactId>jetcd-core</artifactId>
			<version>0.5.10</version>
			<exclusions>
				<exclusion>
					<groupId>io.netty</groupId>
					<artifactId>netty-buffer</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.netty</groupId>
					<artifactId>netty-common</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
`

**Comment by LERSONG** [comment]
@zhengyuyzhao u can see [https://github.com/yametech/etcd-registry-spring-boot-starter](url)
