### ISSUE TITLE
jetcd-core v0.5.10 keepAlive terminates with a call to onComplete after some time

### ISSUE THREAD

**Issue by jeet129** [etcd-io/jetcd#965]
```
Client client = Client.builder().endpoints("http://localhost:2379").build();
Lease leaseClient = client.getLeaseClient();
        Long leaseid = leaseClient.grant(60).get().getID();
        //leaseClient.keepAliveOnce(leaseid, )
        leaseClient.keepAlive(leaseid, new StreamObserver<LeaseKeepAliveResponse>() {
            @Override
            public void onNext(LeaseKeepAliveResponse leaseKeepAliveResponse) {
                System.out.println("Lease renewed at "+ LocalDateTime.now() + " for "+ leaseKeepAliveResponse.getTTL());
            }

            @Override
            public void onError(Throwable throwable) {
                System.out.println("Error occurred"+throwable.getCause());
            }

            @Override
            public void onCompleted() {
                System.out.println("Completed the renewal");
            }
        });
```
        
  As per the documentation the keepAlive should renew the lease till the time application is running. I am calling this snippet from main method which keeps on running but still the lease expires after some time (a random time like 20 minutes, 30 minutes or so) with receiving a callback for onCompleted() method of observer. 

Please help with fixing this issue. Looks like the keepAlive retry is not happening after a certain time and hence the lease expires resulting in call to onCompleted.

**Comment by jeet129** [comment]
@lburgazzoli need your input on this. This is a very basic use case where in I want to keep the lease alive for the duration application is running or it is explicitly revoked. It should have worked as per the API docs.

**Comment by lburgazzoli** [comment]
There should be an error happening in background or an error not recovered properly as the ttl here is 60 seconds but the `onCompleted` happens after 20/30 minutes, do you have any chance to increase the log level on both the client and the server and see what is happening ?

**Comment by jeet129** [comment]
Hello @lburgazzoli thanks for your response. I did increased the log visibility to DEBUG but I am not seeing any error or any abnormal events in both java client and etcd server logs.

**Comment by johnxiaohe** [comment]
My Project get This Error after start 5s. And Watcher not Work

**Comment by johnxiaohe** [comment]
I want to know which startup configuration of ETCD affects Jetcd's remote KeepAlive and Watch request operations. Or Jetcd client Build parameters affect the success or failure of KeepAlive and Watch requests

**Comment by johnxiaohe** [comment]
default deadline after 5s

**Comment by johnxiaohe** [comment]
3.4.7 and 3.5.0 version not work with module of simple auth or non auth. it work with SSL/TLS auth module.
Maybe KeepAlive and Watch only support GrpcConn operation?
