### ISSUE TITLE
concurrent update  fail

### ISSUE THREAD

**Issue by pioneer-hash** [etcd-io/jetcd#967]
The update fails in concurrent situations but no error message is reported
Let's write it this way:
```java
 for (int i=0;i++;i<2;) {
key="test"
json="{
    "num": i
}"
EtcdClient.get().getKVClient().put(ByteSequence.from(key.getBytes()), ByteSequence.from(json, charset));
}
```

**Comment by lburgazzoli** [comment]
This does not seems a concurrent update.
Can you provide a reproducer for the issue ?
