### ISSUE TITLE
Detecting connection errors

### ISSUE THREAD

**Issue by carlanton** [etcd-io/jetcd#970]
Hi!

What is the correct way to do KV requests with a timeout? The client seems to retry forever (jetcd 0.5.10).
My code looks like this:

```java
Client etcd = Client.builder()
        .endpoints("http://127.0.0.1:2379")
        .connectTimeout(Duration.ofSeconds(1))
        .build();

CountDownLatch countDownLatch = new CountDownLatch(1);
etcd.getKVClient()
        .get(ByteSequence.from("/x", StandardCharsets.UTF_8))
        .whenComplete((response, throwable) -> {
            if (throwable != null) {
                throwable.printStackTrace();
            }

            System.out.println("response = " + response);
            countDownLatch.countDown();
        });

countDownLatch.await();
System.out.println("done");
```

If I run this code without ectd running, it will never terminate. I've tried different retry options to the client builder but I can't get it to work.

Thanks,
Anton

**Comment by lburgazzoli** [comment]
you mean, you run the code without having etcd running at all ?
can you please create a test/reproducer for this issue ?

**Comment by carlanton** [comment]
Exactly! And I want to get notified if my application fails to connect the etcd server. I'll try to create a test.

**Comment by carlanton** [comment]
Hopefully this test (#971) makes sense.

Currently, when I do `future.get(10, TimeUnit.SECONDS)` I will get a TimeoutException since the future is not ready yet. The thing I would except is that the future completes exceptionally (because of too-many-reties or something), which then can be handeld with the CompletableFuture api. What do you think?

**Comment by lburgazzoli** [comment]
thx for the PR, I'll try to have a look at the issue in the coming days but I can't promise any ETA as I'm quite busy at the moment so if you have any spare time to digg into the issue, then it would be really appreciated.

**Comment by carlanton** [comment]
I think that the problem is related to gRPC's "[wait for ready](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md)" semantics. Currently it is enabled for all stubs (`.withWaitForReady()` in ClientConnectionManager). I updated the PR with a new setting in ClientBuilder that can disable it.

Another option could be to disable wait-for-retry completely  and rely on the Failsafe retry thing that is used for other kinds of failures...

**Comment by lburgazzoli** [comment]
> I think that the problem is related to gRPC's "[wait for ready](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md?rgh-link-date=2021-09-01T08%3A29%3A40Z)" semantics. Currently it is enabled for all stubs (`.withWaitForReady()` in ClientConnectionManager). I updated the PR with a new setting in ClientBuilder that can disable it.
> 
> Another option could be to disable wait-for-retry completely and rely on the Failsafe retry thing that is used for other kinds of failures...

The `wait-for-retry` option has been introduced by another user to avoid relying on failsafe so I think this is not an option for the moment

**Comment by mikehuston** [comment]
Thanks so much @carlanton @lburgazzoli for reporting and the analysis.

I've also been running into this (etcd client appears to retry forever and it would be helpful to be notified with exception after timeout).

Is there a recommended solution or workaround? Would @carlanton's proposal of adding `waitForReady` toggle in `ClientBuilder` break anything?

**Comment by lburgazzoli** [comment]
@mikehuston I think it can be an acceptable compromise, willing to send a PR ?

**Comment by carlanton** [comment]
I've updated #971 with a fix!

**Comment by mikehuston** [comment]
Thank you @lburgazzoli and @carlanton? 🙌  

Is there any chance a new release will be available soon-ish that includes https://github.com/etcd-io/jetcd/pull/971?

**Comment by lburgazzoli** [comment]
I'm waiting for feedback on another pr, then I can do a release

**Comment by carlanton** [comment]
Thanks a lot! 👍
