### ISSUE TITLE
Support for transaction and rollback on failure

### ISSUE THREAD

**Issue by mathewsreji** [etcd-io/jetcd#972]
Hello community

I've been trying to understand transactions in etcd a bit more clear. Have a requirement where we have multiple put operations on the etcd. 

Suppose, I have something as follows
1. PUT("path1/mykey1", "myvalue1)
2. PUT("anotherpath/mykey2", "myvalue2)
3. PUT("differentpath/mykey3", "myvalue3)

I need to ensure that even if my application fails / process dies / network drops at 3rd PUT, I should be able to rollback the effect of first 2 PUTS.  I am looking for something similar to the jdbc's transactional features where we can rollback on a failure. 

Is this feasible with [Txn interface](https://github.com/etcd-io/jetcd/blob/5996b0c63fceb0a7f3cf5f64c00ac40f968edfbe/jetcd-core/src/main/java/io/etcd/jetcd/Txn.java#L66) ?

Would love to see an example if anyone has done it.

Cheers
Reji

**Comment by lburgazzoli** [comment]
We have some tests here: https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/test/java/io/etcd/jetcd/KVTest.java#L182-L251

Not sure if they cover all your cases but you may give it a try
